- tools/ci/check_file_names.py
:cl:
fix: Тесты не будут больше ругаться на одинаковые названия файлов в папке для модулей
/:cl:
> Fix: CL wont check modular files for same names

- tools/ci/unticked_files.py
:cl:
fix: На этот раз точно пофиксил инклюды модульных файлов в тестах
/:cl:
> Fix: tickled files cl for modularity

- tools/ci/unticked_files.py
:cl:
fix: Проебал одну /
/:cl:
> Fix: THIS TIME CL works

- tools/ci/unticked_files.py
:cl:
fix: Если  щас не сработает - пойду спать. Фикс тестов.
/:cl:
> Fix: nested dme's stuff

- modular_ss220/fullscreen/_fullscreen.dm
- modular_ss220/fullscreen/_fullscreen.dme
- modular_ss220/fullscreen/code/client.dm
- modular_ss220/fullscreen/code/client_defines.dm
- modular_ss220/fullscreen/code/client_procs.dm
- modular_ss220/modular_ss220.dme
Adds fullscreen support
Fullscreen is good
:cl:
add: Fullscreen support
/:cl:
> feat: Fullscreen

- modular_ss220/modular_ss220.dme
- modular_ss220/prime_combat/_prime_combat.dm
- modular_ss220/prime_combat/_prime_combat.dme
- modular_ss220/prime_combat/code/weapons.dm
Добавляет модуль боевки прайма.
На текущий момент просто добавляет урон стабатону в два раза.
Не знаю
:cl:
add: Боевка прайма (станбатон двойной урон)
/:cl:
> [FEAT] Prime combat

- modular_ss220/crit_rework/_crit_rework.dm
- modular_ss220/crit_rework/_crit_rework.dme
- modular_ss220/crit_rework/code/_crit_rework_defines.dm
- modular_ss220/crit_rework/code/crit_rework_component.dm
- modular_ss220/crit_rework/code/crit_rework_mob.dm
- modular_ss220/modular_ss220.dme
Человек в крите получает трейты FLOORED (только ползает) и HAND_BLOCKED (не дает пользоваться руками).
Человек в крите не может общаться, кроме как шептать: рация и обычный разговор заблокированы.
Человек в крите при осмотре показывает, что он в стане.
Крит является концом боя и добавляет смертельности
Trust me
:cl:
add: Переработка крита. Крит теперь более опасен, делая куклу недееспособной
/:cl:
> [FEAT] Crit rework

- modular_ss220/pixel_shift/code/pixel_shift.dm
Двигает добавление компонента пиксель-шифта из инита в логин
Не надо нагружать лишний раз инит всеми ливингами
Запустил, потыкал
> [FIX] Pixel Shift - AddComponent moved from Initialize to Login

- modular_ss220/aesthetics/chairs/code/chairs.dm
- modular_ss220/crit_rework/code/crit_rework_mob.dm
- modular_ss220/modular_ss220.dme
- modular_ss220/prime_combat/_prime_combat.dm
- modular_ss220/prime_combat/_prime_combat.dme
- modular_ss220/prime_combat/code/weapons.dm
Написано в тайтле
:cl:
del: Механика софткрита ревертнута
tweak: Батон больше не наносит двойной урон
fix: Стулья шаттла вернулись
/:cl:
> Disable Softcrit, Delete Prime Combat, Fix seats

- modular_ss220/modular_ss220.dme
- tools/ci/unticked_files.py
Теперь на тиклинг будут проверяться и отключенные модули
> Fix: turned off modules support

- SQL/paradise_schema.sql
- SQL/updates220/49.220.1-49.220.2.sql
- code/__DEFINES/misc_defines.dm
- config/example/config.toml
- modular_ss220/emotes/code/emote_translations.dm
- modular_ss220/modular_ss220.dme
- modular_ss220/whitelist/_whitelist.dm
- modular_ss220/whitelist/_whitelist.dme
- modular_ss220/whitelist/code/whitelist.dm
:cl:
add: Улучшение вайтлиста. Автоматизация вписки.
fix: Несколько эмоутов работали некоректно
/:cl:
> Feat: whitelist database

- code/game/atoms_movable.dm
- code/game/mecha/mecha.dm
- code/game/objects/items/weapons/extinguisher.dm
- code/game/objects/structures/stool_bed_chair_nest/wheelchair.dm
- code/modules/mob/living/living.dm
- code/modules/mob/living/simple_animal/simple_animal.dm
- code/modules/mob/mob_vars.dm
- code/modules/vehicle/ambulance.dm
- code/modules/vehicle/vehicle.dm
Во имя процессора, оперативки и кодерского духа, РВивнь.
:cl:
fix: исправлены подёргивания при диагональном перемещении
/:cl:
> fix: primal RV code (fixes diag gliding jittering)

- modular_ss220/aesthetics/walls/code/walls.dm
Теперь у фальшстен такие же спрайты как у обычных
Секретки снова секретные
Trust Me
Broo
:cl:
fix: Неправильные спрайты у фальшстен
/:cl:
> Fix: Falsewall old sprite

- code/__DEFINES/dcs/signals.dm
- code/__DEFINES/is_helpers.dm
- code/__DEFINES/movement.dm
- code/_onclick/hud/parallax.dm
- code/controllers/subsystem/SSspacedrift.dm
- code/controllers/subsystem/SSthrowing.dm
- code/datums/components/orbiter.dm
- code/game/atoms.dm
- code/game/atoms_movable.dm
- code/game/mecha/mecha.dm
- code/game/objects/buckling.dm
- code/game/objects/structures/transit_tubes/transit_tube_pod.dm
- code/modules/mob/dead/observer/observer_base.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/carbon/human/human_movement.dm
- code/modules/mob/living/living.dm
- code/modules/mob/mob_emote.dm
- code/modules/mob/mob_movement.dm
- code/modules/recycling/disposal.dm
- code/modules/ruins/lavalandruin_code/puzzle.dm
- code/modules/vehicle/ambulance.dm
- code/modules/vehicle/vehicle.dm
- paradise.dme
> TESTMERGE fix: fix gliding

- code/datums/components/orbiter.dm
- code/game/objects/items/weapons/extinguisher.dm
- code/game/objects/structures/stool_bed_chair_nest/wheelchair.dm
- code/modules/mob/mob_movement.dm
> fix: fix RV

- code/modules/mob/living/living.dm
> fix: fix grabbed gliding

- code/game/atoms_movable.dm
> fix: call parent for `Move`

- .github/workflows/check_changelog.yml
- tools/changelog220/check_changelog.py
- tools/changelog220/tags.yml
> Feat WiP: changelog

- _maps/map_files220/cyberiad/cyberiad.dmm
> Compile fix

- modular_ss220/_defines220/_defines220.dme
- modular_ss220/_defines220/code/signals_mob/signals_mob_main.dm
- modular_ss220/_signals220/code/signals_mob/signals_mob_living.dm
- modular_ss220/pixel_shift/code/pixel_shift_component.dm
Фиксит неработающий pixelshifting
:cl:
fix: pixelshifting снова работает
/:cl:
> fix: make pixelshift work again

- code/modules/events/new_space_laws.dm
- modular_ss220/events/code/new_space_laws.dm
- paradise.dme
Отправка кода New Space Law в модуль
Хорошо для модульности
есь
:cl:
tweak: New Space Law goes full modularity
/:cl:
> Tweak: New Space Law goes full modularity

- code/modules/paperwork/folders.dm
- code/modules/paperwork/paper_bundle.dm
- code/modules/pda/PDA.dm
Исправляет кириллицу в папке, стопке бумаг.
Убирает пробелы до и после введёного кода аплинка
:cl:
fix: исправляет кириллицу в папке, стопке бумаг
fix: убирает пробелы до и после введёного кода аплинка
/:cl:
> fix: minor fixes

- _maps/map_files220/cyberiad/cyberiad.dmm
- modular_ss220/jobs/_jobs.dm
- modular_ss220/jobs/_jobs.dme
- modular_ss220/jobs/code/access.dm
- modular_ss220/modular_ss220.dme
:cl:
tweak: Теперь мед отдел не имеет доступа в рнд
tweak: Теперь ученый имеет доступ в теха
/:cl:
> Fix: accesses

- modular_ss220/unique_objects/code/unique_objects.dm
Фикс упущения с невозможностью сбора туалета второго уровня.
(какой ужас что у меня уже 3 ПРа с этим связано.)
Емагнутый фикснутый толкан:
:cl:
fix: Теперь можно собирать блюспейс толкан 2-го уровня.
/:cl:
> fix: BS NT Toilet 2 level

- code/game/objects/items/weapons/stunbaton.dm
- code/modules/security_levels/security_levels.dm
Переводит сообщения смены кодов доступа
Не будет смешной озвучки ТТСом
:cl:
add: переводит сообщения смены кодов безопасности
tweak: даёт возможность класть станпрод в рюкзак
/:cl:
> feat: translate security code change alerts

- _maps/map_files220/cyberiad/cyberiad.dmm
Перенос всех доступов (кроме кнопок) в хелперы.
Так же немного расширен доступ в техи отдела... отделам.
Стандартизация доступов с ранзнобоя в req_one_access_txt, в единичных случаях остаётся req_access_txt
В идеале, игроки не должны заметить разницы, сделано для удобства в будущем, легче добавлять доступы дверям и меньше путаницы, так как всё в хелперах.
Нечего показывать, увы
Походил, пооткрывал двери, я хуй знает, вроде ничего не проебал
:cl:
tweak: Перенос доступов из VV в хелперы
/:cl:
> Transferring door accesses to helpers.

- SQL/paradise_schema.sql
- SQL/updates220/49.220.2-49.220.3.sql
- code/__DEFINES/misc_defines.dm
- config/example/config.toml
- modular_ss220/whitelist/_whitelist.dme
- modular_ss220/whitelist/code/wl_admin.dm
:cl:
tweak: Теперь на прайме свои админы
/:cl:
> Feat: wl admins

- code/game/objects/buckling.dm
"Пристёгивание" к мебели не находясь непосредственно на ней.
Было сделано для оффов, но у них там наплыв ПРов, так что висит уже почти 3 недели...
В общем заливаем и молимся что примут.
Меньше пиксель-хантинга
https://github.com/ParadiseSS13/Paradise/assets/69762909/1d6dd2e3-8c00-4f48-a7d9-9e933465ac41
Да. Но может что-то упустил
:cl:
tweak: Теперь сесть можно не стоя на стуле.
/:cl:
> Tweak: Nearby buckling

- modular_ss220/text_to_speech/code/hear.dm
Фиксит варнинги в коде ттс, связанные с обновленным проком рации
> Fix: hear_radio in tts

- paradise.dme
Двигает коммент в .dme, тк в .dme тесты не расчитаны на то, что комментарий будет на той же строке, что и инклюд.
> Fix: Tickled CL

- _maps/map_files220/cyberiad/cyberiad.dmm
- modular_ss220/aesthetics/floors/code/floors.dm
- Исправления
- Стандартизация
- Чистка вар эдитов
Надо надо
DIFF
На добром слове
:cl:
tweak: Стандартизация и чистка вар эдитов
fix: Множественные исправления на Кибериаде
/:cl:
> Cyberiad: Cleanup, standartization, fixes

- _maps/map_files220/delta/delta.dmm
- modular_ss220/_maps220/code/Areas/station.dm
Изменен инженерный отдел Дельты, добавлена новая зона.
- Немного переделана комната СМа, добавлены недостающие элементы для быстрого запуска двигателя. Немного переделан контур охлаждения, убран лишний аир алярм.
- В Атмосе убран ненужный охладитель, добавлены дополнительные риги и шкафчики, добавлено пара пустых канистр. Заменена зона комнаты контроля атмосов.
- Изменено Фойе инженерного отдела, добавлен корпус машины и запчасти для автолата.
- В каюте СЕ добавлен монитор СМа, плата автолата, в шкаф СЕ добавлен БРПД.
- В инженерке немного изменена проводка двигателя, добавлены шкафы, рации и твердая плазма. На защищенный склад добавлено немного металла, риги стоят ближе друг к другу. Инженерный склад ВКД был расширен, добавлены инструменты, джетпаки и т.д. 
- Новая зона для транзита на …
> Remap: Delta Engineering 

- _maps/map_files220/delta/delta.dmm
Как блять это вышло?
:cl:
fix: Delta linter fix
/:cl:
> Delta linter fix

- _maps/map_files220/RandomRuins/SpaceRuins/whiteship.dmm
- config/example/config.toml
- modular_ss220/_maps220/code/RandomRuins/space_ruins.dm
- modular_ss220/_maps220/code/mobs.dm
Замена оффовского  ̶н̶е̶д̶о̶р̶а̶з̶у̶м̶е̶н̶и̶я̶ ̶ медицинского корабля на новый (port from RuParadise)
Добавление в модули враждебных симплов - undead (на оффах они почему то retaliate)
Лут: медицина, мини лазерный пистолет, шаттл
Больше косморуин - больше косморуин
Кнопки жмутся, зомби дерутся
:cl:
add: враждебные симплмобы - undead
tweak: замена косморуины whiteship
/:cl:
> SpaceRuin - White Ship

- _maps/map_files220/cyberiad/cyberiad.dmm
Исправления по запросам
- Подвинута печать СЕ
- Убран маяк синги/теслы
- Добавлен душ, кнопки в комнате атмоса к СМу
- Исправлена зарядка СМЕСа в Гравгене
- Консоль камер у НТРа убрана
bruh
bruh
:cl:
fix: Кибериада: Фиксы инженерки по запросам
/:cl:
> Cyberiad: Engineering fixes by requests

- _maps/map_files220/delta/delta.dmm
Перенос отдела сервиса с пары на Офы
- Полностью перенесен отдел сервиса.
- Немного изменены техи бара/гидропоники.
Ну красивее немного. Наверно.
кнопочки нажимал, бегал туды сюды
:cl:
tweak: Дельта: Перенос отдела сервиса и новые корявые техи
/:cl:
> Remap: Delta service

- _maps/map_files220/delta/delta.dmm
Разделил центральный холл на несколько зон, дабы не был обесточен по КД и клоун не игрался с файралярмами.
Подсоединил АПЦшки которые забыл подсоединить в ходе рефактора.
Фиксы багов
MapDIFF
Загрузил локалку, прогнал дебаггер, полетал и посмотрел через некоторое время.
Старый SDMM снова насрал кучей строчек, увы.
:cl:
fix: Починил свет на Керберосе.
/:cl:
> Delta: APC and Central Hall Areas fix

- modular_ss220/maps220/_maps220.dme
- modular_ss220/maps220/code/Station/cyberiad.dm
- modular_ss220/maps220/code/Station/delta.dm
- modular_ss220/maps220/code/nanomap.dm
- tools/github-actions/nanomap-renderer-invoker.sh
:cl:
fix: Наномапы теперь рендерятся для наших карт
/:cl:
> Fix: nanomap render for 220 maps

- _maps/map_files220/cyberiad/cyberiad.dmm
- _maps/map_files220/delta/delta.dmm
- modular_ss220/aesthetics/decals/code/decals.dm
- modular_ss220/maps220/code/Areas/station.dm
Чиню то что сломалось после ребейза на картах.
> fix: Rebase map fixes

- _maps/map_files220/cyberiad/cyberiad.dmm
- _maps/map_files220/delta/delta.dmm
Удалил неиспользуемые переменные у полов.
Меньше мусора
Нет ничего что было бы заметно
Нет нужды
:cl:
del: Удалил неиспользуемые переменные у полов. Не должно быть заметно изменений.
/:cl:
> Del: Unused floor vars

- _maps/map_files220/cyberiad/cyberiad.dmm
Добавил добавленную оффами аркаду "NT Recruiter" на Кибериаду.
На дельту будет вместе с ремапом дорм.
Заведомо неудачный способ утихомирить ассистух.
Нет. :Clueless:
:cl:
add: Добавлена новая аркада на Кибериаду.
/:cl:
> Feat: NT Recruiter game (Cyberiad)

- modular_ss220/maps220/code/misc.dm
> Fix: Immortality for everyone

- SQL/paradise_schema.sql
Перемещает наши изменения бд в самый низ, что бы не путаться.
Не влияет на игроков
> Tweak: moved ss220 sql edits to the down of the parascheme

- modular_ss220/aesthetics/airlocks/code/airlock_assembly_types.dm
- modular_ss220/aesthetics/airlocks/code/airlock_types.dm
Реорганизация и фикс недостающего
-
-
lmao
:cl:
tweak: Реорганизация и фиксы аирлоков
/:cl:
> Feat: Reorganize and fix airlocks

- _maps/map_files220/delta/delta.dmm
Передвинул барбера в сервис, где ему и место.
Расширил и передвинул аркаду.
Сделал 2 спальни.
Добавил болты в парашу.
Все к этому привыкли.
Запустил локалку, потыкал кнопочки.
:cl:
fix: Подвинул пару ламп, которые не надо двигать. (Delta)
tweak: Добавил болты в барашу. (Delta)
tweak: Барбер переехал в сервис. (Delta)
tweak: Аркада стала чуть больше. (Delta)
add: В дормы добавлены 2 спальни. (Delta)
/:cl:
> Delta dorms bedrooms and barber relocation

- _maps/map_files220/delta/delta.dmm
На дельту добавлен гейт.
Немного изменена комната экспедиции и добавлены сами врата.
ну не зря же маперы старались.
Моё стандартное бегал кнопочки нажимал.
:cl:
add: На Дельту добавлен гейт.
/:cl:
> New: Delta gateway

- modular_ss220/objects/code/miscellaneous.dm
Closes https://github.com/orgs/ss220club/projects/2?pane=issue&itemId=38786582
...
...
в игре
:cl:
add: Кошелёк теперь вмещает кольца и ключи шифрования
/:cl:
> Feat: Add more items that wallets can hold

- SQL/updates220/51.220.4-51.220.5.sql
- code/__DEFINES/misc_defines.dm
- config/example/config.toml
- modular_ss220/donor/_donor.dm
- modular_ss220/donor/_donor.dme
- modular_ss220/donor/code/client_procs.dm
- modular_ss220/modular_ss220.dme
:cl:
add: Поддержка нашей системы донатов через бусти
/:cl:
> Feat: parashiz don

- _maps/map_files220/cyberiad/cyberiad.dmm
Возвращена комната пыток на Кибериаде.
Я люблю причинять людям боль.
:cl:
add: Возвращена комната пыток на Кибериаде.
/:cl:
> Feat: Interrogation room (Cyberiad)

- tools/tgs_scripts/InstallDeps.sh
- tools/tgs_scripts/PreCompile.sh
Исправляет некоторые косяки в скриптах для тгс
> Fix: More-tgs-fixes

- _maps/map_files220/delta/delta.dmm
Поменял зону incinerator на turbine
Больше логики.
Нет.
:cl:
fix: У турбины теперь правильная зоны
/:cl:
> Fix: Turbine area

- _maps/map_files220/cyberiad/cyberiad.dmm
Содержит визуальные улучшения:
- Рума локеров
- Оружейная
- Туалеты
- Увеличен брифинг рум
- Переложена плитка в холле
а
В игре
:cl:
tweak: Кибериада: Улучшение Брига, часть 1
/:cl:
> Feat: Cyberiad Brig update 1

- _maps/map_files220/RandomRuins/LavaRuins/scp_facility.dmm
Заменяет труп с ЦК картой в СЦП комплексе на лаве, теперь там учёный с картой.
Потому что я долбоёб
Ноуп
Запустил локалку, лежи учёный со своей картой.
:cl:
fix: Убрал труп с ЦК картой в СЦП комплексе на лаве, теперь там учёный.
/:cl:
> Fix: CC ID Card

- _maps/map_files220/cyberiad/cyberiad.dmm
- _maps/map_files220/delta/delta.dmm
Лёгкая чистка перед полным обдристыванием карт скриптом
Это хорошо для мапперов
Ноуп
Может ещё отсосать?
:cl:
spellcheck: Подготовка карт к полной очистке, не должно быть заметно.
/:cl:
> Ref: Light Prefab Cleanup

- _maps/map_files220/RandomRuins/LavaRuins/scp_facility.dmm
- _maps/map_files220/RandomRuins/SpaceRuins/convoy_ambush.dmm
- _maps/map_files220/RandomRuins/SpaceRuins/destroyed_infiltrator.dmm
- _maps/map_files220/RandomRuins/SpaceRuins/infected_ship.dmm
- _maps/map_files220/RandomRuins/SpaceRuins/mechtransport_new.dmm
- _maps/map_files220/RandomRuins/SpaceRuins/spacehotel.dmm
- _maps/map_files220/RandomRuins/SpaceRuins/transit_bar.dmm
- _maps/map_files220/RandomRuins/SpaceRuins/voxraiders_1.dmm
- _maps/map_files220/RandomRuins/SpaceRuins/whiteship.dmm
- _maps/map_files220/RandomZLevels/blackmarketpackers.dmm
- _maps/map_files220/RandomZLevels/gate_lizard.dmm
- _maps/map_files220/RandomZLevels/terrorspiders.dmm
- _maps/map_files220/RandomZLevels/wildwest.dmm
- _maps/map_files220/cyberiad/cyberiad.dmm
- _maps/map_files220/delta/delta.dmm
- _maps/map_files220/generic/Admin_Zone.dmm
- _maps/map_files220/generic/Lavaland.dmm
- _maps/map_files220/generic/centcomm.dmm
- modular_ss220/maps220/code/directions.dm
Применяет скрипт залитый в https://github.com/ss220club/Paradise-SS220/pull/282
Написано в том ПРе
В соло не справлюсь, глазками пробежался, надо ещё по локалке побегать
:cl:
spellcheck: Проведён рефактор всей настенной машинерии, должно быть меньше мусора, не должно оказать практически никакого влияния на геймплей.
/:cl:
> Ref: Var's to Subtypes (PepePizdec)

- modular_ss220/maps220/code/directions.dm
фикс
:cl:
add: Фикс линтера
/:cl:
> Fix: Path lint

- modular_ss220/text_to_speech/code/_defines.dm
- modular_ss220/text_to_speech/code/seeds/silero.dm
Тиры взяты с РуПары и частично дополнены с нашей (всё что выше тир-1)
Возможно где-то проебаны тиры, где-то не так, но:
- Актуализирует список голосов TTS
- Добавляет тиры
Деньги капают на сервер
Фри
Тир1
Тир2
Тир3
Тир4
̶я̶ ̶х̶з̶ ̶к̶а̶к̶ ̶у̶ ̶м̶е̶н̶я̶ ̶в̶е̶т̶к̶а̶ ̶н̶е̶ ̶с̶ ̶т̶т̶с̶о̶м̶  
ладно ща протестирую, заебал...
протестировал
:cl:
add: Добавлено больше голосов
add: Добавлены тиры подписок для голосов
/:cl:
> Feat: first TTS update, tiers and voice actualization

- _maps/map_files220/cyberiad/cyberiad.dmm
- Добавляем Унику ГСБ и боевые перчатки в его ныне пустой шкаф (это единственное летальное оружие на данный момент у СБ)
- Приводим офис Дека к варианту РуПары
- Для СБ была добавлена кобура
- Чистка накаканого с прошлой обновы
Привычнее
Дифф бот
В игре
:cl:
add: Кибериада: У СБ появилось единственное летальное оружие - Уника у ГСБ
add: Кибериада: ГСБ добавлены боевые перчатки
add: Кибериада: Добавлена кобура для СБ
tweak: Кибериада: Офис детектива был приведен к виду с РуПары
/:cl:
> Feat: Cyberiad Brig update 2

- code/modules/security_levels/security_levels.dm
- modular_ss220/modular_ss220.dme
- modular_ss220/security_redalert_accesses/_security_redalert_accesses.dm
- modular_ss220/security_redalert_accesses/_security_redalert_accesses.dme
- modular_ss220/security_redalert_accesses/code/security_redalert_accesses.dm
Добавляет доступы СБ в красный код
Closes https://github.com/ss220club/Paradise-SS220/issues/285
Ориг PR: https://github.com/ss220-space/Paradise/pull/1207
-
-
В игре
:cl:
add: СБ добавлены доп. доступы в красный код
/:cl:
> Feat: Securtity additional accesses on red code

- _maps/map_files220/cyberiad/cyberiad.dmm
Починил доступы в инженерке.
Меньше дер.
DIFF бот
Нет
:cl:
fix: Гейтеры больше не могут попасть в инженерку через техи.
/:cl:
> Fix: Cyberiad Engie Accesses

- _maps/map_files220/cyberiad/cyberiad.dmm
Фикс неправильного положения машинерии в телепортной.
Фикс
Нет конечно
:cl:
fix: Фикс расположения машинерии в телепортерной.
/:cl:
> Fix: Teleporter Room (Cyberiad)

- _maps/map_files220/RandomRuins/LavaRuins/scp_facility.dmm
- _maps/map_files220/RandomRuins/SpaceRuins/convoy_ambush.dmm
- _maps/map_files220/RandomRuins/SpaceRuins/destroyed_infiltrator.dmm
- _maps/map_files220/RandomRuins/SpaceRuins/infected_ship.dmm
- _maps/map_files220/RandomRuins/SpaceRuins/mechtransport_new.dmm
- _maps/map_files220/RandomRuins/SpaceRuins/spacehotel.dmm
- _maps/map_files220/RandomRuins/SpaceRuins/transit_bar.dmm
- _maps/map_files220/RandomRuins/SpaceRuins/voxraiders_1.dmm
- _maps/map_files220/RandomRuins/SpaceRuins/whiteship.dmm
- _maps/map_files220/RandomZLevels/blackmarketpackers.dmm
- _maps/map_files220/RandomZLevels/gate_lizard.dmm
- _maps/map_files220/RandomZLevels/terrorspiders.dmm
- _maps/map_files220/RandomZLevels/wildwest.dmm
- _maps/map_files220/cyberiad/cyberiad.dmm
- _maps/map_files220/delta/delta.dmm
- _maps/map_files220/generic/Admin_Zone.dmm
- _maps/map_files220/generic/Lavaland.dmm
- _maps/map_files220/generic/centcomm.dmm
- modular_ss220/maps220/code/directions.dm
- tools/UpdatePaths/Scripts/ss220/vars_to_subtypes.txt
Чинит неправильно написанные направления у ламп.
Редактирует скрипт шоб такого не было.
не знаю
Заметных нет.
Просмотрел в редакторе и в коде правильность путей.
:cl:
fix: Починил направления ламп, никаких изменений заметных игроку.
/:cl:
> Fix: Lights direction

- modular_ss220/donor/code/client_procs.dm
:cl:
fix: Исправлен расчет уровня доната.
/:cl:
> Fix: donation amounts

- _maps/map_files220/cyberiad/cyberiad.dmm
- modular_ss220/bureaucracy/code/photocopier.dm
Факс больше не уничтожает карты.
Факс больше не уничтожает карты.
Факс больше не уничтожает карты.
:cl:
fix: Факс больше не уничтожает карты.
/:cl:
> Fix: Card Destroyer Fax

- code/game/jobs/job_exp.dm
- code/game/machinery/camera/camera.dm
- code/game/mecha/combat/honker.dm
- code/game/mecha/equipment/tools/medical_tools.dm
- code/game/mecha/mecha_topic.dm
- code/game/objects/items/blueprints.dm
- code/game/objects/items/devices/paicard.dm
- code/game/objects/items/weapons/manuals.dm
- code/modules/admin/outfits.dm
- code/modules/admin/permissionverbs/permissionedit.dm
- code/modules/admin/player_panel.dm
- code/modules/admin/secrets.dm
- code/modules/admin/topic.dm
- code/modules/admin/verbs/randomverbs.dm
- code/modules/arcade/prize_counter.dm
- code/modules/atmospherics/machinery/other/area_atmos_computer.dm
- code/modules/mob/living/silicon/pai/recruit.dm
- code/modules/mob/mob.dm
- code/modules/mob/new_player/new_player.dm
- code/modules/paperwork/paper.dm
- code/modules/paperwork/paper_bundle.dm
- code/modules/paperwork/photography.dm
- code/modules/pda/ai_pda.dm
- modular_ss220/title_screen/code/_title_screen_defines.dm
Кринж пиздец, ну а че делать
:cl:
fix: Кодировка в некоторых меню
/:cl:
> NON MODULAR CRINGE: utf8

- _maps/map_files220/delta/delta.dmm
Перенос Суда, офиса магистрата и перестройка АВДшной со старопары
Нада
На карте
Тесто было
🆑
add: Ремап суда, магистрата и АВД на дельте.
/🆑
> remap delta courtroom magistrate IAA office's

- code/modules/mob/mob_misc_procs.dm
Вернул заикание и спутанную речь.
СЪешь ещё 'ити'х' мя'гк'их Фр'ан'цуЗсшкИх БУлуК, да Выпей Чаю
Б-бл-лят-ть
:cl:
tweak: СЪешь ещё 'ити'х' мя'гк'их Фр'ан'цуЗсшкИх БУлуК, да Выпей Чаю
tweak: Б-бл-лят-ть
/:cl:
> Feat: Stutters and slurs speech

- modular_ss220/mobs/code/simple_animal/friendly/mouse.dm
Исправляет кастомные дескрипшены у мобов
хз
нету
не тестировал, если что - всё сваливайте на Пупса
:cl:
fix: Отсутствующие кастомное описание у мышей и их подтипов
/:cl:
> Fix: Mouse description

- modular_ss220/_modpacks.dm
- modular_ss220/administration/_administration.dm
- modular_ss220/administration/_administration.dme
- modular_ss220/administration/code/randomverbs.dm
- modular_ss220/modular_ss220.dme
Closes https://github.com/ss220club/Paradise-SS220/issues/300
- Добавляет гост оффер в контекстное меню для администраторов
Удобство админам
:cl:
add: Ghost Offer для администрации в контекстное меню
/:cl:
> Feat: Ghost offering

- _maps/map_files220/RandomZLevels/terrorspiders.dmm
Пауки больше не должны сбегать с зон содержания в гейте.
Да пиздец, пауки плодятся и сбегают.
Убрал венты у квины и сделал неломаемыми поддуры.
Нет, я уверен.
:cl:
fix: Пауки больше не должны сбегать с зон содержания в гейте.
/:cl:
> Fix: No Terror Escape

- _maps/map_files220/cyberiad/cyberiad.dmm
Офис детектив теперь полностью соответствует РуПаровскому, с улучшениями.
Элементарно стало лучше
+Вайб
В игре
:cl:
add: Кибериада: Улучшен офис детектива
/:cl:
> Feat: Cyberiad update detective's office, part 2

- _maps/map_files220/delta/delta.dmm
Добавил контроллер шлюзов, заменил холодильники вирусологии на холодильники с вирусами вирусологии
:)
в боте
ворк
:cl:
fix: Дельта: В вирусологии теперь работают шлюзы, холодильники с вирусами.
/:cl:
> Fix: Delta virology

- _maps/map_files220/RandomRuins/SpaceRuins/whiteship.dmm
- _maps/map_files220/cyberiad/cyberiad.dmm
- _maps/map_files220/delta/delta.dmm
Привел размеры доков медицинского корабля НТ к значениям самого корабля.
Теперь он летает.
На локалке ворк.
:cl:
fix: шаттл NT med теперь снова мобильный
/:cl:
> Fix: Whiteship destinations

- _maps/map_files220/delta/delta.dmm
заменил гиббер на кухне на food processor 
:)
на дифе
нет
:cl:
fix: на кухне Дельты вместо гиббера теперь стоит Food processor 
/:cl:
> Fix: Delta kitchen

- _maps/map_files220/generic/centcomm.dmm
- modular_ss220/maps220/_maps220.dme
- modular_ss220/maps220/code/admin.dm
added ATM, bag of cash, centcom stamp, mirror
Добавил немного QoL в офис на ЦК (деньги, зеркало, печать).
:cl:
tweak: небольшие изменения на ЦК
/:cl:
> feat: minor centcom changes

- modular_ss220/discord_link/code/discord.dm
> Fix: No discord linkage ruin

- _maps/map_files220/cyberiad/cyberiad.dmm
Заменяет все факсы глав на long range.
Closes #347
не знаю
В коде
Нет
:cl:
add: На Кибериаде, все факсы глав теперь могут отсылать сообщения на ЦК.
/:cl:
> Feat: Long range faxes (Cyberiad)

- modular_ss220/gateway/_gateway.dme
- modular_ss220/gateway/code/jobs.dm
:cl:
tweak: Исследователи снова доступны раундстартом
/:cl:
> Revert: explorer slots

- modular_ss220/aesthetics_sounds/code/closet.dm
- modular_ss220/closet_picklocking/_closet_picklocking.dm
- modular_ss220/closet_picklocking/_closet_picklocking.dme
- modular_ss220/closet_picklocking/code/closet_picklocking.dm
- modular_ss220/modular_ss220.dme
Closes https://github.com/ss220club/Paradise-SS220/issues/346
- Добавляет взлом шкафчиков и ящиков с РуПары.
- Было улучшено описание состояния взлома.
- Пофикшен баг при котором можно было взаимодействовать с ящиком внутри него.
- Инкапы больше не могут взаимодействовать с ящиком.
Запрос игроков, наконец то ящики можно вскрыть
Нет
:cl:
add: Взлом шкафчиков и ящиков с РуПары. Улучшено описание взломанного шкафчика
add: Добавлен звук lock/unlock для ящиков (забыл про них)
fix: Пофикшен баг при котором можно было взаимодействовать с ящиком внутри него
fix: Инкапы (в наручниках/в крите и т.д.) больше не могут взаимодействовать с ящиком
/:cl:
> Feat: Closet picklocking

- code/game/atoms_movable.dm
- code/game/objects/structures/stool_bed_chair_nest/wheelchair.dm
Правильно обновляет `glide_size` для коляски
Выглядит приятнее глазу
Покатался на каляске
:cl:
fix: мобы на калясках катаются плавно
/:cl:
> fix: fix glide size update for wheechairs

- modular_ss220/jukebox/code/jukebox.dm
Убрал проверку на преф dance machine
Понизил громкость жукбоксов
Увеличил слегка радиус музыки
:cl:
tweak: Jukebox (Диско-шар) теперь проигрывает музыку в радиусе 14 тайлов.
tweak: Слегка понизил максимальную громкость диско-шара, до 50 стандартных и 75 максимальных. А так же у музыкального автомата до 25 стандартных и максимальных.
tweak: Диско-шар теперь "перезаряжается" быстрее.
fix: Диско-шар теперь должен быть слышен всем. Отключать его звук через МИКШЕР. Опции - Открыть микшер
/:cl:
> Tweak: Jukebox tweaks

- code/modules/security_levels/security_levels.dm
Перевод оповещений кодов безопасности
Отсутствие кривой озвучки ТТСом английского текста
Не тестировал
:cl:
tweak: Перевод оповещений кодов безопасности
/:cl:
> Translation

- _maps/map_files220/cyberiad/cyberiad.dmm
ТЯП ЛЯП ХУЯК
- Добавляет статую Фемиды в зал суда
- Обновляет визуал суда
- Добавляет двойные аирлоки... местами, где они не будут забагованы...
Кайф ну
Немножко в игре, если что, пофикшу потом xdd
:cl:
add: Кибериада: Статуя Фемиды в зал суда
add: Добавлены новые двойные аирлоки, местами (где они не забагованы)
tweak: Обновлен визуал зала суда
/:cl:
> Feat: Cyberiad actualization, part 2

- _maps/map_files220/generic/centcomm.dmm
Просто открыл шлюзы подов на ЦК
Можно выйти с пода и послушать музыку.
:cl:
fix: Шлюзы подов на ЦК теперь открытые. Но админы могут вылететь в космос :Clueless:
/:cl:
> Fix: Locked Emergency pods airlocks (CentComm)

- modular_ss220/balance/code/species/nucleation.dm
- modular_ss220/food/code/drinks.dm
:cl:
tweak: Теперь разрешено брать нуклеаций как расу.
fix: Наверное, починил баги с пропадающей иконкой напитков.
/:cl:
> Fix: alcosprite

- _maps/map_files220/delta/delta.dmm
Оказывается я как-то перепутал местами аутлет и чут. Исправил недоразумение.
Мусор может катиться дальше
:cl:
fix: Дельта: Мусор теперь может уходить с карго, ну и доставка снова работает.
/:cl:
> Fix: Cargo Disposal

- _maps/map_files220/cyberiad/cyberiad.dmm
Починил зоны по карте.
Где-то nearstation
Где-то убрал космос
Где-то прикрыл техи
Мелочь короче
> Fix: Cyberiad Areas

- _maps/map_files220/generic/centcomm.dmm
Фиксит конвееры в карго.
Да, на ЦК, на Дельте, на Кибериаде.
:cl:
fix: Конвееры в карго теперь работают корректно.
/:cl:
> Fix: Cargo shuttle conveyor

- modular_ss220/maps220/code/floors.dm
Трава теперь не мешает шмалять в гейте Gate Lizard
Странный вопрос
Код
Да
:cl:
fix: Трава теперь не мешает стрелять в гейте Gate Lizard.
/:cl:
> Fix: Grass opacity fix

- modular_ss220/emotes/code/emote_verbs.dm
:cl:
add: Вернул некоторые эмоуты в меню
/:cl:
> Revert: Ruina

- _maps/map_files220/delta/delta.dmm
- Добавил главам факсы дальнего диапазона
- Добавил зиппо для глав.
лучше коммуникация глав и ЦК
в боте
ноуп
:cl:
add: Дельта: теперь у каждого главы есть личная зажигалка.
tweak: Дельта: у глав теперь нормальные факсы.
/:cl:
> Tweak: Delta Long-range faxes and zippo 

- code/datums/ai_law_sets.dm
Перевод законов ИИ
ТТС криво озвучивает латиницу
Никак:)
:cl:
add: Перевод законов ИИ
/:cl:
> feat: translate ai law sets

- _maps/map_files220/cyberiad/cyberiad.dmm
- _maps/map_files220/delta/delta.dmm
Офис КМа теперь больше похож на офис главы.
потому что КМ глава и ему нужен подобающий офис 
кномпочки нажимал
:cl:
add: Кибериада: В офис КМа добавлено устройство аутентификации
tweak: Дельта: Офис КМа теперь офис главы а не простого работяги.
/:cl:
> Tweak: Delta QM office

- _maps/map_files220/cyberiad/cyberiad.dmm
- _maps/map_files220/delta/delta.dmm
Убрал инициализацию у патчей в медах.
В меде дельты сделал небольшую перестановку на складе.
Патча работают?
Ну да.
:cl:
tweak: Дельта: Небольшая перестановка на складе в меде.
fix: Раундстартовые патчи на столах в меде, теперь не пустые.
/:cl:
> Fix: Patch fix

- _maps/map_files220/delta/delta.dmm
- Добавил в бриг холстеры, рации СБ.
- Перенес сек вендомат.
- К хосу в ящик добавлены комбат перчатки и холстер, в кабинет мегафон.
СБ немножко попроще щиткурить
В боте
чуть чуть
:cl:
tweak: Дельта: в бриг добавлены холстеры. Хосу добавил комбаты, мегафон и холстер.
/:cl:
> Tweak: Delta brig

- _maps/map_files220/delta/delta.dmm
Немного изменена комната экспедиции под новые возможности.
Гейтеры будут меньше манчить 
Нет
:cl:
add: Дельта: на мостике есть маяк для телепорта.
tweak: Дельта: комната экспедиции теперь с шкафами исследователей.
/:cl:
> Tweak: Delta expedition room

- _maps/map_files220/cyberiad/cyberiad.dmm
Пока Уника
?
Она пропала
Нет.
:cl:
del: Неизвестный агент синдиката украл у ГСБ его Унику на Кибериаде, как ему это удалось - нам не ясно, поиски вора продолжаются, однако шансы на его поимку крайне малы... ГСБ уволен кстати.
/:cl:
> Del: HoS Mateba

- _maps/map_files220/cyberiad/cyberiad.dmm
Заменил пару помп что бы инженеры не умирали по глупости.
Меньше трупов инженеров.
В боте.
Там тестировать нечего особо
:cl:
fix: Кибериада: Больше нет проблем с слишком высоким давлением в вентиляции.
/:cl:
> Fix: Cyberiad overhigh pressure

- modular_ss220/balance/_balance.dm
- modular_ss220/balance/_balance.dme
- modular_ss220/balance/code/jobs/warden.dm
Добавляет Вардену доступ к аккаунту СБ
Варден заведующий бригом, значит и оружейки
Заказали, подтвердили
:cl:
add: Добавлян Вардену доступ к аккаунту СБ
/:cl:
> warden cargo access

- config/example/config.toml
- modular_ss220/_misc/_misc.dm
- modular_ss220/_misc/_misc.dme
- modular_ss220/_misc/code/ss220_general_config.dm
- modular_ss220/discord_link/code/discord.dm
Добавляет галочку в конфиге на проверку привязки дискорда
Хост не забудь добавить обновить конфиг
Локалка с БД больше не требует невозможного
Тыкнул так, тыкнул сяк
:cl:
tweak: Добавлена галочка в конфиге на проверку привязки дискорда. По умолчанию - не требуется.
/:cl:
> discord verification on non prod server pepelaugh

- _maps/map_files220/cyberiad/cyberiad.dmm
Исправлена проблема с посылками/мусором от церкви и библиотеки.
Мусор в церкви - плохо.
В боте
Проверил работу труб.
:cl:
fix: Кибериада: Мусор и посылки церкви/ботаники вновь нормально отправляются.
/:cl:
> Fix: Cyberiad waste disposal system

- code/modules/client/preference/link_processing.dm
- code/modules/mob/new_player/new_player.dm
- modular_ss220/_modpacks.dm
- modular_ss220/discord_link/code/discord.dm
- modular_ss220/text_to_speech/code/hear.dm
- modular_ss220/text_to_speech/code/providers/silero.dm
- modular_ss220/text_to_speech/code/tts_preferences.dm
Тут всякие мелочи, которые надо бы пофиксить, но мне все лень
> Tweak: Annoying-stuff

- _maps/map_files220/cyberiad/cyberiad.dmm
Вернул в вирусологию настенный раздатчик... питания для вирусов?
:cl:
fix: Кибериада: Вернул в вирусологию настенный раздатчик... питания для вирусов?
/:cl:
> FIx: Virusfood (Cyberiad)

- modular_ss220/credits/code/SScredits.dm
:cl:
fix: Финальная починка титров
/:cl:
> fix: rank check

- modular_ss220/objects/code/closets.dm
:cl:
add: Добавлены запасные патроны для анаконды в ящик гсб
/:cl:
> Add: anaconda loaders

- modular_ss220/discord_link/code/discord.dm
Создает лесенку из ифов, чтоб работала привязка нормально
> fix: ds link

- _maps/map_files220/cyberiad/cyberiad.dmm
Удалил освещение в зоне содержания теслы, авось поможет от поцелуя теслы сквозь стену.
Fixes #477 
Меньше ударов теслой?
Trust me brooo
Trust me brooo
:cl:
fix: Кибериада: Ещё одна попытка починить поцелуи теслы сквозь стену, убрал освещение в зоне содержания. Должно помочь, если нет то... увы.
/:cl:
> Fix: Tesla hits through the wall

- modular_ss220/keybindings/code/human_keybinds.dm
Паррировать -> Парировать
:cl:
spellcheck: Паррировать -> Парировать
/:cl:
> Translation fix

- modular_ss220/smart_equip_targeted/code/smart_equip_targeted.dm
Фиксит у МОДов хоткеи на фаст-эквип
Это ведь тоже сумка
trust me bro
:cl:
fix: Фаст-эквип теперь работает и с МОДами
/:cl:
> fix modcontrol fast equip

- _maps/map_files220/delta/delta.dmm
Подключил мусорку в робо, которая по какой то причине была отключена, так же добавил туда доставку.
Сломанные борги отправляются в помойку
ноуп
Нет
:cl:
fix: Дельта: теперь в робо работает мусорка. Так же появилась доставка в робо.
/:cl:
> Fix: Delta robotics waste disposal system 

- _maps/map_files220/RandomZLevels/caves.dmm
Фикс активных турфов в гейте caves. 
Меньше нагрузка
Локалка
:cl:
fix: Убрал лишние тайлы с воздухом в гейте "Caves". 
/:cl:
> Fix: Caves active turf

- modular_ss220/modular_ss220.dme
- modular_ss220/world_view_bigger/_world_view_bigger.dm
- modular_ss220/world_view_bigger/_world_view_bigger.dme
- modular_ss220/world_view_bigger/code/world_view_bigger.dm
Увеличивает world.view с 15х15 до 19х19. Вроде бы не ломает параллакс, сей работает по горизонтали как нужно, по вертикали вряд ли исправить (слышишь дальше, чем видишь, на 2 турфа)
Если видишь, как кто-то говорит, стоит услышать их
сей-сей, полетел по космосу, вроде работает
:cl:
tweak: Увеличение world.view с 15x15 до 19x19, что позволит слышать на вайдскрине людей на границе экрана.
/:cl:
> Increases world.view from 15x15 to 19x19

- modular_ss220/mobs/code/simple_animal/overrides.dm
- modular_ss220/text_to_speech/code/base_seeds/mobs/_base.dm
Заменяет дефолтный ТТС голос на среднестатистический мужской
Больше никаких специфичных полуписклявых кляйнеров кому попало
:cl:
tweak: Изменил дефолтный ТТС голос на более нейтральный мужской
/:cl:
> Tweak: Default TTS sound is now more "neutral"

- modular_ss220/clothing/code/mask.dm
Чиним вордс реплаке
Фикс Вордс реплаке
:cl:
fix: починил вордс реплаке
/:cl:
> fix: words replace

- _maps/map_files220/cyberiad/cyberiad.dmm
Я долбоёб
Убрал когда-то случайно поставленный кейс с пчёлами с коробки
Нет пчёл
Их нет.
Просто убил пчёл
:cl:
fix: НТ вызвало дезинсектора на Кибериаду, больше пчёлы вас не побеспокоят, откуда они вообще появились... загадка...
/:cl:
> Fix: Remove BeeCase from (Cyberiad)

- _maps/map_files220/RandomZLevels/caves.dmm
- _maps/map_files220/cyberiad/cyberiad.dmm
- _maps/map_files220/delta/delta.dmm
- _maps/map_files220/generic/Lavaland.dmm
Исправление путей после мержа с оффами
:cl:
/:cl:
> Fix: Path fixes

- _maps/map_files220/cyberiad/cyberiad.dmm
- _maps/map_files220/delta/delta.dmm
- _maps/map_files220/generic/Lavaland.dmm
Пофиксил трансит трубы, почистил аутпост
Протестировал
:cl:
fix: Фиксы карт после мержа с оффами
/:cl:
> Fix: Transit tubes, Lavaland outpost "cleanup"

- _maps/map_files220/generic/Lavaland.dmm
Дочистил объекты, переложил местами пол, исправил местами трубы
Фикс оффовского говна
Нет
Нет
:cl:
tweak: Стандартизация и дочистка аванпоста Лаваленда
/:cl:
> Tweak: Lavaland outpost cleanup & standardization

- modular_ss220/aesthetics_sounds/_aesthetics_sounds.dme
- modular_ss220/aesthetics_sounds/code/alerts.dm
Фух, оказалось нужно было заменить ток одну
Closes https://github.com/ss220club/Paradise-SS220/issues/538
Протестил в игре
:cl:
tweak: Вернул замену звука Эпсилон после мержа с оффами
/:cl:
> Tweak: Epsilon sound re-add

- modular_ss220/mecha_skins/code/paintkit_install.dm
Исправляет баг
Баги плохо
Потыкал картой в игре - работает
:cl:
fix: Пофиксил взаимодействие с мехами
/:cl:
> Fix: Mecha interaction

- modular_ss220/balance/_balance.dme
- modular_ss220/balance/code/items/projectiles.dm
:cl:
add: Чтобы попасть по лежачей цели оружием дальнего боя, теперь нужно кликать по кукле лежачей цели.
/:cl:
> [BALANCE] Prone Targetting

- code/datums/ai_law_sets.dm
Перевод законов ИИ и синтетиков
Больше игроков (в теории) будут понимать законы синтетикой
:cl:
tweak: Перевод законов ИИ, который даже не отобразится в вашем чейнджлоге
/:cl:
> Translate: AI laws

- .github/workflows/auto_translate.yml
- .github/workflows/translate_branch_update.yml
> prayge: another translation fix

- _maps/map_files220/delta/delta.dmm
Переделана библиотека дельты.
Ничего шибко нового добавлено не было.
Чуть чуть лучше по визуалу.
Да тестировать нечего особо.
:cl:
tweak: Дельта: переделана библиотека.
/:cl:
> Remap: Delta library

- _maps/map_files220/delta/delta.dmm
Добавил ГСБ его штамп.
Нет нужды мучать админов
Нет
:cl:
fix: Дельта: у ГСБ снова есть печать.
/:cl:
> Fix: Delta HoS stamp

- _maps/map_files220/cyberiad/cyberiad.dmm
- _maps/map_files220/delta/delta.dmm
Добавил чутка зарядок для боргов. 
На дельту 2 - в бриг и ассистентскую.
На коробку 3 - две в мед и одну в бриг.
Боргам дано больше времени робастить.
В боте
Нет
:cl:
add: Дельта: 2 новых зарядника для боргов. Один в бриге, второй в ассистентской.
add: Кибериада: 3 новых зарядника для боргов. Два в меде, один в бриге.
/:cl:
> Fix: More cyborg rechargers

- modular_ss220/objects/code/beretta.dm
Небольшой фикс кода.
Nanofixes, son. 
Здесь могло быть изображение кода.
Тест прошел на локалке и вполне успешно. 
:cl:
fix: Починил крафт патронов в протолате рнд. Уменьшил количество коробок патронов в ящике карго. Сделал перезарядку магазинов как у магазинов ВТшки.
/:cl:
> FIX: Another code fix for Beretta M9

- code/datums/revision.dm
- code/modules/mob/dead/observer/observer_base.dm
- code/modules/mob/mob.dm
- code/modules/mob/new_player/new_player.dm
Перевод статуса и пары всплывающих окон...
Чуть более понятно некоторые вещи, ну и тест.
Ну типа
:cl:
experiment: Экспериментальный перевод статус бара
/:cl:
> Translate: Status bar

- code/modules/mob/new_player/new_player.dm
https://github.com/ss220club/Paradise-SS220/pull/522
> Translate: Test 2

- code/modules/mob/new_player/new_player.dm
Добавляет частичный перевод
:cl:
add: Частичный перевод в главном меню
/:cl:
> Тестовый перевод 2

- tgui/packages/tgui/components/ByondUi.js
- tgui/packages/tgui/components/NanoMap.js
- tgui/packages/tgui/interfaces/AgentCard.js
- tgui/packages/tgui/interfaces/CameraConsole220.js
- tgui/packages/tgui/interfaces/EmotePanel.js
- tgui/packages/tgui/interfaces/Jukebox.js
- tgui/packages/tgui/interfaces/ModpacksList.js
Обновляет JS файлы под новый pretty. Ничего не меняет, кроме как красоты в тексте. Автоматически создан с tgui.build
> TGUI pretty update

- .tgs.yml
> Bump TGS Byond version

- .github/workflows/auto_translate.yml
- .github/workflows/translate_branch_update.yml
- tools/translator/converter.py
github action:
- fix
converter.py:
- filter allowed file paths
- addend new translations to old
Don't trust me
:cl:
fix: cкрипт перевода и github actions
/:cl:
> Fix translation script and json v3

- code/game/verbs/ooc.dm
:cl:
fix: фикс ветки ифов
/:cl:
> fix: ooc-color

- tools/translator/ss220replace.json
Ручная синхронизация перевода из https://github.com/ss220club/Paradise-SS220/pull/624
:cl:
fix: Ручная синхронизация json с переводом
/:cl:
> Ручная синхронизация json

- .github/workflows/auto_translate.yml
Фикс github action обновляющего файл с переводами
:cl:
fix: Фикс github action обновляющего файл с переводами
/:cl:
> Fix auto_translate.yml

- modular_ss220/text_to_speech/code/seeds/silero.dm
Пересмотр требуемых уровней подписки для голосов Silero.
Я не инициатор, а исполнитель
:cl:
tweak: Изменены требуемые уровни подписки бусти для голосов Silero
/:cl:
> tweak: TTS required donators levels

- _maps/map_files220/cyberiad/cyberiad.dmm
- _maps/map_files220/delta/delta.dmm
По запросу баунти переделал немного турбину на Дельте и Кибериаде. 
Починил работу самой турбины на Дельте. 
Сделал отдельные трубы для смеси в турбину на Дельте и Кибериаде.
Немного переделал атмос Дельты и Кибериады.
Потому что мне заплатили
:cl:
tweak: На Дельте и Кибериаде доработана турбина. Так же был немного изменен атмос.
/:cl:
> Tweak: better turbine

- modular_ss220/clothing/code/garment_bag.dm
- modular_ss220/clothing/code/gloves.dm
- modular_ss220/modular_ss220.dme
- modular_ss220/objects/code/closets.dm
- modular_ss220/objects/code/miscellaneous.dm
- modular_ss220/objects/code/weapons.dm
- modular_ss220/prime_only/_prime.dm
- modular_ss220/prime_only/_prime.dme
- modular_ss220/prime_only/code/anakonda.dm
Убирает анаконду, спидлоадеры к ней и комбат перчатки у ХоСа с мейна.
Вместо неё теперь пончик.
Никакой имбы на мейне
:cl:
tweak: ГСБ продал свою Анаконду за Анаконду поменьше...
/:cl:
> Feat: Prime Only modpack

- modular_ss220/balance/code/items/projectiles.dm
Добавляет прожектайлам проверку, что лежачий типчик живой.
Убирает абуз
:cl:
fix: Стрельба не в хелпе теперь проверяет в сознании ли лежачая цель
/:cl:
> added check if the target is concious

- _maps/map_files220/MetaStation/MetaStation.dmm
Поменял у глав обычные факсы на крутые факсы.
Так же немного увеличил офис КМа.
На лоупопе прямая связь с ЦК это гуд.
В боте.
Ноуп
:cl:
tweak: Цера: у глав заменены факсы. Офис КМа чуть больше.
/:cl:
> Tweak: Meta long-range faxes 

- modular_ss220/queue/code/new_player_procs.dm
фикс рантайма
:cl:
fix: Теперь удаление сикея из вайтлиста очереди совершает сабсистема
/:cl:
> fix: reserve slot

- modular_ss220/queue/code/new_player_procs.dm
Убираем var/ из аргумента прока
> fix: linter

- code/modules/client/preference/preferences.dm
Частичный перевод окна с настройками персонажа
:cl:
add: Частичный перевод окна с настройками персонажа
/:cl:
> Player settings translation

- tools/changelog/check_changelog.py
Подгоняем ruamel.yaml под актуальную версию
:cl:
fix: Устаревшое наименование аргумента
/:cl:
> fix: constructor argument renamed

- _maps/map_files220/delta/delta.dmm
> Fix: Syndie shuttle (Delta)

- code/modules/client/preference/preferences.dm
Исправляет перевод
:cl:
tweak: Правка перевода в преференсах
/:cl:
> Tweak: Preferences translation fix

- _maps/map_files220/generic/centcomm.dmm
- modular_ss220/unique_objects/code/unique_objects.dm
По запросу Муни выносим статую на синди-ЦК и переименовываем
Меняем статуи, готовим для будущего потенциального апдейта с ними.
:cl:
tweak: Статуя муни вынесена на синдицк в лес
/:cl:
> [MAP] Statue Update 1

- .github/workflows/auto_translate.yml
Фикс github action `Add new translation`
:cl:
fix: Фикс github action `Add new translation`
/:cl:
> Fix auto translate

- tools/github-actions/nanomap-renderer-invoker.sh
Должно починить рендер наномап
> Fix: NanoMap Render

- tools/github-actions/nanomap-renderer-invoker.sh
Теперь точно чинит рендер наномап
> Fix for fix: NanoMap Render

- modular_ss220/mobs/code/pet_carrier.dm
- modular_ss220/objects/code/officetoys.dm
- modular_ss220/objects/code/papershredder.dm
- modular_ss220/objects/code/platform.dm
Переводит вербы с введеных нами предметов на Альт-клики
Догоняем оффов Clueless
Не появляется Objects с пролагами в вербах
:cl:
tweak: Убраны вербы и переведены в Альт-клики у: paper shredder, platform, office toy, pet carrier
/:cl:
> Verbs clean up

- modular_ss220/donor/code/client_procs.dm
- modular_ss220/loadout/code/donor.dm
Чиним выявленные неисправности донтаного лодаута
:cl:
fix: Цена аптечки соответсвует цене в рекламе доната
fix: Теперь донатный тулбелт реально с инструментами без мультитула
fix: Теперь люди без донатного тира тоже ограничиваются слотами
/:cl:
> fix: donor

- modular_ss220/donor/code/client_procs.dm
Пересмотр формулы выдачи новых слотов персонажа
:cl:
fix: Теперь количество доступных слотов для персонажа соответствует рекламе подписки
/:cl:
> fix: save slots to new formula

- modular_ss220/whitelist/code/whitelist.dm
Теперь когда игроки заходят на прайм без проходки - их уведомляет об этом
:cl:
tweak: Теперь когда игроки заходят на прайм без проходки - их уведомляет об этом
/:cl:
> Tweak: not on the whitelist ban reason

- modular_ss220/food/code/food.dm
Варенные пельмени становятся вареными и так далее
действительно
скомпилировал, запустил
:cl:
spellcheck: неверное нн в нескольких предметах пищи было исправлено на верный вариант
/:cl:
> Исправляет "НН" где это неправильно в добавленных предметах еды

- _maps/map_files220/cyberiad/cyberiad.dmm
Исправляет мой проёб в id
Нет бага
Протестил
:cl:
fix: Кибериада: исправление конвейерной ленты в переработчике мусора
/:cl:
> Fix: Cyberiad recycler conveyor belt

- modular_ss220/discord_link/code/discord.dm
Упрощает процедуру привязки к дискорду, до простого "копировать-вставить"
Меньше вопросов по привязке
Да
:cl:
tweak: Привязка дискорда упрощена, теперь достаточно всего-лишь копировать и вставить.
/:cl:
> Tweak: Easier discord link

- modular_ss220/queue/code/new_player_procs.dm
Донатеры, начиная от третьего тира, игнорируют очередь, запрос Муниверса
:cl:
tweak: Донатеры, начиная от третьего тира, игнорируют очередь, запрос Муниверса
/:cl:
> tweak: donators with at least 3 tier ignore the queue

- .github/workflows/ci_translate.yml
- tools/translator/converter.py
Переработан converter.py
Добавлена ci проверка на перевод
:cl:
add: Добавлена ci проверка на перевод
fix: Переработан converter.py
/:cl:
> Update translate tools and add ci

- tools/translator/ss220replace.json
Синхронизируем json с актуальной веткой перевода
:cl:
fix: Синхронизируем json с актуальной веткой перевода
/:cl:
> Синхронизация json с актуальной веткой перевода

- modular_ss220/text_to_speech/code/seeds/silero.dm
Исправляем ошибочно выявленные гендеры (Еллис из L4D был женским голосом)
:cl:
fix: Чиним неправильно определенные гендеры голосов
/:cl:
> fix: silero genders

- modular_ss220/_modpacks.dm
Админка на локалке снова выдаётся автоматически.
Из минусов - не будет модульных вербов на локалке, да и похуй, он всего 1 пока что.
Не нужно запускать ебучий бйонд ради тестика.
Их нет.
Только на локалке, в теории не должно повлиять на сервер.
:cl:
fix: Починил выдачу авто-админки на локалке. Не должно быть никакого эффекта на серверах.
/:cl:
> Fix: LocalHost auto-admin

- modular_ss220/_misc/code/discord_configuration.dm
:cl:
fix: Чиним прок считывания конфига дискорда
/:cl:
> fix: add . = ..()

- modular_ss220/clothing/code/suits.dm
Убирает точку в названии предмета
:cl:
spellcheck: Убрана точка в названии жакета Вай
/:cl:
> Tweak: Vi jacket spellcheck

- modular_ss220/whitelist/code/whitelist.dm
Изменяет причину кика при отсутствии доступа на Прайм
Меня больше не корежит, игрокам не придется обращаться в #help
> Tweak: Change no whitelist reason

- _maps/map_files220/MetaStation/MetaStation.dmm
- _maps/map_files220/cyberiad/cyberiad.dmm
Добавил EFTPOS в бриг.
Косяки исправляем
ме
Нет
:cl:
fix: Добавлены EFTOPS в бриг. 
/:cl:
> Fix: Delta brig consoles and EFTOPS for security 

- _maps/map_files220/delta/delta.dmm
Исправление мусорки. Она не работала. Приемник мусора был не тот, и сортировщик отправляет мусор на круг, а посылки в переработку.
Теперь она работает
локальный сервер
:cl:
fix: Дельта: Исправлен приемник мусора и мусорные трубы
/:cl:
> HOTFIX: Delta/Cargo/disposal

- modular_ss220/maps220/_maps220.dme
- modular_ss220/maps220/code/Station/cerestation.dm
Фаррагус больше нельзя выбрать в голосовании
Нахуй хуёвые карты
Она пропала
Нет
:cl:
del: За Фаррагус больше нельзя проголосовать при выборе карты
/:cl:
> Del: CereStation no more voteable

- modular_ss220/_defines220/_defines220.dme
- modular_ss220/_defines220/code/donor.dm
- modular_ss220/donor/code/client_procs.dm
- modular_ss220/text_to_speech/code/tts_preferences.dm
Добавляем новые тиры для работников проекта.
- Большой работяга дает доступ ко всем голосам, имеет 10 слотов персонажа и 9 лодаут очков.
- Маленькйи работяга дает доступ голосам 1 тира, имеет 7 слотов персонажа и 5 лодаут очков
:cl:
tweak: Пересмотрены админ тиры, теперь у работников проекта отдельный тир который лучше чем тот что был до нововведения
/:cl:
> tweak: new-tiers-for-staff

- _maps/map_files220/MetaStation/MetaStation.dmm
- _maps/map_files220/generic/Lavaland.dmm
Фикс линтера карт (оно не уберет крестики, просто меньше ошибок)
> Fix: CI errors with access helpers

- modular_ss220/whitelist/code/whitelist.dm
Добавляем больше информации для проверки вайтлиста
:cl:
tweak: Уточняем что доступ на прайме можно получить с помощью второго тира бусти
/:cl:
> tweak: new message for isBanned proc

- modular_ss220/objects/_objects.dme
- modular_ss220/objects/code/musician.dm
Смена инструмента у обычного пианино с кошмарного, дефолтного "piano" на "Crisis Grand Piano One"
У гитары на "Crisis Steel String Guitar"
У трубы на "Crisis Trumpet"
У тромбона на "Crisis Trombone"
В баре будут реже вытекать уши от "музыканта"
https://github.com/ss220club/Paradise-SS220/assets/69762909/37b258a0-8c5a-488f-94f4-09a89882a8fe
Trust me brooo
:cl:
tweak: Пианино в баре теперь не заставляет ваши уши вытекать от одной ноты, так как теперь там "Crisis Grand Piano One". Тоже самое у гитары, трубы и тромбона
/:cl:
> Better Instruments sounds

- modular_ss220/text_to_speech/code/tts_seed.dm
Откатывает перенос выбора голоса на ТГУИ лист, работает не стабильно
Фиксит синий экран при выборе голоса ОБР
Нет
Trust me broo
:cl:
fix: Фикс синего/белого экрана при выборе голоса ОБР
/:cl:
> Revert: TTS voice choice list

- modular_ss220/mobs/code/pet_carrier.dm
- modular_ss220/mobs/code/simple_animal/pets/security_dogs.dm
- Теперь с собаки детектива можно снять ошейник
- Теперь в переноску можно поместить только pet симплов (не лучший фикс, но это лучше чем таскать с собой оперативника синдиката или демона в переноске, тут все равно нужен рефактор)
Меньше багов
:cl:
fix: В переноску больше нельзя засунуть демонов, ревенантов, оперативников... Синдиката?...
fix: Теперь можно снять ошейник с пса детектива
/:cl:
> Fix: Detective dog collar retrieve & pet carriers mob specify

- _maps/map_files220/cyberiad/cyberiad.dmm
Поставил скрабберы и венты в коридор РнД, их там не было, лол.
Не знаю
Нет Jokerge
:cl:
fix: Cyberiad: Возвращены скрабберы и венты в коридор РнД
/:cl:
> Fix: R&D hallway vents and scrubbers 

- interface/skin.dmf
- modular_ss220/aesthetics/skin/code/darkmode.dm
Небольшие твики скина, в числе которых:
Смена сглаживания на Nearest Neighboor
Смена шрифта на MS Serif (Италик и мелкий всё так же Small Fonts)
Покраска и лёгкий сдвиг кнопки Fullscreen
Допил скина, чётче картинка (благо новые полы позволяют) и чуть лучше шрифт в рунчате (привет буква Ё)
Мне лень
Да
:cl:
tweak: Сглаживание по-умолчанию теперь точно изменено на "По соседним пикселям"
tweak: Покрашена кнопка Fullscreen (пилим бюджет KEKW)
fix: В рунчате, большая буква "Ё" теперь отображается корректно, шрифт рунчата был изменён на MS Serif
/:cl:
> Skin Tweaks

- tools/tgs_scripts/PreCompileSS220.sh
:cl:
add: Что-то добавил
del: Что-то удалил
tweak: Поменял что-то по мелочи
fix: Что-то починил
wip: Какие-либо наработки в процессе
soundadd: Добавил новый звук
sounddel: Удалил старый звук
imageadd: Добавил новую картинку
imagedel: Удалил старую картинку
spellcheck: Исправил опечатку
experiment: Добавил эксперементальную функцию
/:cl:
> added: PreCompile for SS220.sh

- modular_ss220/text_to_speech/code/_defines.dm
- modular_ss220/text_to_speech/code/seeds/silero.dm
Делаем новые голоса Силеро бесплатными
:cl:
tweak: Новые голоса Силеро теперь доступны без подписки
/:cl:
> tweak: make new silero voices free

- modular_ss220/text_to_speech/code/seeds/silero.dm
Делаем недавно добавленные голоса из балдурс гейта бесплатными
:cl:
tweak: Голоса из БГ3 не требует подписки
/:cl:
> tweak: make BG3 voices free

- modular_ss220/text_to_speech/code/seeds/silero.dm
Обнаружена еще одна коллизия имен, император из скайрима и из бг 3
:cl:
fix: Починил за собой голос императора из БГ3
/:cl:
> fix: emperor name collision

- code/controllers/master.dm
- code/controllers/subsystem/non_firing/SSmapping.dm
Пробуем-пробуем-пробуем и ещё раз пробуем...
Заебали тесты падать
> Trying to fix falling tests

- code/game/objects/effects/decals/cleanable.dm
- code/modules/clothing/clothing.dm
- code/modules/clothing/shoes/magboots.dm
- code/modules/mob/living/carbon/human/human_movement.dm
Подсасываем раз конфликтов нет
:cl:
/:cl:
> merge upstream

- _maps/map_files220/cyberiad/cyberiad.dmm
Вернул пару труб в инженерку
Дышать вредно
Нет конечно
:cl:
fix: Вернул скрученные трубы в инженерку Кибериады
/:cl:
> Fix: [Cyberiad] Engie pipe

- modular_ss220/loadout/code/donor.dm
Добавляет жакет из Драйва в донорские предметы
Да не умер он в конце мёржа
Потом. Меня торопят.
Протестировано
:cl:
add: Добавлен предмет "Drive jacket" в лодаут Donor
/:cl:
> Add: Drive jacket in donor lodaut

- modular_ss220/credits/code/SScredits.dm
- modular_ss220/credits/code/credits.dm
- modular_ss220/credits/code/halloween_credits.dm
> refactor: credits

- modular_ss220/text_to_speech/code/_defines.dm
- modular_ss220/text_to_speech/code/seeds/silero.dm
Добавляем новые голоса от Силеро
:cl:
add: Добавлено 6 голосов из сериала "Слово Пацана"
/:cl:
> add: tts new voices

- modular_ss220/text_to_speech/code/seeds/silero.dm
Убрал запрещенные символы из названий голосов, судя по всему раньше из-за этого не применялся эффект рации и боргов на некоторые голоса
> fix: names in tts seeds

- modular_ss220/food/code/food.dm
- Исправляет рецепт вульпиксов
- Исправляет ошибку в названии еды
Нет бага
:cl:
fix: Исправлен рецепт вульпиксов
spellcheck: Исправлена опечатка "вульпыксы" -> "вульпиксы"
/:cl:
> Fix: Vulpix recipes & spellcheck

- _maps/map_files220/RandomZLevels/caves.dmm
Убираю остатки активных турфов.
ЭТОТ РАЗ ТОЧНО ПОСЛЕДНИЙ
Меньше нагрузки
Работает
:cl:
fix: Из гейта Caves убраны последние тайлы с активным атмосом. Честно-честно.
/:cl:
> Fix: Cave active turfs

- README.md
Обновил оставшиеся ссылки в README, теперь картинки с нашей инфой
> Update CI links in README

- modular_ss220/food/code/food.dm
Чиним рецепт вульпиксов
нет бага
.|.
.|.
:cl:
fix: Ярый любитель вульпочки под соусом сообщил что вульпиксы не починены, и я их починил еще раз, что бы мальчик был доволен 🥺
/:cl:
> Fix: Vulpix recipes... AGAIN

- modular_ss220/text_to_speech/_tts.dme
- modular_ss220/text_to_speech/code/tts_megaphone.dm
Чинит ТТС у мегафоне, спустя столько времени...
ПОТОМУ ЧТО!!!
показывает звук*
Нет возможности (На плечах legendaxe)
:cl:
fix: ТТС у мегафона теперь работает
/:cl:
> fix: Megaphone TTS

- _maps/map_files220/delta/delta.dmm
Добавил боксёрские перчатки на дельту
Убрал поломанные беговые дорожки, они просто не работают как надо, не знаю как давно они сломаны, но идёт этот кринж нахер
Можно боксировать
Ага
:cl:
add: Дельта, в качалке появился ящик с боксёрскими перчатками и масками
/:cl:
> Delta: Boxing gloves

- _maps/map_files220/cyberiad/cyberiad.dmm
Жалеем несчастного вирусолога, добавив ему пачку интеркомов в его берлогу. Пусть же при отключенных телекомах доложит всем о своем заточении или успехах в открытии ~~разрушающих мозг~~ полезных вирусов.
Вирусолог жив и даже почти не плачет.
Интеркомы на пикче выделены нежно-розовым цветом.
Работает.
:cl: Maxiemar
tweak: Вирусология Кибериады теперь оснащена интеркомами.
/:cl:
> Please save Virologist aka Ne Zvoni Suda Bolshe

- _maps/map_files220/MetaStation/MetaStation.dmm
- _maps/map_files220/cyberiad/cyberiad.dmm
- _maps/map_files220/delta/delta.dmm
- _maps/map_files220/generic/centcomm.dmm
- modular_ss220/balance/_balance.dme
- modular_ss220/balance/code/items/storage/surgical_tray.dm
Заменяем хирургические сумки на прикольные подносы. В апстриме с ними идут берн и травма киты, это вырезаем, наверное.
Реализм.
Коробка, остальное я уже закрыл, соре.
Я п(р)оверил.
:cl: Maxiemar
tweak: Хирургические сумки в операционных заменены на хирургические подносы. Стерильно 👍
/:cl:
> Surgical Trays

- _build_dependencies.sh
- code/modules/food_and_drinks/food_base.dm
- tools/UpdatePaths/Scripts/23063_patch_pill.txt
- tools/UpdatePaths/Scripts/23379_food_containers.txt
- tools/requirements.txt
:cl:
add: Мержим оффов
fix: Исправлен баг с слишком большой едой, (Пончик не помещался в коробку для пончиков)
/:cl:
> merge upstream 24.01.2024

- modular_ss220/credits/code/SScredits.dm
По непонятной мне причине сразу после коммита рефактора титров где я починил титры, фикс пропал в коммите с новогодними титрами, похоже произошел провтык с ветками.
:cl:
fix: починил призрачные титры после "пропуска синематика"
/:cl:
> fix: clear_credits

- modular_ss220/text_to_speech/code/tts_seed.dm
Перевод имени вёрба synth_change_voice
> tweak: translate `synth_change_voice` verb

- modular_ss220/clothing/code/suits.dm
- modular_ss220/jukebox/code/jukebox.dm
- modular_ss220/loadout/code/donor.dm
Добавил курткам Саундхэнд карманы
Добавил Куртки с тэгом в лоадаут за 2 поинта
Добавил в карго фанатские куртки Саундхэнд и барабан в big band
Потому что так и задумывалось
мэ
Зашел, проверил - ворк
:cl:
add: В лоадауте теперь есть куртки Саундхэнд, стоят 2 очка.
add: В карго теперь можно заказать фанатские куртки Саундхэнд и красный барабан в наборе Big Band 
tweak: В куртках Саундхэнд теперь есть карманы.
tweak: Теперь куртка Саундхэнд без тега - просто фанатская.
/:cl:
> Add: Саундхэд теперь в доноре и карго

- modular_ss220/text_to_speech/code/tts_seed.dm
- modular_ss220/text_to_speech/code/tts_subsystem.dm
Reverts ss220club/Paradise-SS220#963
> Revert "fix: make choosing voice by borg possible again"

- interface/skin.dmf
Изменяет кнопки, переводя их в инглиш и немного корректируя (так как слетело после мержа TGUIv4)
> Tweak: Skin dmf

- modular_ss220/text_to_speech/code/seeds/silero.dm
Потенциальный фикс ошибки No such file or directory и работы этих же голосов (если с ними есть проблемы)
:cl:
fix: Потенциальный фикс некоторых голосов, а также их кэширования
/:cl:
> Fix: TTS no such file or directory

- _maps/map_files220/delta/delta.dmm
Смотри название ПРа
Смотри первое слово ПРа
Смотри предпоследнее слово названия ПРа, и поменяй буквы местами
> Fix some pipes on delta

- modular_ss220/aesthetics/kitchen/code/kitchen.dm
:cl:
fix: Еда из микроволновки больше не оказывается под микроволновкой, пардон
/:cl:
> Fix: Microwave Layer

- config/example/config.toml
- modular_ss220/verbs/code/verbs.dm
- Добавляет перезарядку на респавн
- Убирает возможность возродиться без респавнабилити
Больше никаких смерть -> респавн -> смерть -> респавн
:cl:
add: Добавлена перезарядка на Респавн и проверка на респавнабилити
/:cl:
> Feat: Respawn cooldown

- _maps/map_files220/MetaStation/MetaStation.dmm
- _maps/map_files220/cyberiad/cyberiad.dmm
- _maps/map_files220/delta/delta.dmm
Фикс нерабочих контроллеров туреллей, из-за перевода зон.
Топорно но надёжно, даже если перевод слетит, проблем не будет.
Можно выключить турелли?
*показывает код карты
Умер в аплоуде
:cl:
fix: Контроллер туреллей снова работает
/:cl:
> Fix: Turret Controls

- modular_ss220/_defines220/code/donor.dm
Исправляем мисскомуникацию.
:cl:
fix: Возвращаем тир маленького работяги на 1-ый уровень бусти тира, как и было запланировано изначально
/:cl:
> fix: little worker donator level

- modular_ss220/verbs/code/verbs.dm
Что-то теперь игроки респавниться теперь совсем не могут, думаю, это должно исправить ситуацию.
Так было, и так должно быть.
Ну проверил на локалке.
С отключенным респавном админ респавнится, игрок - нет.
С включенным респавном админ респавнится, игрок - ждет.
:cl:
fix: Исправлена проблема с невозможностью респавна для обычных игроков.
/:cl:
> Allow respawn for regular players

- modular_ss220/jukebox/code/jukebox.dm
- modular_ss220/jukebox/code/jukebox_datum.dm
- modular_ss220/jukebox/code/jukebox_subtypes.dm
У барабанов снова отдельная папка для треков
фикс бага
Проверил на локалке
:cl:
fix: Барабаны снова используют отдельную папку для треков
/:cl:
> fix: drums

- modular_ss220/maps220/code/Areas/station.dm
Вернул удалённые зоны
В ветке translate надо будет перевести
> Return deleted areas

- modular_ss220/keybindings/_keybindings.dme
- modular_ss220/keybindings/code/admin_keybinds.dm
- modular_ss220/keybindings/code/client.dm
- modular_ss220/keybindings/code/communication_keybinds.dm
- modular_ss220/keybindings/code/living_keybinds.dm
Обновляет кейбинды по умолчанию для связи
Нет дубляжа, нет сломанного дубляжа
Зашел в игру, нажал резет
:cl:
fix: Фикс кейбиндов для связи по-умолчанию (сей, ми, асей и тд); убирает сломанные дубликаты
/:cl:
> Fix Default Keybindings for Comms

- modular_ss220/objects/code/weapons.dm
Фиксит название ящика с пневмошариками, из-за которого ломались ящики с береттами.
:cl:
fix: Исправлен вызов ящиков с береттами.
/:cl:
> Fixed pepperballs supply crate

- _maps/map_files220/cyberiad/cyberiad.dmm
- _maps/map_files220/delta/delta.dmm
- modular_ss220/balance/code/access/access.dm
~~Ебёт меня в жопу~~ Добавляет доступы в места где его не хватает
Меньше проблем с доступами
:cl:
del: Я устал от недовольства с доступами
tweak: Медик отбил свой доступ в химию, вирусологию и генетику у ЦК, наслаждайтесь :XyliPizdish:
tweak: Атмосферники получили обычный инженерный доступ, инженеры получили атмософский.
/:cl:
> Another access fixes

- _maps/map_files220/delta/delta.dmm
Удаляет лишние стены из комнаты для нагревания плазмы, что мешали ей очиститься после открытия ставней, добавляет вентилятор в комнате запуска бомб для предотвращения разгерметизации.
Микс комнату можно наконец опустошить. Бомбы запускаются без проблем.
Работает
:cl:
fix: Отредактированы помарки в комнате токсинов и комнате запуска на Дельте
/:cl:
> Toxins fixed

- modular_ss220/text_to_speech/code/tts_subsystem.dm
Пара медицинских аббревиатур и все.
Хорошо звучит.
На проде.
:cl: Maxiemar
tweak: Изменена TTS озвучка нескольких медицинских аббревиатур.
/:cl:
> More TTS acronyms

- modular_ss220/objects/code/platform.dm
Продавливает палку через платформу.
Палка продавлена через платформу.
https://github.com/ss220club/Paradise-SS220/assets/39908528/a875bbfd-8984-463e-a3b4-aabc1cce9089
:cl: Maxiemar
fix: Палка мага теперь свободно пролетает через платформы.
/:cl:
> Make immovable rod able to go through platform

- modular_ss220/objects/_objects.dme
- modular_ss220/objects/code/smartfridge.dm
- modular_ss220/silicons/code/items/gripper.dm
Ну складывались таблетки в холодос, да не выкладывались из захвата, что приводило к множеству ссылок на одно и тоже, телепортам и т.п. Еще согласно здравому смыслу разрешаем медборгам хватать патчи.
Баги плохо.
Ну локально работает.
:cl: Maxiemar
tweak: Медицинские борги теперь могут хватать патчи с помощью устройства захвата.
fix: Исправлена проблема, возникающая при помещении боргом предметов в холодильник.
/:cl:
> Medborg gripper fixes

- code/controllers/master.dm
Добавил нолик к сиду для тестов, так как снова падают чазмы заставляя их падать...
> Fix: Unit Tests runtime. Again

- _build_dependencies.sh
- code/modules/food_and_drinks/food/foods/meat.dm
Ну тут эксплойт фикс и еще че то, че там подсосут и насколько ПР быстро вмержится...
> Merge upstream 10.03.2024

- modular_ss220/balance/_balance.dme
- modular_ss220/balance/code/items/storage/closets.dm
- modular_ss220/balance/code/items/storage/surgical_tray.dm
- modular_ss220/objects/code/closets.dm
Добавил пару джаунтер гранат в шкафчик парамедику
Парамедик может вытаскивать с чазмов, если осмелится
Одну использовал, но вот
Ага
:cl:
add: Парамедику в шкафчик добавлено 2 Jaunter гранаты. Если надо больше то просите у шахтёров.
/:cl:
> add: 2 Jaunter Grenades for Paramedic

- _maps/map_files220/generic/Lavaland.dmm
Добавляет биллборд с оффов на лаву
Красивое
В игре увидете
Нет
:cl:
add: Добавлен новый приветственный биллборд на лаваленд, на нашей лаве его не было.
add: Добавлены хранилища для сьютов на каторгу, на нашей лаве их не было.
/:cl:
> Lavaland Billboard

- modular_ss220/chat_badges/code/badges.dm
Ну, рефактор бейджей и теперь отображаются отдельно донатерский бейдж и бейдж от профы.
Вроде пофиксил дерганье бейджей, когда они прилетали хуй пойми откуда. Обвиняю `bicon_cache` в кешировании по адресу в памяти.
Вклад каждого виден.
Скомпилировалось, попробовал - было норм. Надеюсь, на проде будет так же.
Тест сранья вроде пройден.
:cl: Maxiemar
tweak: В OOC чате возле ника теперь отображаются сразу 2 значка: значок донатера (зависит от уровня) и значок, зависящий от роли на сервере/проекте.
fix: Значки в OOC чате теперь не должны пропадать в никуда, появляться из ниоткуда и заменять друг друга в случайном порядке.
/:cl:
> Badge changes

- modular_ss220/screentip_change/code/screentip.dm
Опускает текст скрин-типов ниже, чтобы они не закрывались первым рядом активных кнопок
:cl:
fix: Скрин-типы больше не закрываются первым рядом активных кнопок.
/:cl:
> move screentip to not be hidden by the first row of abilities

- _maps/map_files220/MetaStation/MetaStation.dmm
- _maps/map_files220/RandomRuins/SpaceRuins/whiteship.dmm
- _maps/map_files220/RandomZLevels/blackmarketpackers.dmm
- _maps/map_files220/cyberiad/cyberiad.dmm
- _maps/map_files220/delta/delta.dmm
- _maps/map_files220/generic/centcomm.dmm
Чистка карт в связи с последними обновами UpdatePaths
- Чистка всех tag'ов
- Чистка всех disposal'ов
не знаю
.l.
посмотрел в редакторе)
NPFC
> Cleanup tag & disposal vars on our maps

- modular_ss220/chat_badges/code/badges.dm
Fixes #1121.
Da.
:cl:
tweak: Иконки теперь отделены от ника пробелом в OOC чате.
/:cl:
> Add space between badges and ckey

- _maps/map_files220/cyberiad/cyberiad.dmm
Жигу КМу даёт
Подкурить можно
Нет
:cl:
add: Кибериада: КМ получил свою зажигалку Зиппо
/:cl:
> Cyberiad: QM Zippo

- modular_ss220/smart_equip_targeted/code/smart_equip_targeted.dm
В апстриме поменяли сигнатуру, адаптация.
Lorem ipsum.
Да.
:cl:
fix: Исправлена работа кеибиндов на помещение предмета в рюкзак или на пояс.
/:cl:
> Fix quick equip

- _maps/map_files220/cyberiad/cyberiad.dmm
- _maps/map_files220/delta/delta.dmm
Удалил лишние венты с дельты, слегка подправил венты в прибытии коробки
:cl:
fix: Убраны лишние не подключённые венты на дельте, подключены не подключённые у святоши.
/:cl:
> Clean forgotten vents

- modular_ss220/credits/_credits.dme
- modular_ss220/credits/code/SScredits.dm
- modular_ss220/credits/code/aprils_fool_credits.dm
Добавляем титры для дня дурака
:cl:
add: Добавлены дурацкие титры
/:cl:
> add: Aprils fools credits

- modular_ss220/balance/code/access/access.dm
Добавляет парамедику доступ в операционные и док карго шаттла, потому что через него приходится ходить на шахту на Мете.
Думайте.
Даже не компилировал.
:cl:
tweak: Парамедик получает доступ в операционные и док карго шаттла.
/:cl:
> Paramedic access tweak

- code/controllers/master.dm
Чинит рантайм в тесте с коробкой.
Забыл.
> Unit test runtime no more

- modular_ss220/text_to_speech/code/tts_component.dm
- modular_ss220/text_to_speech/code/tts_vv.dm
С варедитом и так можно вручную это делать. Немного удобства.
> Modifying TTS Component needs VAREDIT, not ADMIN

- .github/labeler.yml
Лейблы снова вешаются на наши карты
На количество изменений не смотрите, Prettier
> fix: Labeler doesn't apply labels on maps

- code/modules/shuttle/emergency.dm
Вырезал долгий и назойливый звук во время полёта шаттла
Нет двух минут действования на нервы
Нет
:cl:
del: Вырезан звук полёта шаттла (2 минуты ВЖВЖВЖВЖВЖВЖ)
/:cl:
> del: Shuttle progress sound

- _maps/map_files220/stations/deltastation.dmm
Заменил неправильную зону, всё
Нет салона робототехники в общем офисе
Нечего показывать
:cl:
fix: Керберос: Общий кабинет теперь не салон робототехники
/:cl:
> fix: Replace incorrect area on Delta

- _maps/map_files220/stations/boxstation.dmm
Чинит комнату смерти в ксено на коробке
*shrugs
Не покажу
Убил радужного слайма которого заспавнил там
:cl:
fix: Кибериада: Комната смерти в ксено теперь убивает
/:cl:
> [Cyberiad] Fix xeno Kill Chamber

- _maps/map_files220/stations/boxstation.dmm
- _maps/map_files220/stations/deltastation.dmm
- _maps/map_files220/stations/metastation.dmm
Гарантирует morgue доступ всем шлюзам в морг, меняет доступ на maintenance в переходе на Мете.
Mapdiff вряд ли информативен, но увы
Я походил детективом, доктором - вроде нормально открывается все.
:cl: Maxiemar
tweak: Исправлены доступы на шлюзах в морги.
tweak: Исправлены доступы на шлюзах в переходе на Мете, теперь инженеры (все) пройдут там.
/:cl:
> Access tweak №28767

- code/modules/antagonists/traitor/contractor/datums/objective_contract.dm
Чинит контрактора, проблема была в регулярке Clueless
Спиздил СМО, отправил СМО, получил ТК.
:cl:
fix: Контрактник починен. Можете воровать вульпочек за ТК.
/:cl:
> fix: Contractor

- modular_ss220/maps220/code/layers.dm
#1181
https://github.com/ss220club/Paradise-SS220/assets/144079671/1b73f876-8f44-4fe8-a767-a5169abae8ac
:cl:
fix:  Вещи в шкафу теперь лежат в шкафу а не под ним.
/:cl:
> Fix: Closet layer

- modular_ss220/whitelist/_whitelist.dm
- modular_ss220/whitelist/code/whitelist.dm
Теперь не нужно нажимать на update_whitelist.
:cl:
tweak: Теперь не нужно нажимать на update_whitelist для игроков которых добавили в вайтлист во время раунда
/:cl:
> tweak: whitelist auto update

- modular_ss220/mobs/code/simple_animal/friendly/mouse.dm
Закрываем абуз через труп мыши и тендрил эшей.
Заспавнил мышку, убил, зафиксировал гиб от тендрила
:cl:
fix: убран абуз через труп мышки и тендрил эшей
/:cl:
> fix tendril mouse abuse

- modular_ss220/text_to_speech/code/tts_component.dm
Добавляет ANY голоса в Select Voice
:cl:
fix: В Change Voice теперь можно выбрать без-гендерные голоса
/:cl:
> Fix Change Voice voice selection

- .github/workflows/check_changelog.yml
Запускает валидацию чейнджлога, когда ПР выходит из драфта.
> Validate CL on ready_for_review

- _maps/map_files220/generic/centcomm.dmm
- modular_ss220/clothing/code/suits.dm
- modular_ss220/maps220/code/directions.dm
- modular_ss220/vending/code/vending.dm
- modular_ss220/vending/code/vending_items.dm
Я совершенно точно не знаю, откуда на ЦК борго-пушки (мне можно верить). Теперь их там нет.
Сделал спальню для ОСО. Добавил вариант пальто ОСО. 
Закрыл батарею БСА створками.
Мелкие проблемы с логикой наименований в оружейке. 
Мехи теперь закрыты створками, а не дверками.
Мелкие косметический правки.
Валлмеды с нанитами в зоне экипажа. 
Исправляет проблемы нового ЦК.
Локалка - ворк.
:cl:
fix: Мелкие правки зоны ОБР на новом ЦК. В зоне экипажа добавлены валлмеды, которые помогут раненым сотрудникам в любых ситуациях.
/:cl:
> Fix: centcomm minor issues

- _maps/map_files220/stations/boxstation.dmm
Заблокирована возможность простреливать ИИ за 2 двери до него лазером
Малф ИИ проживёт лишнюю 1 минуту
:cl:
tweak: "домик ИИ" в котором он расположен был перестоен так, чтобы его нельзя было прострелить через дверь
/:cl:
> Перестройка сателлита ИИ в пользу сбойного ИИ.

- modular_ss220/logs/code/logging.dm
Возвращаем логгирование целей
Проверил на локалке
NPFC
> fix: objectives logging

- interface/skin.dmf
> Fix path in skin.dmf

- _maps/map_files220/stations/deltastation.dmm
Поставил забытую плитку под дверь в техи вирусологии
:cl:
fix: Дельта: БС аномалия уничтожила плитку под дверью в техи вирусологии, мы вернули её на место
/:cl:
> Remove space from maints

- _maps/map_files220/generic/centcomm.dmm
Поменял местоположения комнаты со скелетами на ЦК.
Мелкие правки офисов.
Триалы довольны, Пупс доволен, Кону доволен, Карчес доволен (спал во время принятия решения).
локалка, доступ 101
:cl:
fix: 23.05.2024. Скелетный инцидент.
/:cl:
> Fix: skeleton incident

- modular_ss220/maps220/code/Station/station_datums.dm
Добавлены ссылки на нормальные интерактивные карты - https://webmap.affectedarc07.co.uk/
:cl:
add: Теперь, если вы нажмёте на кнопку "Карта" справа сверху, вам предложит открыть в браузере интерактивную карту, на которой сейчас проходит раунд
/:cl:
> Add webmap urls

- code/datums/outfits/outfit_admin.dm
- code/modules/admin/verbs/deathsquad.dm
- code/modules/admin/verbs/one_click_antag.dm
- code/modules/admin/verbs/striketeam_syndicate.dm
- code/modules/response_team/ert.dm
Перевод рангов у ЕРТ, Дедсквада и подобного
> Translate: Ranks

- code/modules/response_team/ert_outfits.dm
> Translate: Ranks fix

- code/datums/keybindings/client.dm
- code/datums/keybindings/mob_keybinds.dm
- code/datums/keybindings/robot_keybinds.dm
Доперевод Keybinding'ов, фикс пропавших (fullscreen)
> Translate: Fix keybindings missed translations

- _maps/map_files220/generic/centcomm.dmm
Обновил немного визуал Центкома, актуализировал наполнение у шаттла трейдеров
:cl:
tweak: У торговцев на шаттле появились специфичные товары, зависимые от их принадлежности (СССП, Воксы и т.п.)
/:cl:
> Update Centcom visual, fix some issues

- code/game/area/ss13_areas/science_areas.dm
Перевод зоны после апстрим мержа
> Translate: Translate area after upstream merge

- modular_ss220/maps220/code/Station/station_areas.dm
Какого-то хера перевод зон был в ветке translate, хотя это модульные зоны...
@Legendaxe если будет мерж конфликт на ветке translate, то бери в пользу моей ветки.
> Translate: Modular areas

- modular_ss220/mobs/code/simple_animal/pets/slugcat.dm
**Починил баг с дюпом шляп через слизнекотика**
"Fixes #1170"
**Никаких бесплатных шляп для персонала**
**Проверил в игре**
:cl:
fix: Слизнекот больше не создает шляпы из блюспейс пространства
/:cl:
> Fix slugcat duping hats

- code/modules/hallucinations/effects/minor.dm
> Translate: Minor hallucinations

- _maps/map_files220/stations/boxstation.dmm
Добавлен Dye Generator на Кибериаду
:cl:
add: Кибериада: Добавлен Dye Generator в заброшенную парикмахерскую.
/:cl:
> Add: Dye Generator to Cyberiad

- milla/src/constants.rs
> [TM] Max Z levels

- code/__DEFINES/emotes_defines.dm
- code/datums/status_effects/neutral.dm
Перевод игры «камень-ножницы-бумага»
Две локалки
> Translate RPS

- code/game/gamemodes/malfunction/Malf_Modules.dm
Чинит робофабрику
Чинит робофабрику
Локалка, всё прошло спокойно
:cl:
/:cl:
> Translate: Malf AI, fix cyborg transformer

- modular_ss220/modular_ss220.dme
- modular_ss220/redis220/_redis220.dm
- modular_ss220/redis220/_redis220.dme
- modular_ss220/redis220/code/news.dm
Отправляет ивент о новостях в редис, чтоб потом отправлять их в дс
> Feat: Emit news event

- modular_ss220/redis220/_redis220.dme
- modular_ss220/redis220/code/tgs_deploy_bandaid.dm
Да хуй его знает. Вдруг сработает
> bandaid: redis reconnect on tgs event

- _maps/map_files220/stations/boxstation.dmm
- _maps/map_files220/stations/deltastation.dmm
Бахнул на дельте факс для АВД с департаментом, на коробке поменял пиксельшифт, выглядит беттер
ЭРПЭ
ЭРПЭ
нет
:cl:
fix: Дельта: факс АВД снова работает как положено.
tweak: Кибериада: факс АВД теперь стоит не на краю стола.
/:cl:
> Fix: Немного починил факсы

- modular_ss220/redis220/code/news.dm
Не пытаемся сериализовать картинку, если ее нет
> fix: nullcheck for news img

- _maps/map_files220/stations/boxstation.dmm
- modular_ss220/objects/_objects.dme
- modular_ss220/objects/code/computer.dm
- Переложил трубы, чтобы они не наслаивались.
- Пофиксил мониторинговые консоли.
- Минорные визуальные изменения.
- Небольшая чистка.
+ Мапдифф
:cl:
fix: Кибериада - Инженерка: Починил некоторые мониторинговые консоли.
tweak: Кибериада - Инженерка: Местами переложил трубы чтобы не было наслоения.
tweak: Кибериада - Инженерка: Минорные визуальные изменения.
/:cl:
> Cyberiad: Engineering - Piping, Fix Monitoring & Network consoles, Cleanup

- modular_ss220/camera_nanomap/code/camera.dm
Фиксит рендер камер дописывая вызов функций рендера вида камеры в наш модульный код
Люди снова видят что происходит на камерах
Запустил локалку и посмотрел камеру. Однако, пришлось релоднуть графику
:cl:
fix: Рендер на камерах должен быть пофикшен
/:cl:
> [Fix] Camera render fix

- modular_ss220/text_to_speech/code/tts_component.dm
При изменении TTS с помощью VV теперь также обновляется и ДНК.
:cl:
fix: Изменение голоса через админ-панель теперь сохраняет информацию о голосе в ДНК
/:cl:
> Update DNA tts seed on VV change

- modular_ss220/jobs/code/donor/job/5_tier_jobs.dm
Позволяет VIP-у (5-ый тир донатная джобка) понимать и говорить на всех доступных библиотекарю языках
Позволит участвовать в больших РП-ситуациях
Не тестировал
:cl:
add: VIP стал мультиязычным
/:cl:
> VIP получает возможность говорить на всех языках

- .github/labeler.yml
Ну я как обычно не могу с первого раза нормально сделать
> Fix: Label name

- _maps/map_files220/stations/boxstation.dmm
- _maps/map_files220/stations/deltastation.dmm
- modular_ss220/maps220/code/layers.dm
Поднял слой дисплеев до 3.4 и поменял один ИИ дисплей на статус дисплей в прибытии дельты
> Increace display layers to 3.4

- .github/labeler.yml
https://github.com/ss220club/Bandastation/pull/419
> BandaStation labeler tweaks

- _maps/map_files220/stations/deltastation.dmm
**Восстановление психиатрии на карте дельта**
Ранее заброшенная психиатрия становится вновь рабочей.
Расширение возможностей психологу на карте дельта.
Локалка
:cl:
tweak: Delta/Восстановлена психиатрия. добавлены недостающие алармы, выключатели. Небольшие правки в техах меда. Проведена мусорка.
/:cl:
> [Remap] Delta: psychologist office restoration

- modular_ss220/balance/_balance.dme
- modular_ss220/balance/code/species/skrell.dm
Добавляет расе скреллов ряд новых особенностей:
Алкоголь теперь наносит 5 единиц урона токсинами и 1 урон почкам. При поломанных почках наносит 15 урона токсинами. (Реальный урон зависит от процента содержания этанола).
Ночное зрение, слабее чем у таяр, но сильнее чем у людей.
Сканнер реагентов для пищи и растворов.
Уменьшение урона от токсинов (Множитель 0.9)
Большее соответствие лору расы на вики, большее отличие от стандартных хуманов (Смотреть скриншоты для пруфов с вики).
Заспавнил себе скрелла, залил ему водки в глотку, потом засканил реагенты, а под конец погулял в техах без фонарика.
:cl:
tweak: Скреллы теперь получают урон токсинами от алкоголя.
tweak: Скреллы теперь видят в темноте чуть-чуть лучше людей.
tweak: Скреллы теперь получает чуть меньше урона от токсинов.
add: Скреллы …
> Few new features for skrells

- _maps/map_files220/generic/Lavaland.dmm
- _maps/map_files220/stations/boxstation.dmm
- _maps/map_files220/stations/deltastation.dmm
- _maps/map_files220/stations/metastation.dmm
Фикс предупреждений в юнит тестах минорными изменениями, которые порой мозолят глаза.
> Fix unit-tests late initialize warnings

- _maps/map_files220/RandomRuins/SpaceRuins/spacehotel.dmm
- _maps/map_files220/RandomZLevels/beach.dmm
- _maps/map_files220/RandomZLevels/caves.dmm
- _maps/map_files220/generic/centcomm.dmm
- _maps/map_files220/stations/boxstation.dmm
- _maps/map_files220/stations/deltastation.dmm
- modular_ss220/aesthetics/decals/code/decals.dm
Такой себе фикс цветов декали, но увы
Пробежался глазами по затронутым картам
> Fix wood decal colors

- _maps/map_files220/generic/Lavaland.dmm
- _maps/map_files220/stations/boxstation.dmm
- _maps/map_files220/stations/deltastation.dmm
- _maps/map_files220/stations/metastation.dmm
- modular_ss220/species/code/mob/living/carbon/human/eat/eat_list_tech.dm
Чинит путь маячка.
Маячки снова работают.
Mapdiff
Подсосались спрайты в SDMM.
:cl: Maxiemar
fix: Маяки для телепорта снова работают.
/:cl:
> Fix tracking beacon path

- _maps/map_files220/generic/centcomm.dmm
Добавил кучу новой фигни. 
- импланты в карго
- телепортер в карго
- бс быстрозаменители в карго и бс штуки которые чинят свет (хыдыды)
- починил общие доступы там где они не должны были быть, заменил на офицерские для ЦК и т.п
- починил доступ в командный центр
- добавил в бриф ОБР для ОСО телескрины, как и в его комнату
- добавил в комнату ОСО два плаща
- массовая замена консолей с датчиками экипажа на их продвинутые версии
- починил доступы в СЦК у телепортеров
- поменял бесящие меня лесенки в брифе ОБР на нормальные
что там тестировать...
> Доработка ЦК

- modular_ss220/title_screen/code/new_player.dm
Добавляет Swap Server verb во вкладку OOC. В OOC, потому что Ghost в лобби недоступно, а хотелось бы видеть и в лобби 😎 
Можно свапнуть сервер в игре.
Я смог открыть example.com и в лобби, и через verb.
:cl: Maxiemar
tweak: Возможность удобно сменить сервер теперь доступна и во время игры. OOC -> Swap Server
/:cl:
> Swap Server Verb

- modular_ss220/title_screen/code/title_screen_datum.dm
Фиксит сброс цвета кнопки если тайтл скрин обновляется
:cl:
fix: Цвет кнопок в лобби больше не должен сбрасываться
/:cl:
> Fix reseting buttons color

- modular_ss220/bureaucracy/code/forms.dm
Обновление даты в общей форме ЦК. В остальных годов нет, так что поменял только тут.
Теперь ЦК отправляет не просроченные на год факсы
Тестовый запуск и проверка изменения номера года показало успешный результат внедрения изменения
:cl:
fix: На ЦК напечатали формы с коректным годом
/:cl:
> CC form update

- _maps/map_files220/stations/deltastation.dmm
Исправление ID факса магистрата на карте Керберос (Delta)
Факс теперь будет работать
Не требуется
Не требуется (портирован факс с коробки)
:cl:
fix: Дельта | Добавлен ID факсу магистрата, для появления его в рассылке
/:cl:
> HotFix | Magistrate Fax ID | Delta

- _maps/map_files220/generic/centcomm.dmm
попытка устранить проблему с неработающим телепортом. (он работает но хуево, перестановка возможно поможет избежать этого)
> Fix: CC cargo teleport

- modular_ss220/text_to_speech/code/_defines.dm
- modular_ss220/text_to_speech/code/seeds/silero.dm
Добавляем новые голоса от Силеро
:cl:
add: Добавлено 4 вариации голоса пророка Санбоя, 3 голоса из "The Last of Us", 15 голосов из киберпанка, 2 голоса из Deep Rock Galactic и голос расказчика из "Падал прошлогодний снег"
/:cl:
> add: new silero voices 30.08.2024

- _maps/map_files220/stations/deltastation.dmm
Мелкие правки и дополнения по РнД после ремапа | Delta
Исправление ошибок
Не требуется
Локалочка
:cl:
tweak: Дельта: Добавлена кнопка управление болтами в проходной ксенобиологов на выход в техи. 
tweak: Дельта: Добавлена коробка кубов с Нианами в вирусологии меда.
tweak: Дельта: Изменен полигон РнД. Добавлено освещение, область расширена.
fix: Дельта: Правки раскрасок полов, оголенных проводов и прочее.
/:cl:
> Fix: Remap RnD | Delta

- _maps/map_files220/stations/deltastation.dmm
Одна из двух фаер алярм под нож. На ее место примостилась реквест консоль.
Возвращена реквест консоль в робототехнику
Допки будут выполняться
Не требуется
Не требуется, взято с консоль с коробки
:cl:
fix: Дельта. Возвращена реквест консоль в робо
/:cl:
> HotFix | Robotics Request Console | Delta

- _maps/map_files220/generic/Lavaland.dmm
- _maps/map_files220/stations/boxstation.dmm
- _maps/map_files220/stations/deltastation.dmm
- _maps/map_files220/stations/metastation.dmm
Применил пропущенный UpdatePath скрипт для реквест консолей
Улыбаемся и машем (надеемся на лучшее)
> Apply Request Console directions UpdatePath

- modular_ss220/balance/code/items/weapons.dm
Лазеры и еганы теперь bulky
:cl:
tweak: Лазеры и еганы теперь не влезают в рюкзак. Хайриски не затронуты
/:cl:
> [TM] Bulky lasers

- _maps/map_files220/stations/boxstation.dmm
- _maps/map_files220/stations/deltastation.dmm
- _maps/map_files220/stations/metastation.dmm
Исправляет позицию гравгена в связи с обновлением большой машинерии
:cl:
fix: Исправлена съехавшая позиция Гравгена.
/:cl:
> Fix gravgen position

- _maps/map_files220/stations/boxstation.dmm
- _maps/map_files220/stations/deltastation.dmm
- _maps/map_files220/stations/metastation.dmm
Замена стекол в холодильниках ксено и серверных РнД.
РнД не будет продувать
Не требуется
:cl:
fix: Коробка/Дельта/Мета | Холодильник ксено, Серверная РнД: Заменены обычные стекла на плазму.
/:cl:
> Fix: Server Coldroom & Xeno Fridge: Plasma windows | Boxstation/Deltastation/Metastation

- modular_ss220/emotes/code/emote.dm
В названии всё сказано
Спам эмоута от особо одарённых будет 6 раз в минуту
Заспавнился за вульпу...
:cl:
tweak: Урчание и гавкание теперь имееют КД в 10 секунд, как у воя
/:cl:
> Make `ururu` and `bark` cooldown 10 seconds

- modular_ss220/text_to_speech/code/base_seeds/mobs/other.dm
Добавлены собственные ТТС сиды для констрактов.
:cl:
tweak: Для конструктов были прописаны собственные ТТС голоса, вместо стандартного.
/:cl:
> Add TTS seeds for constructs

- modular_ss220/credits/code/credits.dm
- modular_ss220/credits/code/halloween_credits.dm
:cl:
fix: Титры снова работают нормально
/:cl:
> fix: credits

- .github/workflows/render_nanomaps.yml
Fixes #1244.
При следующем ПРе.
> Make `Render Nanomaps` have `CL не требуется`

- _maps/map_files220/generic/Admin_Zone.dmm
Добавлены зарядники для боргов и КБП в гост бар
КБП не будут страдать
Не требуется
Не требуется
:cl:
tweak: Гост Бар: Добавлены два зарядника для боргов
/:cl:
> Tweak: Admin_Zone | GhostBar add recharge station

- .github/ISSUE_TEMPLATE/config.yml
> Enable blank issue forms

- .github/labeler.yml
Чинит фильтр ветки путем изменения неправильной регулярки.
gihub -> github
Проверил на форке.
> Labeler fixes

- _maps/map_files220/RandomRuins/SpaceRuins/mechtransport_new.dmm
- _maps/map_files220/RandomZLevels/blackmarketpackers.dmm
- _maps/map_files220/RandomZLevels/wildwest.dmm
- _maps/map_files220/generic/centcomm.dmm
- _maps/map_files220/stations/boxstation.dmm
- _maps/map_files220/stations/deltastation.dmm
- _maps/map_files220/stations/metastation.dmm
- tools/maplint/lints/wall_stacking.yml
Пора наконец убрать нахуй это болото на стенах, которое в редакторе под ними
Меньше уродства
MapDiff
А?
:cl:
tweak: Мы наняли уборщика, дабы он очистил стены от грязи, правда с плесенью и ржавчиной он не справился.
/:cl:
> Clean dirt under walls

- _maps/map_files220/generic/Admin_Zone.dmm
Добавил реле телекомов ЦК, диски в ботанику, убрал ограничения по доступу с компутера библиотеки
ураа приколы для гостов
зашел, посмотрел : ураа диски появились, ураа можно печатать книжки
телекомы не проверял......................
:cl:
tweak: Гостбар: Добавлены ботанические диски и реле телекомов. Библиотечный компьютер больше не запрашивает доступа.
/:cl:
> Фиксы гостбара

- modular_ss220/text_to_speech/code/_defines.dm
- modular_ss220/text_to_speech/code/seeds/silero.dm
Добавляем новые голоса силеро
:cl:
add: Добавлено 9 голосов из новых спейсмаринов и один голос из "Падал прошлогодний снег"
/:cl:
> add: new voices

- _maps/map_files220/stations/boxstation.dmm
- _maps/map_files220/stations/deltastation.dmm
- _maps/map_files220/stations/metastation.dmm
Делает турели улучшаемыми малф иишкой
о_О ну это... эм.... механ который не работал?
заспавнил хумана, стреляют маленькие такие лазеры очень мало демеджа, малфнулся, улучшил турельку........
это теперь аннигиляторные пушки....
:cl:
fix: Малф ИИ снова может улучшать свои турели
/:cl:
> Малф снова может улучшать турели

- _maps/map_files220/generic/Admin_Zone.dmm
Удаляет маску сб путём выреза автомата и заменой кучей вещей
:cl:
tweak: Гостбар: Заменил СБшный автомат.
/:cl:
> Remove sus from ghostbar

- code/modules/mob/new_player/new_player.dm
:cl:
fix: Больше нельзя поставить реди, если вы выбрали персонажа расы, на которую у вас отобрали вайтлист.
/:cl:
> fix: ready without specie whitelist

- _maps/map_files220/stations/deltastation.dmm
- _maps/map_files220/stations/metastation.dmm
Добавляет недостающие доступы для windoor на паре карт. У оффов они есть.
На Дельте 1 для карго, 1 для меда, 3 для евы.
На Мете 3 для карго, 1 для рнд, 1 изменил с рнд на робо (в робототехнике).
Потому что игроки не должны попадать в чужой отдел без доступа.
<details>
<summary>Доступ на Мете для стойки РНД и карго</summary>
</details>
<details>
<summary>Доступ на Дельте для карго, евы</summary>
</details>
тестировал через sdmm (надёжно).
:cl:
fix: Windoor'ы получили свои недостающие доступы на Дельте и Мете.
/:cl:
> Fixes windoors with no access at departments

- modular_ss220/vending/code/vending.dm
перемещаем перчатки воксов из ютула контрабанды в инженерную, но зато за 300 баксов
Т.к. перчатки и так можно купить в ассистентской и воксы не могли купить еще одни. (расизм)
:cl:
tweak: воксовские изольки перемещены в контрабанду вендора инженеров, а не YouTool
tweak: воксовские изольки подешевели до 300
/:cl:
> Vox insulgloves

- .github/workflows/build_rust.yml
В рамках подготовки к мерге апстрима.
> Update rust workflow

- _maps/map_files220/stations/boxstation.dmm
Закрывает ишуе https://discord.com/channels/1097181193939730453/1301073300100878376
Фикс оборванной трубы в техах меда на Кибериаде.
:cl:
fix: Кибериада: Исправлена оборванная труба в техах меда.
/:cl:
> Fix piping in Cyberiad med. maints

- _maps/map_files220/stations/deltastation.dmm
Докинул проводку которую забыл сделать давным давно. Так же немного переделал трубу из смеси в отходы (более фешн, юноу?).
Потому что свои косяки надо исправлять.
Проверил - все ворк
:cl:
fix: Центральное командование отправило профессиональный инженерный отряд на ИСН Керберос для выявления проблем с питанием турбины и северо-западных солнечных панелей. Проблема была устранена.
/:cl:
> Fix: Delta wires in atmos

- modular_ss220/translations/code/ru_names/ru_name_base.dm
В declent initial теперь пихаем имя, а не путь атома
> Update declent initial

- _maps/map_files220/generic/centcomm.dmm
Фикс неработающего крематория на Трурле.
Можно сжигать тела на Трурле.
Локалка, ворк
:cl:
fix: Крематорий Трурля снова работает. ИСКЛЮЧИТЕЛЬНО (!!!) в добрых целях.
/:cl:
> Fix: CentCom crematorium

- _maps/map_files220/stations/deltastation.dmm
- Исправлены некоторые ошибки, недочеты.
- Визуальный импрувмент (по большей части того что меня бесило, такие дела).
- Все что возможно было сделать хелпером - сделано теперь хелпером (экстернал и locked аирлоки).
- Местами была переложена машинерия, незначительные перестановки в комнатах.
Посмотрим
MDB
Проверил все экстерналы в игре, глянул изменения визуала на локалке.
:cl:
tweak: Дельта: Были проведены общие визуальные улучшения, незначительные перестановки и исправления недочетов.
/:cl:
> Delta basic overhaul

- _maps/map_files220/stations/deltastation.dmm
Фикс накаканого после апдейта
NPFC
> Delta fix visual overhaul update issues

- _maps/map_files220/stations/deltastation.dmm
Добавляет недостающие трубы.
Все продувается, все задувается.
Все продувается, все задувается.
:cl: Maxiemar
fix: Комната с турбиной подключена к общей системе жизнеобеспечения на Керберосе.
/:cl:
> Connect turbine room to the central life support atmospherics 

- modular_ss220/clothing/code/suits.dm
Убирает ненужный флаг некоторым шмоткам, не заметил при мергировании апстрима.
Баги плохо.
Так сделано в апстриме, и я реально верю, что это поможет.
:cl: Maxiemar
fix: С курток снято ERP заклятие.
/:cl:
> Fix ERP jackets

- modular_ss220/antagonists/_antagonists.dme
- modular_ss220/antagonists/code/morph/morph.dm
…ches 8
Возвращаем анонс разрешающий ВХ против морфов.
Заспавнил на локалке 8 морфов - получил анонс. При дальнейшем спавне морфов анонс не повторяется.
После рестарта заспавнил 7 морфов, гибнул одного и заспавнил еще двух - получил анонс
:cl:
add: После того как количество живых морфов достигает 8 - появляется анонс разрешающий ВХ против них.
/:cl:
> add: Morphs announcement

- README.md
Добавляет директорию с приколами с гунов в список с особой лицензией в README.
> Update license section in README.md

- _maps/map_files220/stations/metastation.dmm
Чинит мусоропровод у офиса ГСБ и добавляет принтер в каюту капитана
Теперь ГСБ сможет выкидывать мусор из своего офиса и не получать его обратно в лицо. А капитану теперь не придется бегать к ГП в поисках принтера для нового отчета на ЦК.
Проверил на локалке
:cl:
add: Цереброн: добавлен принтер в каюту капитана
fix: Цереброн: исправлен мусоросброс офиса ГСБ
/:cl:
> Fix disposalpipe of HoS office

- _maps/map_files220/stations/deltastation.dmm
- _maps/map_files220/stations/metastation.dmm
Убрал лишнюю трубу, тем самым исправил #1717
чтоб игра не жаловалась
:GAGAGA:
:cl:
fix: Убрана лишняя труба на Мете.
/:cl:
> Fix: Disposal metastation blea

- modular_ss220/credits/code/credits.dm
- modular_ss220/donor/code/client_procs.dm
На парадайзе не существует вл прайма, в этом больше нет нужды
:cl:
fix: Исправлена выдача донат тира администраторам и им подобным.
/:cl:
> [TM] Remove redundant SQL query

- _maps/map_files220/generic/centcomm.dmm
Обновляет доступы на всех дверях, ведущих в карго ЦК, на всех кнопках, переключающих двери, ведущие в карго ЦК, на всех дверях, ведущим к кнопкам, переключающим двери, ведущие в карго ЦК... короче, больше ОБР дебилы в ЦКшное карго не проникнут, ибо там стоят доступы ACCESS_CENT_SHUTTLES (106), которых ни у кого из ОБР нет
Нет дебилов на ЕРТ в отсеке с щитспавн вещами.
Там особо нечего смотреть
Заспавнился за командира ЦК и попробовал войти в карго ЦК через каждую из трех щелей, не получилось. Перезаспавнился за интерна ЦК и вошел нормально.
:cl:
fix: Говорят, что не очень умные сотрудники ОБР решили проникнуть в зону доставки Центрального Командования. Больше смешного не будет.
/:cl:
> No More ERT Pepegas In CC Shitspawn Zone
