ss220club/Paradise-SS220

modular_ss220/modular_ss220.dme, modular_ss220/screentip_change/_screentip_change.dm, modular_ss220/screentip_change/_screentip_change.dme, modular_ss220/screentip_change/code/screentip.dm
Сменяет позицию Screentips на 50 пикселей вверх
fixes https://github.com/ss220club/Paradise-Remake/issues/18
Скриптип не лезет в глаза
:cl:
tweak: Смена позиции Screentips на 50 пикселей вверх
/:cl:
=> tweak: Screentip position

modular_ss220/modular_ss220.dme, modular_ss220/smart_equip_targeted/_smart_equip_targeted.dm, modular_ss220/smart_equip_targeted/_smart_equip_targeted.dme, modular_ss220/smart_equip_targeted/code/smart_equip_targeted.dm
Позволяет хоткеям на сумку брать предмет из выбранного слота
fixes https://github.com/ss220club/Paradise-Remake/issues/48
Хоткеи круто
Потыкал хоткеи
:cl:
tweak: Позволяет хоткеям на сумку брать предмет из выбранного слота
/:cl:
=> [FEAT] Smart Equip

interface/skin.dmf
Меняет сглаживание с Nearest Neighbor (Distort) на Point Sampling (Normal)
+Меньше ряби, никаких преследующих полосок
+Пиксели не деформируются
-Чуть больше мыла
До
После
Запустил - видно хорошо
:cl:
tweak: Смена стандартного сглаживания с Nearest Neighbor на Point Sampling
/:cl:
=> tweak: Nearest Neighbor to Point Sampling

code/game/atoms_movable.dm
Вызывать `Moved` только тогда, когда `Move` был успешен.
:cl:
fix: связанные с передвижением события вызываются только тогда, когда передвижение было по факту
/:cl:
=> fix: call `Moved` only if we actually moved

code/game/atoms_movable.dm, code/modules/mob/living/carbon/human/human_defense.dm, code/modules/mob/mob.dm, code/modules/mob/mob_movement.dm, code/modules/mob/mob_vars.dm, code/modules/surgery/organs/blood.dm
Исправляет еще пачку проблем с глайдингом, а именно когда при диагональном хождении в стену с пуленым обьектом, диагональное движение на vehicle, а так же выбо направления куклы при диагональной попытке передвижения в стену
:cl:
fix: запуленый обьект не дёргается при движении при диагональном движении  в стену, когда движение успешно
fix: сигвей и другие vehicle адеватно двигаются по диагонали
fix: все некотролируемые клиентом мобы имеют более-менее адекватный глайдинг
fix: правильный глайдинг при грабе
/:cl:
=> fix: fix another pack of gliding issues

code/modules/mob/mob_vars.dm, code/modules/projectiles/gun.dm
Update gun appearance flags, set default mob gliding to 8 (atom movable's value)
:cl:
fix: делает перемещение мобов, управляемыми игроком плавнее
fix: весь спрайт оружия трансформируется как одно целое (все оверлеи считаются частью спрайта)
/:cl:
=> fix: update gun appearance flags, set default mob gliding to 8 (atom movable's value)

modular_ss220/balance/_balance.dm, modular_ss220/balance/_balance.dme, modular_ss220/balance/code/items/weapons.dm, modular_ss220/modular_ss220.dme
Понижает вес станпрода до normal, чтобы его можно было положить в рюкзак
Мы с старопары привыкли что его можно класть в рюкзак
-
:cl:
tweak: Вес станпрода понижен до normal
/:cl:
=> Tweak: Stunprod weight

_maps/map_files220/RandomRuins/SpaceRuins/convoy_ambush.dmm, config/example/config.toml, modular_ss220/_maps220/code/RandomRuins/space_ruins.dm
Добавление новой косморуины: засада на группу транспортных кораблей NT (port/remap caravanambush from Skyrat)
Лут: дизейблер, два списанных ретро лазергана, 760 кредитов, 3 мета по 10 u., 2 фраг гранаты, стечкин, c4, плазмакаттер.
Больше косморуин - больше косморуин
Работает, молюсь на ребейз
:cl:
add: новая карта - convoy_ambush
/:cl:
=> SpaceRuin - Convoy Ambush

_maps/map_files220/cyberiad/cyberiad.dmm, modular_ss220/objects/code/platform.dm
- Добавляет портированные предметы из ПРа
https://github.com/ss220club/Paradise-SS220/pull/218
- Актуализация с оффами (отредактирован кабинет КМа в связи с тем что он теперь глава 💀, добавлены костыли в мед)
- Пояс чемпиона заменен на подтип wrestling (РуПара момент)
- Исправляет отсутствие доступа у шаттеров гейта
- Заменены варэдитные спавнеры
Актуализация карты
:cl:
add: Кибериада: Добавлены портированные предметы
tweak: Кибериада: Актуализация с изменениями оффов (костыли в мед, КМ - глава)
tweak: Кибериада: Пояс чемпиона заменен на подтип рестлера
fix: Кибериада: Исправлено отсутствие доступа у шаттеров гейта
/:cl:
=> Feat: Actualization of the Cyberiad, part 1

modular_ss220/text_to_speech/_tts.dme, modular_ss220/text_to_speech/code/seeds/base.dm, modular_ss220/text_to_speech/code/tts_seed.dm
:cl:
add: Синты теперь могут сменить себе голос в любой момент
add: Генокрады теперь воруют голос вместе с днк
add: Ерт теперь может выбрать себе голос при спавне
/:cl:
=> Feat: tts change for synths, cling, ert

modular_ss220/text_to_speech/code/rust_g_ss220.dm, modular_ss220/text_to_speech/code/tts_subsystem.dm, modular_ss220/text_to_speech/code/~undefs/~undefs.dm
Мелкие изменения в работе нашего растг
=> Ref: rustg220

_maps/map_files220/generic/centcomm.dmm, modular_ss220/maps220/code/objects.dm
- Добавляет фейковые лампы
- Заменяет всю машинерию ламп Центкома на фейки (кроме шаттлов)
- Фейки, не ломаются, на них не накладываются эффекты, и они практически не влияют на производительность, а как мы помним, машинерия грузит больше всего.
- Из минусов, возможно, это может повлиять как-то на РП составляющую?
Неотличимо
:cl:
add: Фейковые лампы
tweak: Вся машинерия ламп Центкома (кроме шаттлов) была заменена на фейковые
/:cl:
=> Feat: Fake Lights

_maps/map_files220/cyberiad/cyberiad.dmm
Возвращает точки спавна для СМО и вирусолога, плюс пара дополнительных для остальных мед. работников
Спавн где надо
[DIFF](https://affectedarc07.blob.core.windows.net/mdb2/images/661116452/17288203754/m/_maps_map_files220_cyberiad_cyberiad/0-diff.png) bot
Нет.
:cl:
fix: СМО и вирусолог снова появляются в меде раундстартом.
/:cl:
=> Fix: Medbay landmarks (Cyberiad)

_maps/map_files220/RandomRuins/SpaceRuins/convoy_ambush.dmm, _maps/map_files220/RandomRuins/SpaceRuins/infected_ship.dmm, _maps/map_files220/RandomRuins/SpaceRuins/mechtransport_new.dmm, _maps/map_files220/RandomRuins/SpaceRuins/voxraiders_1.dmm, _maps/map_files220/RandomRuins/SpaceRuins/whiteship.dmm
Фикс космических тайлов с активным атмосом на некоторых косморуинах: whiteship, convoy_ambush, voxraiders_1, mechtransport_new. Фикс положения кнопок на руине mechtransport_new. Фикс лампочек на некоторых руинах.
Меньше нагрузки - меньше нагрузки.
Что это?
:cl:
fix: убрал ненужные тайлы с активным атмосом на картах whiteship, convoy_ambush, voxraiders_1, mechtransport_new; починил лампочки там же.
/:cl:
=> FIx: SpaceRuins atmos

_maps/map_files220/cyberiad/cyberiad.dmm
Заменяет синди-дюфель в пыточной на обычный, с иконкой синди.
1000IQ мув
Нет смысла манчить
:cl:
tweak: В пыточной теперь обычный дюфель со спрайтом синди вместо синди.
/:cl:
=> Tweak: Replace syndie duffelbag (Cyberiad)

_maps/map_files220/cyberiad/cyberiad.dmm, _maps/map_files220/delta/delta.dmm
Превращает Дельту в зоопарк, возвращает собак, котов, моль в теха.
На Гипериаде мелкие упущенные правки с статуями и карпами в аквариумах друг напротив друга. 
Теперь на дельте у большинства пассивных отделов есть безопасные животины. Для хайпопа показали они себя отлично.
Нет
Да
:cl:
add: Дельта: Добавлен зоопарк.
add: Кибериада: Имена для карпов
add: Кибериада: Статуи
/:cl:
=> [MAP] Добавляем зоопарк на дельту, мелкие правки на Коробке

_maps/map_files220/cyberiad/cyberiad.dmm
Исправляет пропадающий шкаф на Кибериаде
https://discord.com/channels/1097181193939730453/1159895097308090408
Closes https://github.com/ss220club/Paradise-SS220/issues/341
Багы
-
В игре
:cl:
fix: Кибериада: Пофикшен пропадающий шкафчик
/:cl:
=> Fix: Cyberiad vanishing closet

code/game/gamemodes/traitor/traitor.dm
Меняет скейлинг трейторов с 1 на 5 игроков до 1 на 10 игроков
Меньше хаоса
С игроками потестим 🃏 
:cl:
tweak: Спавн 1 трейтора на 10 игроков вместо 5
/:cl:
=> tweak: spawn 1 traitor per 10 players

_maps/map_files220/cyberiad/cyberiad.dmm, modular_ss220/mobs/code/simple_animal/pets/pet.dm
- Фикс доступа у КМа
- Добавлено 4 места в зале суда
- Добавил Йорика в кабинет Магистрата
- Переложил пол в зале суда, поменял некоторые объекты
- Вернул кусок стекла в эквипменте СБ
- Подкорректировал описание Пэйперворка
— Если вы желаете, суд предоставит вам бесплатного адвоката.
— Благодарю, ваша честь, но лучше бы двух толковых платных свидетелей.
CoolstoryBob
:cl:
tweak: Кибериада: Добавлено 4 места в зале суда, переложил полы, поменял некоторые объекты
add: Кибериада: Йорик в кабинет Магистрата
fix: Кибериада: Фикс доступа к офису КМа
fix: Исправлено описание Пэйперворка в соответствии с его расположением
/:cl:
=> Fix: Cyberiad general fixes

_maps/map_files220/RandomZLevels/gate_lizard.dmm
Добавил бейзруф на все зоны, что бы не было предательских разгерм.
Заменил пару стен, подвинул уран ближе к генераторам.
Убрал пару сбивающих с толку проводов.
Дырок в планете не должно быть 
Локалка, работает 
:cl:
fix: Больше нельзя сделать разгерму на карте gate_lizard
/:cl:
=> Fix: awaymission baseturf

_maps/map_files220/RandomZLevels/wildwest.dmm
Решаю проблему кардинально, что бы лишний раз не плодить ненужный код - заменяю шлюзы культа в гейте wildewest на двери хранилища. 
Перевел фразы стептриггеров.
Нет невидимых шлюзов. Хоть где-то я не сру в код.
Локалка
:cl:
fix: На карте Wild West теперь нет проблем с невидимыми шлюзами культа...Потому что самих шлюзов теперь нет.
/:cl:
=> Fix: wildwest invisible airlocks

_maps/map_files220/cyberiad/cyberiad.dmm
Чуточку улучшает прибытие Кибериады
- Добавлен доп. порт стыковки "на будущее" и для симметричности
- Переложил плитку, декали
- Местами подвигал машинерию
- Визуальные улучшения
Улучшения Кибериады
+Мапдифф
В игре
:cl:
add: Кибериада: Добавлен новый порт стыковки в прибытие "на будущее"
tweak: Кибериада: Улучшена визуальная составляющая, местами подвинута машинерия
/:cl:
=> Feat: Cyberiad arrivals overhaul

code/controllers/subsystem/SSspacedrift.dm
Делает перемещение без гравитации плавным
При отсутствии гравитации перемещение будет плавным
Полетал в космосе. Да и step просто вызывает Move()
:cl:
fix: Глайдинг в космосе плавный
/:cl:
=> fix: make gliding in Zero-G set correctly

code/controllers/subsystem/SSticker.dm, modular_ss220/credits/code/SScredits.dm
Больше не будет музыки с простым черным экраном
:cl:
del: Удалены неработающие титры
/:cl:
=> hotfix: credits

_maps/map_files220/RandomZLevels/blackmarketpackers.dmm
Убрал активные турфы в гейте с кораблем контрабандистов.
Меньше нагрузка
Локалка
:cl:
fix: В гейте BMPtraiders убрал тайлы с воздухом из космоса.
/:cl:
=> Fix: BMPtraiders active turfs

modular_ss220/text_to_speech/code/hear.dm
Ревертит кринжовый голос при шёпоте.
в Силеро плохо реализован шёпот (а если точнее - это не реализация, а уничтожение интонации в речи)
Никому это не нравится, голос становится роботизирован
+уши
:cl:
del: Реверт изменения голоса при шёпоте (плохая реализация в Силеро)
/:cl:
=> Revert: TTS whisper

_maps/map_files220/cyberiad/cyberiad.dmm, _maps/map_files220/delta/delta.dmm
- Добавляем Пет-вендинг в дормитории на места дубликатов автоматов со снеками.
- Убираем непонятную отсылку на коробке и замещаем её на моржа, придавая ему солидный вид.
- Добавляем медаль хорошему мальчику
Наконец-то можно готовить рыбу, не боясь потерять всё.
Да?
:cl:
add: Добавлены пет-вендинги в дормитории
del: Непонятная отсылка у моржа
add: Медаль хорошему мальчику
/:cl:
=> [MAP] Добавляем пет-вендинг

modular_ss220/title_screen/code/new_player.dm
Лобби скрин теперь подгружается вовремя(наверное)
Не надо каждый раз жать FIX LOBBY SCREEN
Запустил и сразу зашел - всё есть
:cl:
fix: Лобби скрин теперь подгружается вовремя(наверное)
/:cl:
=> fix: show title properly, on `new_player` init

modular_ss220/title_screen/code/new_player.dm
Quickfix для отображения лобби скрина
Quickfix для отображения лобби скрина
:cl:
fix: Quickfix для отображения лобби скрина
/:cl:
=> costil: adds `show_title_screen` to new_player/Login(), as well as to new_player/Initialize()

code/modules/library/book.dm
Контент книг на кириллице отображается корректно
fixes #475
Контент книг на кириллице отображается корректно вместо кракозябр - это теперь можно читать
Зашел в игру, написал в книгу русскоязычный текст - всё читается
:cl:
fix: Текст кириллицей отображется корректно в книгах
/:cl:
=> fix: book charset

_maps/map_files220/cyberiad/cyberiad.dmm
- Исправляет подключение power monitor'а к сети на мостике
- Добавляет защитную стеклянную дверь к воронке в камеру испытания токсинов
- Исправляет неверные значения у stacking machine
- Правильная киса в техах
- Исправляет наложение кнопки на стойке РНД
Меньше багов и недоработок
Trust me bro
:cl:
fix: Кибериада: Исправление подключения power monitor'а к сети на мостике
fix: Кибериада: Добавил защитную стеклянную дверь к воронке в камеру испытания токсинов
fix: Кибериада: Исправлена работа stacking machine
fix: Кибериада: Исправлен тип кисы в техах карго
fix: Кибериада: Исправлено наложение кнопки на стойке РНД
/:cl:
=> Fix: Cyberiad pack of fixes

modular_ss220/text_to_speech/code/tts_subsystem.dm
Актуализирует кор ТТСа в соответствии с коммитами
https://github.com/ss220-space/Paradise/commits?author=Bizzonium
Хорошо для отладки и, возможно, работы ТТС
Нет возможности
:cl:
tweak: Изменения ТТС
/:cl:
=> Tweak: TTS core actualization

_maps/map_files220/RandomRuins/SpaceRuins/infected_ship.dmm, _maps/map_files220/RandomRuins/SpaceRuins/spacehotel.dmm, _maps/map_files220/RandomZLevels/caves.dmm, _maps/map_files220/RandomZLevels/gate_lizard.dmm, _maps/map_files220/cyberiad/cyberiad.dmm, _maps/map_files220/delta/delta.dmm, modular_ss220/maps220/code/directions.dm, tools/UpdatePaths/Scripts/ss220/vars_to_subtypes.txt
Добавляет подтипы направления для АПЦшек руин.
Плюс дополняет ими скрипт и применяет его же.
Closes #331 
Nope
Nope
=> Tweak: APC subtypes

modular_ss220/cinematics/code/cinematics/credits.dm, modular_ss220/credits/code/SScredits.dm
Избавляемся от пустой "в роли" строке в списке актеров.
Чиним не полное отображение списка мертвых.
Делаем все подзаголовки титров хедерами
Починил генерацию названия эпизода с пустым словом
Теперь титры не отключают ООС
проверил с нюкой, без нюки, с большим списком экипажа, с большим списком мертвецов
:cl:
tweak: Теперь все подзаголовки - хедеры
tweak: Теперь титры не отключают ООС
fix: Теперь часть "В память о" всегда помещается в титры
/:cl:
=> fix: Credits

code/modules/mob/living/silicon/robot/robot_examine.dm, modular_ss220/modular_ss220.dme, modular_ss220/silicon_hats/_silicon_hats.dm, modular_ss220/silicon_hats/_silicon_hats.dme, modular_ss220/silicon_hats/code/silicon_hats.dm, modular_ss220/silicon_hats/code/silicon_interactions.dm
Порт моего старого ПРа: https://github.com/ss220-space/Paradise/pull/1318
На силиконов теперь можно надеть шапки.
Изменения:
- У каждого силикона и модуля имеются свои оффсеты и правила
- Хуманизированные борги могут носить шлема
- Хуманизированные борги с встроенными шляпами - не могут носить шляпы.
- Головной убор надевается в слот головы
- HELP-intent с шляпой в руке - надевает её на силикона.
- GRAB-intent с пустой рукой - снимает с силикона шляпу.
- ГИБ и деконструкт - роняет головной убор
- Смена модуля - изменяет ОФФсет под текущий модуль
- Готовые борги с модулями (синди, дезсквад, дестроеры) сразу имеют нужные оффсеты и правила.
- Дроны могут носить головной убор
- ИИ может носить не-шлемовые головные уборы
- Новые силиконы сразу корректно инициализируются, из-за чего можно …
=> [PORT FEAT] Borg Hats

_maps/map_files220/RandomZLevels/blackmarketpackers.dmm
В оригинальном гейте BMP стены НЕ ломаются (там и так шорткаты есть). У нас теперь тоже. 
Убрал уродливые уголки у двигателей.
Поменял слои у бластдоров, теперь отображаются поверх шлюзов.
Возвращаемся к предкам.
Локалка
:cl:
fix: В гейте BMP теперь неразрушаемые стены (как и в оригинале). Бластдоры теперь адекватно отображаются поверх шлюзов.
/:cl:
=> стенки и бластдоры

_maps/map_files220/RandomZLevels/caves.dmm, _maps/map_files220/cyberiad/cyberiad.dmm, _maps/map_files220/delta/delta.dmm, modular_ss220/gateway/code/exile.dm, modular_ss220/objects/code/miscellaneous.dm
- Возвращает Exile имплант
- Фиксит иконку архив и в его в целом, возвращая вырезанную структуру
:cl:
fix: Возвращен Exile имплант после мержа с оффами
fix: Пофикшена иконка архивов
/:cl:
=> Tweak: Return exile implant, fix archive icon

code/game/gamemodes/traitor/traitor.dm
Что этот PR делает
Снижает скейлинг триторов
:cl:
tweak: 1 трейтор на 10 игроков максимум
/:cl:
=> fix: 1 traitor per 10 players

_maps/map_files220/generic/centcomm.dmm
Порт недостающего с оффов после обновы
- Арена Бубли
- Госткафе (хз зачем, надо будет ХОТЯ БЫ портануть нормальный со Скайрата)
- Магическая мартышка у мага
Устраняем недостаток функционала
Мапдифф
Побегал по госткафе, умным взглядом поглядел на арену
:cl:
tweak: Актуализация Центком уровня после обновы с оффами
/:cl:
=> Feat: Centcom level actualization

_maps/map_files220/RandomZLevels/blackmarketpackers.dmm
Убрал слаги с гейта BMP, заменил их на бакшоты.
Скажем слагам нет
Локалка
:cl:
tweak: В гейте BMP были слаги. Теперь их нет. Зато есть бакшоты. 
/:cl:
=> Tweak: BMP slag remove

modular_ss220/aesthetics/chairs/code/chairs.dm
- Исправляет вырвиглазные цвета, немного (jokerge) десатурируя их
- Исправляет отсутствие armrest у comfy/corp
Хорошо, когда кресло не выбивается цветом из общей картины
Посмотрел в игре
:cl:
tweak: Поменял цвет кресел, чтобы не выбивались вырвиглазным цветом
fix: Вернул armrest у chair/comfy/corp
/:cl:
=> Tweak: Recolor comfy chairs, fix corp armrest

modular_ss220/balance/code/items/projectiles.dm
Теперь, чтобы попасть по лежачей цели нужно:
- Либо накликать на куклу
- Либо быть не в режиме помощи (хелп): дизарм, граб или харм позволят снаряду попадать по лежачим на своей траектории
Также, теперь отраженные снаряды всегда попадают в лежачих.
Легче накликать по лежачим, блоб не контрится лежачими АЕГовцами
Пострелял с риота по скреллам, пострелял в себя с рефлекторного блоба
:cl:
add: Если вы не в режиме помощи, то снаряды теперь попадают в лежачих на своей траектории
add: Отраженные снаряды теперь попадают в лежачих
/:cl:
=> Смена логики попаданий снарядов по лежачим

modular_ss220/mecha_skins/code/paintkit_install.dm
Переписал 1 строчку в проке для правильного отображения текстур. КЛЯНУСЬ ОНО РАБОТАЕТ ИДЕАЛЬНО
баги плоха
Запустил игру, она запустилась, выдохнул и выключил компьютер от греха подальше.
=> FIX(again): Paintkit

_maps/map_files220/delta/delta.dmm
Убрал шкафы на замках из комнаты улик, добавил два зарядника в оружейку
Возможно.
ноуп
:cl:
add: Дельта: в оружейной добавлено два зарядника для оружия.
fix: Дельта: в комнате для улик в бриге теперь простые шкафы.
/:cl:
=> Fix: Delta brig evidence closet and chargers

_maps/map_files220/cyberiad/cyberiad.dmm, _maps/map_files220/delta/delta.dmm, _maps/map_files220/generic/Lavaland.dmm
Добавил общий командный доступ к доступу КМа в его офис дабы туда не могли попасть шахтеры/каргонцы.
Ну, офис главы это офис главы.
Ноуп
:cl:
fix: В офис КМа более не могут попасть каргонцы и шахтеры.
/:cl:
=> Fix: QM office access

modular_ss220/wire_splicing/wiresplicing.dm
* Немного рефактора кода
* Фикс обновления иконки при `reinforce()`
* Теперь показывает прогресс бар
* Теперь при ходьбе уменьшается шанс от удара током
Чуть лучше код
Можно законтрить без изолек
Trust me bro
:cl:
tweak: Через оголенные провода меньше шанс удара током при ходьбе
fix: Фиксы у оголенной проводки для прогресс бара и иконки 
/:cl:
=> Оголенная проводка 2: Теперь немного лучше

modular_ss220/aesthetics/boxes/code/boxes.dm
wizard/hardsuit icon state correction
У коробки был неверный айкон стейт. Теперь будет верным.
Магическая коробка будет не настолько магической и маглы смогут её видеть.
:cl:
fix: wizard box icon
/:cl:
=> fix: wizard box icon

code/game/verbs/ooc.dm, code/modules/client/preference/preferences.dm
Меняем требуемый флаг R_ADMIN на R_EVENT.
Модульно префы и ООС сделать не получится
Запрос Муниверса
:cl:
tweak: для смены цвета ника в ООС требуется R_EVENT
/:cl:
=> tweak: Поменял требуемый флаг для смены ника

_maps/map_files220/generic/Admin_Zone.dmm, _maps/map_files220/generic/centcomm.dmm, modular_ss220/aesthetics_sounds/code/items.dm
Кажется из-за ошибки или устаревшего названия в моде aesthetics_sounds появился дубликат обычного ножа - knife/carrotshiv, но не со звуками ножа, упоминается он только там. Удалил и в мапах заменил обычным ножом
Удаление дубликата предмета с неправильными звуками
:cl:
del: Carrotshiv remove
/:cl:
=> Carrotshiv remove

_maps/map_files220/delta/delta.dmm
Добавляет душики в буферную зону СМа для смыва радиации с куклы и предметов
Избавления от радиации
Повключал душики, работает
:cl:
tweak: Добавил душики в буфер СМа
/:cl:
=> Delta-Shower-SM

_maps/map_files220/cyberiad/cyberiad.dmm
Немного изменяет позиции оголённых проводов (вытащил из под плиток, убрал однотайловые ловушки, нагромождение в одном месте)
Оголённая проводка не должна быть убийцей всего и вся, особенно если её не видно
:cl:
tweak: Кибериада: Позиции оголённых проводов изменены, а также местами вытащена из под плитки
/:cl:
=> Tweak: Cyberiad wire splice positions

modular_ss220/whitelist/code/wl_admin.dm
Сейчас при выдаче админки игра решает прайм это или не прайм значением reroute_cap, которое также отвечает за кап игроков на сервере, нереально отвратительный фикс но сейчас есть более приоритетные задачи.
:cl:
fix: Админы мейна не получают админку на мейне
/:cl:
=> fix: Быстрый фикс разделения админов прайма и мейна

modular_ss220/queue/code/new_player_procs.dm
Добавляем в ссылку byond что бы он закрывал текущий клиент
=> fix: byond redirect

modular_ss220/queue/code/new_player_procs.dm
Reverts ss220club/Paradise-SS220#662
=> Revert "fix: byond redirect" (как оказалось протокол указывался вместе с ссылкой в конфиге)

_maps/map_files220/cyberiad/cyberiad.dmm
Фикс сломанной фляги детектива на Кибериаде. Теперь в ней спавнится 30 юнитов виски и в неё можно заливать химикаты
Детектив снова может пить
Запустил локалку и проверил
:cl:Romains
fix: Починил флягу детектива на Кибериаде
/:cl:
=> Fix: Detective's Flask

tools/changelog/check_changelog.py
Пытаемся починить чейнжлог
:cl:
fix: замена устарвешей функции
/:cl:
=> fix deprecated error in check_changelog

config/example/config.toml, modular_ss220/queue/_queue.dme, modular_ss220/queue/code/new_player_procs.dm, modular_ss220/queue/code/overflow_configuration.dm
Снижаем стандартное время резервации слота на сервере для вышедшего игрока до 10 секунд(Уже на сервере поставлю 1 минуту наверное)
:cl:
tweak: Выносим переменную в конфиг
/:cl:
=> refactor: slot preservation time to config

code/game/objects/items/weapons/kitchen.dm, code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm, code/modules/food_and_drinks/kitchen_machinery/grill_new.dm, code/modules/food_and_drinks/kitchen_machinery/oven_new.dm, code/modules/food_and_drinks/kitchen_machinery/processor.dm
Перевод некоторых кухонных устройств и предметов.
:cl:
add: Перевод некоторых кухонных устройств и предметов.
/:cl:
=> Some kitchen equipment translation.

_maps/map_files220/cyberiad/cyberiad.dmm
Убирает интеркомы под машинерией (хз как оно вообще там оказалось)
:cl:
fix: Кибериада: Убраны лишние интеркомы в тюряге, который оказались под машинерией таймера
/:cl:
=> Fix: Cyberiad intercoms in cell missplaced

config/example/config.toml, modular_ss220/donor/code/client_procs.dm, modular_ss220/loadout/_loadout.dme, modular_ss220/loadout/code/donor.dm, modular_ss220/loadout/code/donor_items.dm
Обновление для донатеров, подробнее читать в бусти
:cl:
add: Добавлены новые предметвы для сабов бусти
tweak: Сабы бусти получают больше очков
tweak: Сабы бусти получают больше слотов персонажей
tweak: теперь стандартное количество слотов персонажей уменьшено до трех
/:cl:
=> add: Loadout donators update

modular_ss220/jobs/code/cards_ids.dm, modular_ss220/jobs/code/job/engineering_jobs.dm, modular_ss220/jobs/code/job/medical_jobs.dm, modular_ss220/jobs/code/job/science_jobs.dm, modular_ss220/jobs/code/job/security_jobs.dm, modular_ss220/jobs/code/jobs.dm
Консоль ГП теперь может навешивать работающую иконку новичковой роли и перекрашивать карту.
Модульность позволяет потенциально работать с этим и в будущем.
Да. Хорошо. Нужно больше набранных паровозиков кадетиков, а не то что мы сейчас видели, где ГП извращались с названиями. А ведь офицеры видят кадета-не-кадета, высказывают к ним требования как к офицерам и бедные кадетики перегружают свои головы и умирают задохнувшись от поступившей информации! Убережем кадетиков!
Да кому нужны эти тестирования когда есть такие прекрасные скриншоты. КОгда мы уже объединим эти 2 пункта.
Навешиваем роль, проверяем иконку:
:cl:
tweak: В консоли ГП теперь можно выдавать новичковые роли + перерисовывать их карты.
/:cl:
=> FEAT: Роли новичков добавлены в консоль ГП

modular_ss220/jobs/code/cards_ids.dm, modular_ss220/jobs/code/job/engineering_jobs.dm, modular_ss220/jobs/code/job/medical_jobs.dm, modular_ss220/jobs/code/job/science_jobs.dm, modular_ss220/jobs/code/job/security_jobs.dm, modular_ss220/jobs/code/jobs.dm
Убираем роли новичков из общего пула даже для педалей
Это альтернативная должность с иконкой. Не более. Он не должен быть доп. слотом, т.к. все против этого.
:cl:
fix: Убраны должности новичков из общего пула профессий.
/:cl:
=> FIX: novice positions

_maps/map_files220/delta/delta.dmm
_Исправляет доступы в инженерном отделе на карте Delta_
Использована следующая логика расположения Helper'ов доступа
- General доступ дает свободный проход по отделу
- Constraction дает доступ к гравгену/тесле и тп
- Equipment дает доступ к складу инженерного отдела
- Atmos дает доступ к атмос крылу
- External установлен дополнительно ко всем выходам в космос
- Также добавлено требование к доступу Constraction на кнопки управления Blast Door's камеры теслы/сингулярности.
Доступы в данный момент не работают корректно. 
В боте
Проект не требует дополнительного тестирования в виду малых изменений
:cl:
fix: Дельта: Исправлены доступы в инженерном отделе.
/:cl:
=> Fix: Delta Engineering access

_maps/map_files220/cyberiad/cyberiad.dmm
- Протянуты недостающие трубы в северо-западных техах
- Починена работа переработчика в диспоушале
- Убрана грязюка со стены в техах карго
Меньше багов
:cl:
tweak: Кибериада: Протянуты недостающие трубы в северо-западных техах
fix: Кибериада: Починена работа переработчика в диспоушале
/:cl:
=> Fix: Cyberiad bunch of fixes (disposal, atmos in north-west tunnels)

config/example/config.toml, modular_ss220/text_to_speech/code/configuration.dm, modular_ss220/text_to_speech/code/providers/silero.dm
Выносим ссылку на апи ТТСа в конфиг
:cl:
tweak: Выносим ссылку на апи ТТСа в конфиг
/:cl:
=> tweak: hardcode to config

code/modules/reagents/chemistry/machinery/chem_dispenser.dm, code/modules/reagents/chemistry/machinery/chem_heater.dm, modular_ss220/silicons/code/items/gripper.dm
Разрешает трогать бикеры боргам в остальной химии (половину они и так могли трогать, а 2-х других машинерий увы).
Буквально копипастит код который был в наследнике, только на этот раз с разрешением для борга.
Помимо этого карго борги теперь могут полноценно брать диски исследований как и каргонцы.
Борги снова могут заглянуть в морг и убирать туда трупы.
А то бикеры есть, а химии набрать гадости нет.
Люди больше не будут жаловаться.
:cl:
fix: Медборги могут взаимодействовать с химическим оборудованием
feat: Сервис/Карго борги могут брать диски для исследований.
feat: Борги снова могут заглянуть в морг 
/:cl:
=> [FIX] Разрешаем грипперам медборгов трогать химию.

code/game/objects/buckling.dm
Позволяет баклиться в радиусе 1 тайла от цели.
Больше месяца висит ПР на оффах, конфликтов нет, думаю можно залить и ждать пока у оффов дойдут руки.
https://github.com/ParadiseSS13/Paradise/pull/22828
Удобно
:cl:
tweak: Можно снова удобно садиться на стулья, достаточно перетащить куклу на него, стоя в упор к нему а не на нём.
/:cl:
=> Nearby Buckle

modular_ss220/agent_id_tgui/code/agent_id_tgui.dm, modular_ss220/clothing/code/shoes.dm, modular_ss220/detective_rework/code/swabs.dm, modular_ss220/maps220/code/misc.dm, modular_ss220/objects/code/card_skins.dm, modular_ss220/text_to_speech/code/tts_seed.dm
Переносит наши списки на ТГУИ.
ТГУИ - красиво.
На пол шишечки.
:cl:
tweak: Админские проки "change_voice" и "select_voice" теперь с поиском и TGUI
/:cl:
=> Convert input lists to tgui

code/game/gamemodes/game_mode.dm, config/example/config.toml, modular_ss220/_misc/_misc.dme, modular_ss220/_misc/code/discord_configuration.dm
Переносим роль которую должен пинговать сервер в конце раунда в конфиг
:cl:
fix: Теперь каждый сервер будет пинговать своих ждунов
/:cl:
=> fix: role to ping for new round to config

modular_ss220/modular_ss220.dme, modular_ss220/verbs/_verbs.dm, modular_ss220/verbs/_verbs.dme, modular_ss220/verbs/code/verbs.dm
- Возвращает кнопку Respawn
- Создаёт отдельный модуль "Verbs" на будущее, если вдруг пригодится вернуть что-то ещё (впрочем, сомневаюсь),
или добавить своё
У игроков появляется опция респавна
Ма бой
:cl:
tweak: Возвращена кнопка Respawn в OOC
/:cl:
=> Feat: Respawn return

_maps/map_files220/cyberiad/cyberiad.dmm
- Замена wall recharger на настольный recharger на столе в бриге
- Перестановка кнопок на КПП пермабрига
- Покраска парочки дверей в пермабриге
Меньше раздражающих моментов
Мапдифф
В игре глядел
:cl:
tweak: Кибериада: Настенная зарядка в бриге на столе заменена на настольную зарядку, перестановка кнопок на КПП пермабрига, покрашены парочка дверей в пермабриге
/:cl:
=> Tweak: Cyberiad brig tweaks

modular_ss220/maps220/code/mobs.dm, modular_ss220/maps220/code/objects.dm
Убрал /xen мобов из экстрактов. Оставил буллсквидов, песиков и вортигеров. 
Произошла чудовищная ошибка.
Нету.
Локалка.
:cl:
fix: Из золотых экстрактов теперь можно получить враждебных буллсквидов, песиков и вортигеров.
/:cl:
=> Fix:remove xen_mobs from golden extract

modular_ss220/devices/code/items/radio.dm
Больше нельзя включать рацию где не положено
Посмотрел в игре
:cl:
fix: Больше нельзя включать рацию там, где не положено
/:cl:
=> Fix: Radio exploit

code/game/machinery/vendors/generic_vendors.dm
Убирает плюсики из слогана Робаст Софтдринкса
Автомат больше не говорит "РобПЛЮСаст сПЛЮСофтдринкс"
Не тестировал
:cl: Romains
fix: Убраны плюсики из слогана Робаст Софтдринкса
/:cl:
=> Fix: Remove Those Pluses

_maps/map_files220/cyberiad/cyberiad.dmm
- Добавил 2 лопатки в ассистушный сад Кибериады
- Немного подвигал объекты
Запрос от рандома, показалось логичным
trust me bro)
:cl:
tweak: Кибериада: В ассистентский сад добавлены 2 лопатки и чуть подвигал объекты 
/:cl:
=> Tweak: Cyberiad garden

code/modules/newscaster/obj/newspaper.dm
Чинит кириллицу в газетах
Потому что
:cl:
fix: Газеты теперь корректно отображают кириллицу
/:cl:
=> Fix: Newspaper text

modular_ss220/discord_link/code/discord.dm
- Добавлена прямая ссылка на канал
- Изменено название канала в соответствии с изменениям в ДСе
Меньше конфуза
:cl:
tweak: Изменено название канала отображаемое при привязка ДСа, а также добавлена прямая ссылка на канал
/:cl:
=> Tweak: Change channel name for discord authorization

modular_ss220/awaymission_gun/code/items/awaymission_gun.dm
Заново создана на основе https://github.com/ss220club/Paradise-SS220/pull/597/files
Полностью фиксит гейтган мк1 и мк2:
- Переработано описание гейтганов на более короткое и понятное
- Убрана лазейка, позволяющая апгрейднуть технологии с 5 до 6 тупо из протолата
- Убрана возможность емага. ЭМИ так же теперь не емагает пушку.
- Убрана приписка force = 10, ибо она и так наследуется.
- Убрана возможность зарядки мк2 в бою, не давая более анлимит боеприпасов. Переработано потребление хавки при зарядке.
Безлимит пушки на станции забесплатно в рнд - плохо, супер плохо. Безлимит пушка в гейте так же ломает баланс гейтов, превращая их в тир. Слишком малое потребление хавки совершенно не влияет, даже не стимулируя брать еду. Зарядка мк2 все еще дает супер скорую зарядку пушки, но теперь …
=> FIX: Gategun

_maps/map_files220/generic/Lavaland.dmm
Чиню линтер
Я ебланчик
:cl:
fix: Двери офиса КМа на шахтёрском аванпосте теперь стеклянные и затемняются
/:cl:
=> Fix: Outpost QM's office door to glass type

_maps/map_files220/delta/delta.dmm
Ноутбук у магистрата и в суде направлен вниз
Исправлен доступ в спальне дормов (был одинаковый на обеих)
Исправления, очевидно
Не требуется
:cl:
tweak: Ноутбук в суде и офисе магистрата теперь направлен вниз
fix: ID шлюза спальни теперь работает правильно
/:cl:
=> Fix: Delta mini fixes

modular_ss220/text_to_speech/code/seeds/silero.dm
Я не заметил что имя голоса у нарратора из Шрека и нарратора из варкрафта совпадает.
:cl:
fix: Чиню то что голос рассказчика из Шрека заменялся голосом рассказчика из варкрафта
/:cl:
=> fix: shrek narrator name collision

modular_ss220/balance/_balance.dme, modular_ss220/balance/code/species/machine.dm, modular_ss220/balance/code/species/nucleation.dm
_Я хоть нормальную папку выбрал под модуль?_
"Затрагивает" баланс, хотел отослать оффам, но у них нет спрайта коробки для КПБ, увы xdd
- Даёт КПБ собственный набор выживания: 5 мотков провода, 1 сварка, 1 глоустик
- Вырезаем полностью код Нуклеаций из модуля, так как в билде их больше нет
Closes https://github.com/ss220club/Paradise-SS220/issues/657
Больше не даём коробки выживания с хер пойми чем для машины
:cl:
tweak: КПБ добавлены собственные коробки выживания с сваркой, проводами и глоустиком
/:cl:
=> Tweak: Give IPC's they own survival box

_maps/map_files220/delta/delta.dmm
Немного изменил зону прибытия Гамма шаттла (дабы одна дверь была закрыта стеной, и в целом чтобы зона выделялась), пофиксил прибытие Гамма шаттла (отсутствовала зона).
Меньше багов
:cl:
fix: Дельта: Пофиксил прибытие Гамма шаттла, немного изменена его зона прибытия
/:cl:
=> Fix: Delta Gamma shuttle arrival

_maps/map_files220/delta/delta.dmm
Исправление проводки в рамках брига.
Подключена переодевалка. Поправлена проводка у вардена. Убраны лишние провода. Общая схема содинения приведена к общему стандарту.
Проводка жеж. Важно жеж
Не требуется в виду незаметности изменений на общей картине.
Не требуется
:cl:
fix: Исправление проводки в рамках Брига
/:cl:
=> Fix: Delta/brig minor fix

modular_ss220/mobs/code/simple_animal/hostile/bear.dm
Делает названия медведей с большой буквы, как это сделано со всеми другими мобами в игре
Исправляет пропадание спрайта медведя при движении
Не исправляет ОП урон боевого медведя
Невидимые мобы - плохо
Неверные правила наименования мобов - плохо
Скомпилировал, запустил, побегал
:cl:
fix: Новые медведи больше не становятся невидимыми при движении
spellcheck: Имена новых медведей теперь пишутся с большой буквы
/:cl:
=> Customised Bears no longer invisible

_maps/map_files220/RandomRuins/SpaceRuins/spacehotel.dmm, _maps/map_files220/RandomZLevels/blackmesa.dmm, modular_ss220/maps220/code/Areas/away.dm
Пофиксил телепорт в мезе. Теперь из Зена можно выбраться прямо к гейту.
Пофиксил зону в космическом отеле. На GPS теперь все отображается корректно.
Подбираю за собой.
Локалка, работает
:cl:
fix: В гейте Black Mesa теперь корректно работает телепорт из Зена. Косморуина Space Hotel теперь корректно отображается на GPS.
/:cl:
=> Fix: Black Mesa and Space Hotel

_maps/map_files220/cyberiad/cyberiad.dmm
Увеличим количество сбшных консолей для запросов с 1 до 4. В количестве ориентировался на РНД, где их 5 (ПЯТЬ!). Ими особо никто (вообще никто) не пользуется, так что на баланс это не повлияет.
Ну это логично для СБ иметь такие консоли не только на чекпоинте.
На пикче новые консоли отмечены ядовито-зеленым. Уехали немного выключатели-переключатели, это я отметил стрелками.
В маппинге я особо не бумбум, но консоли вроде работают, кнопки тоже не сломались.
:cl: Maxiemar
tweak: Количество СБшных консолей запросов на Кибериаде увеличено с 1 до 4.
/:cl:
=> Increase the number of Security Requests Consoles from 1 to 4

code/datums/emote.dm, code/datums/status_effects/neutral.dm, code/game/objects/items/hand_item.dm, code/modules/mob/living/brain/brain_emote.dm, code/modules/mob/living/carbon/alien/humanoid/humanoid_emote.dm, code/modules/mob/living/carbon/carbon_emote.dm, code/modules/mob/living/carbon/human/human_emote.dm, code/modules/mob/living/living_emote.dm, code/modules/mob/living/silicon/silicon_emote.dm, code/modules/mob/living/simple_animal/friendly/friendly_emote.dm, code/modules/mob/living/simple_animal/hostile/gorilla/gorilla_emote.dm, code/modules/mob/living/simple_animal/slime/slime_emote.dm, code/modules/mob/mob_emote.dm
Переносим перевод эмоций из модуля в `translate`. Надо смержить прям вместе с #951. Синхронизация с #938 также рекомендуется.
Чистим чистим чистим.
Важно верить в хорошее.
:cl: Maxiemar
tweak: Дальнейший перевод эмоций, включая рукопожатия и пощечины.
/:cl:
=> Add emote translations to [translate]

code/modules/research/server.dm
Меняем кодировку в окне на UTF-8 для отображения кириллицы.
Кириллица теперь читабельна.
:cl: Maxiemar
fix: Исправлена кодировка в консоли управления сервером РНД.
/:cl:
=> Fix encoding in R&D server controller

modular_ss220/text_to_speech/code/tts_seed.dm, modular_ss220/text_to_speech/code/tts_subsystem.dm
closes #961 
Исправляет баг с невозможностью за борга выбрать голос.
Добавляет боргам `tgui_input_list` для выбора голосов.
Борги снова могут выбрать голос, так еще и с ТГУИ
Запустил игру, попробовал сменить голос. Всё корректно работает, рантаймов нет.
:cl:
tweak: Добавляет боргам удобный список с поиском для выбора голосов
fix: Исправляет баг с невозможностью за борга выбрать голос
/:cl:
=> fix: make choosing voice by borg possible again

modular_ss220/loc_blurb/_loc_blurb.dm, modular_ss220/loc_blurb/_loc_blurb.dme, modular_ss220/loc_blurb/code/location_blurb.dm, modular_ss220/loc_blurb/loc_blurb.dme, modular_ss220/modular_ss220.dme
Добавил прикольный текст при спавне куклы + оповещение о ребуте сервера. 
:cl:
add: Добавлен текст при спавне персонажа, добавлен текст при ручном перезапуске сервера.
/:cl:
=> RSCADD: Roundstart blurb 

modular_ss220/text_to_speech/code/base_seeds/objs/objs.dm, modular_ss220/text_to_speech/code/tts_seed.dm
Для всех выборов голоса, кроме ЕРТ использует ТГУИ список.
Пул доступных голосов определяется гендером обьекта, которому меняют голос, а не гендером того кто меняет.
Исправлен баг.
Красивые списки с поиском хорошо.
В игре посмотрите:)
Скомпилировал, проверил.
:cl:
tweak: Для всех случаев смены голоса используются `tgui_input_list` (красивые списки с поиском), кроме ЕРТ
fix: Пул доступных для куклы голосов, определяется гендером куклы
/:cl:
=> refactor: make voice selection with TGUI input list for all cases, except ERT, define gender by atom's gender, not users

code/game/objects/items/devices/painter/floor_painter.dm, modular_ss220/aesthetics/floors/code/floors.dm
Покрасчик полов теперь имеет спрайты наших полов, плюс несколько новых
Красить люблю пиздец
Ага
:cl:
fix: Painter в режиме покраски полов, теперь имеет спрайты наших полов.
tweak: Также добавлено несколько новых расцветок полов туда же.
/:cl:
=> Floor Painter Tweaks

_maps/map_files220/cyberiad/cyberiad.dmm
Убирает 1000 кредитов в техах Кибериады
1. Оффы снизили кол-во кредитов на карте еще давно
2. Столько кэша лежит только в хранилище кэпа
3. Это огромный бафф для того кто это найдет (например карго, или сб)
Ни за что в жизни
:cl:
tweak: Кибериада: Изменено кол-во кредитов в одной из комнат в техах с 1000 до 200
/:cl:
=> Tweak: Debuff cash in Cyberiad maints

_maps/map_files220/delta/delta.dmm
Добавлено хранилище импланта изгнания на Дельту в комнату экспедиции
Рабочий механ
Не тестировал
:cl:
add: Дельта: Добавлено хранилище импланта изгнания в комнату экспедиции
/:cl:
=> Add: Exile storage on Delta

modular_ss220/verbs/code/verbs.dm
Пофиксил свою логику в респавн вербе (НАДЕЮСЬ)
Нема багулин
Нет
Не тестировал
:cl:
fix: Теперь логика кнопки Respawn работает корректно
spellcheck: Исправлено сообщение при нажатии на кнопку Respawn
/:cl:
=> Fix: Respawn verb logic

_maps/map_files220/MetaStation/MetaStation.dmm, _maps/map_files220/cyberiad/cyberiad.dmm, _maps/map_files220/delta/delta.dmm, _maps/map_files220/generic/Lavaland.dmm, tools/UpdatePaths/Scripts/ss220/1002_airlock_names_to_autoname.txt
ВСЕ аирлоки теперь с Autoname хелперами, в купе с переводами зон, это упростит навигацию, особенно для новичков.
Удобство
Trust me BRO
TestMerge Clueless
:cl:
tweak: Аирлоки теперь должны быть на русском, навигация упрощена
/:cl:
=> Tweak: Transfer Airlock names to Autoname helpers

code/modules/point/point.dm
Слегка увеличил анимацию Point to (Почти в 2 раза)
Легче увидеть куда показывают
https://github.com/ss220club/Paradise-SS220/assets/69762909/451e2f07-589e-4d42-b7d7-d079e7cd6f73
:cl:
tweak: Анимация стрелочки при указании (СКМ) теперь немного дольше
/:cl:
=> Longer pointer animation

_maps/map_files220/MetaStation/MetaStation.dmm, _maps/map_files220/cyberiad/cyberiad.dmm, _maps/map_files220/delta/delta.dmm, _maps/map_files220/generic/Lavaland.dmm, modular_ss220/balance/_balance.dme, modular_ss220/balance/code/access/access.dm
Чиним доступы после отказа от minimal_access
Я уже не знаю
Попытка в небольшое разделение внутри отделов
Дифф бот + скачать ветку
Ноуп
:cl:
tweak: Изменение доступов на всех картах. В целом всё +- как и было, за исключением того что Щит теперь имеет доступ к кабинетам глав, в противовес этому, слегка обрезаны доступы у обычного врача. Подробнее в дискорде в канале #инфо-по-картам - https://discord.com/channels/1097181193939730453/1097543419586428989/1208757057927385089 
В ветку туда же негодования, или галочку если всё в целом устраивает
/:cl:
=> Map Access fix

_maps/map_files220/MetaStation/MetaStation.dmm, _maps/map_files220/cyberiad/cyberiad.dmm, _maps/map_files220/delta/delta.dmm
Удаляет жукбоксы с станционных карт
Возможно общая производительность станет выше
:cl:
del: Со всех станционных карт, были убраны музыкальные автоматы
/:cl:
=> Remove Jukeboxes from maps

modular_ss220/discord_link/code/discord.dm
Более читаемая инструкция по привязке дискорда, и предупреждение о том, что аккаунт не привязан
Меньше вопросов, больше удобства?
Ага
:cl:
tweak: Инструкция по привязке дискорда теперь более читаемая и подробная.
/:cl:
=> Better Discord linking

_maps/map_files220/MetaStation/MetaStation.dmm
Фиксит 3 вещи на метастейшене:
- У коридора в медбее теперь есть воздушная сигнализация
- К офису священника теперь проложен провод
- Воздушная сигнализация в серверной РнД больше не будет давать тревогу от того, что в серверной холодно
Меньше багов
Я верю в свои силы
:cl:
fix: Цереброн: Коридор медбея имеет воздушную сигнализацию
fix: Цереброн: К офису священника проложен провод
fix: Цереброн: Воздушная сигнализация серверной РнД заменена на серверную
/:cl:
=> [Fix] Metastation Fixes

modular_ss220/mobs/_mobs.dme, modular_ss220/mobs/code/mob_holder.dm, modular_ss220/mobs/code/simple_animal/friendly/butterfly.dm, modular_ss220/mobs/code/simple_animal/friendly/lizard.dm, modular_ss220/mobs/code/simple_animal/hostile/bee.dm
Теперь животных в руке можно будет в `harm` интенте съесть, как обычную еду. При этом учитываются предпочтения из `species`. Также будет возможность скормить животное другой кукле аналогичным образом.
Ксеносы истребят всех мышей на станции, слава ксеносам.
https://github.com/ss220club/Paradise-SS220/assets/39908528/8beb2833-4029-42c7-98ad-3c462ccc8133
:cl:
add: Таяры, вульпканины, унатхи и киданы теперь могут съесть некоторых мелких животных.
fix: Исправлены проблемы с невозможностью взять некоторых мелких животных в руку.
fix: Исправлены некоторые проблемы с отображением мелких животных в руке.
/:cl:
=> [TM] Bring animal devouring back

modular_ss220/objects/code/electrostaff.dm
Добавляет возможность парирования электропосохом атак в ближнем бою. Работает только если включен двуручный режим.
Потому что парирование - это круто. И одобрено.
На локалке с товарищем и на мобах.
:cl:
add: Добавлено парирование для электропосоха атак ближнего боя, если он в двух руках.
/:cl:
=> Add parry for electrostaff

_maps/map_files220/cyberiad/cyberiad.dmm
Убирает обычный стол под стеклянным в кабинете вирусолога
Я не думаю, что двойной стол - модно
Я верю в свои силы
:cl:
fix: Кибериада: У вирусолога больше не стоит обычный стол под стеклянным
/:cl:
=> [Fix] Cyberiad Fix

_maps/map_files220/delta/delta.dmm
Видимо, моя трилогия фиксов карт...
Фиксит три проблемы на дельте:
- Обрезанный провод от допросной до "просматриваемой допросной"
- Обрезанный провод с техов до комнат клоуна и мима
- ЛКП в техах над голопадом теперь изначально подключён к общей сети (почему-то лэндмарк повреждённого пола "ломает" соединение провода и терминала ЛКП)
Меньше инженерных тревог из-за ошибок ~~мапперов~~ инженеров НТ, полагаю
Играл на локалке 9 часов
:cl:
fix: Дельта: Обрезанный провод в допросной
fix: Дельта: Обрезанный провод под дверью с техов до комнат клоуна и мима
fix: Дельта: ЛКП в техах над голопадом теперь изначально подключён к сети
/:cl:
=> [Fix] Delta Fixes

modular_ss220/emotes/_emotes.dme, modular_ss220/emotes/code/human_mob.dm
Исправляем ситуацию, когда эмоуты могут не обновиться при изменении расы куклы.
Баги плохо.
Превратил куклу в слайма с помощью экстракта - обновились эмоуты.
:cl: Maxiemar
fix: Вкладка Эмоции теперь обновляется при изменении расы персонажа во время игры.
/:cl:
=> Update verbs on species change

modular_ss220/balance/code/access/access.dm, modular_ss220/jobs/_jobs.dme, modular_ss220/jobs/code/access.dm
Даем робототехнику трогать РНД консоль ученых, ладно. Ну и лишний файлик убираю, и так сейчас все сотрудники отделов могут в техах шастать.
Я не знаю.
Побегал по текущим картам - консоль трогать можно, в техах бегать можно.
:cl: Maxiemar
tweak: Робототехники снова могут пользоваться консолью ученых в РНД.
/:cl:
=> Allow robotics to use the R&D scientists console

interface/skin.dmf
Кнопки справа сверху теперь имеют динамический размер.
Плюс отключён тултип слева снизу
Эстетика
https://github.com/ss220club/Paradise-SS220/assets/69762909/2ccbe018-f961-448f-b8c6-ae6161de47f8
:cl:
tweak: Кнопки справа сверху (Правила, вики и т.д.) теперь имеют динамический размер.
tweak: Тултип слева снизу теперь отключён по-умолчанию
/:cl:
=> tweak: Dynamic skin buttons size

_maps/map_files220/cyberiad/cyberiad.dmm
Читай название
Нахуй надо
:cl:
tweak: Кибериада: Крио в клонёрке и просто крио теперь независимы. Однако я спиздил один клинер и бикер криоксадона :ratge:
/:cl:
=> Cyberiad: Separate cryo canisters

_maps/map_files220/RandomZLevels/blackmesa.dmm, _maps/map_files220/RandomZLevels/gate_lizard.dmm, modular_ss220/maps220/code/floors.dm
Чазмы греют так же из-за planetary_atmos. Сделал подтип с нормальной температурой для гейтов (как будто ожидаются еще)
Чазмы не дуют и не греют.
локалка
:cl:
fix: Я вас обманул и мне не стыдно. Но в этот раз окончательно, чазмы в гейтах black_mesa и gate_lizard не запекают гейтеров. 
/:cl:
=> Fix: awaymission chasm

modular_ss220/maps220/code/floors.dm
Продолжаю работать банщиком. Приводим параметры пола lavaland_air к оффовским значениям. Меньше нагрузки из-за разности в газовом давлении.
Меньше нагрузки.
Локалка.
:cl:
fix: Приводим параметры пола lavaland_air к оффовским значениям.
/:cl:
=> Fix: lavaland_air plasteel floor temperature and air parameters

modular_ss220/hairs/code/vulpkanin_hair.dm
Fixes https://github.com/ss220club/Paradise-SS220/issues/1129
Вульпячие швабры больше не оверрайдят сигма прически хуманов
.l.
Не тестировал
:cl:
fix: Прически вульп больше не заменяют людские, если их имена были одинаковы
/:cl:
=> Fix: Vulpkanin hairs overrides Human hairs

_maps/map_files220/cyberiad/cyberiad.dmm, _maps/map_files220/delta/delta.dmm
Переставляет громоотводы в зоне содержания теслы, чтобы за ее пределами никого не било током.
Better gameplay.
mapdiff
Ни один робот бобот не пострадал
:cl:
tweak: Кибериада/Керберос: громоотводы в зоне содержания теслы были переставлены и теперь обеспечивают безопасность перемещения кого-либо за ее пределами.
/:cl:
=> Tesla containment area safety

_maps/map_files/cyberiad/cyberiad.dmm, _maps/map_files220/RandomRuins/SpaceRuins/whiteship.dmm, _maps/map_files220/cyberiad/cyberiad.dmm, _maps/map_files220/delta/delta.dmm
Поменял размеры порта для медицинского шаттла НТ на Кибериаде. 
Опустил порт на Керберосе на три тайла вниз, что бы не было проблем с телепортацией с границы сектора на шаттл.
Небольшая правка стен шаттла.
Медицинский шаттл НТ снова работает на Кибериаде. Нет проблем с телепортацией с границы сектора прямо на шаттл.
Локалка.
:cl:
fix: Медицинский шаттл НТ снова работает на Кибериаде (надеюсь). Нет проблем с телепортацией с границы сектора прямо на шаттл на Керберосе.
/:cl:
=> Fix: whiteship dock sizes

_maps/map_files220/RandomZLevels/spacebattle.dmm, modular_ss220/maps220/code/Areas/gateway.dm, modular_ss220/maps220/code/mobs.dm
Заменил весь камень на /turf/simulated/mineral, что бы избежать генерации лаваленда.
Поставил недостоющие зоны, апц.
Заменил паверсинк на структуру.
Поднял ХП главгаду.
Скинул процент дропа синди хардсьюта до 1, скинул хп маулеру до 250, поднял хп мобам.
Чуть прибрал за собой.
В раунде.
:cl:
fix: Технические изменения гейта spacebattle.
/:cl:
=> Fix: spacebattle minor fixes

_maps/map_files220/RandomZLevels/wildwest.dmm
Заменил синдикатовских симплов в гейте wildwest. Теперь гарантированно можно выбить 3 cr20, 1 есворд и 1 щит. Остальные симплы роняют рандомный лут как в гейте spacebattle.
Синдикатовские симплы стали чуть жирнее.
Еще по мелочи поменял плитку и пару костюмов в ящиках.
Меньше манча? Возможно.
Локалка.
:cl:
tweak: Понизил шанс получить целый арсенал в гейте wildwest. Теперь можно гарантированно получить  только 3 винтовки, 1 есворд и щит. Остальное - рандом.
/:cl:
=> Tweak: wildwest loot balance

modular_ss220/jobs/code/objects/job_objects.dm
Убрал из списка невидимые предметы, они же подтипы в подтипах
Нет невидимых игрушек
:cl:
fix: В коробке торговца больше не должно быть невидимых вещей
/:cl:
=> fix: Invisible items into SOL trader box

tools/changelog/check_changelog.py, tools/changelog/tags.yml
Чейнджлог чаще попадает в базу/дис.
Я (тестировщик), произвожу тесты воркфлоу на форке 😎 
Но нормально работает вроде.
=> Better changelog validation

modular_ss220/awaymission_gun/code/items/awaymission_gun.dm
Гейт ган можно использовать не только в гейте, но и в космосе, вне станционного уровня
Эксплореры могут защититься в космосе
Да
:cl:
tweak: Exploreverse (Гейт-ган) можно теперь использовать в секторах с космическими руинами.
/:cl:
=> Make Exploreverse elligible to use in Space Ruins levels

modular_ss220/mobs/code/simple_animal/mobs.dm
Более нельзя взять в руки живого хедслага. 
Теперь невозможна ситуация, когда живой хедслаг находится в руках или инвентаре и его не видно из-за отсутствующего спрайта
:cl:
fix: Более нельзя взять в руки живого хедслага. 
/:cl:
=> [FIX] Headslugs cannot be taken in hands

_maps/map_files220/generic/centcomm.dmm
Телепорт в зоне ОБР снова работает (вроде бы)
Работает = хорошо.
Локалка, у меня работает.
:cl:
fix: Починен телепортер в зоне ОБР - доставка отряда с ЦК без посредников и прямиком на мостик.
/:cl:
=> Fix: centcomm teleporter fix

_maps/map_files220/generic/centcomm.dmm
Починил раундстартовых обсёрверов и заодно актуализировал хату мага с оффами
Свежесть и без багов, наверное
Дифф бот
Нет
:cl:
fix: Можно снова гоститься до начала раунда
tweak: Хата мага получила интеркомы синдиката, лаву как на лаваленде, пару новых окон и новый пол. А, ещё на одну из книжных полок положена дополнительная книга
/:cl:
=> Fix roundstart observers and actualize wizard home

_maps/map_files220/generic/Lavaland.dmm, _maps/map_files220/generic/centcomm.dmm, _maps/map_files220/stations/boxstation.dmm, _maps/map_files220/stations/deltastation.dmm, _maps/map_files220/stations/metastation.dmm
Актуализация с картами оффов
https://github.com/ParadiseSS13/Paradise/pull/24037
https://github.com/ParadiseSS13/Paradise/pull/23981
https://github.com/ParadiseSS13/Paradise/pull/24605
https://github.com/ParadiseSS13/Paradise/pull/25352
https://github.com/ParadiseSS13/Paradise/pull/24548
:cl:
tweak: Небольшие изменения шаттла Гулага, а также зоны посадки на Лаваленде.
tweak: Лаваленд: Наружные стены Гулага теперь укрепленные, а также небольшие изменения визуальной составляющей.
tweak: Лаваленд: На вершине скалы Гулага разбилась старая спасательная капсула. В ней находится ящик с инструментами, что делает возможным побег из "Чазмаленда" (Дырявый Лаваленд xdd).
tweak: Кибериада: изменена область вокруг шаттла Гулага, чтобы он перестал открываться во время события "Greytide".
tweak: Все …
=> Actualize stations & Lavaland

_maps/map_files/stations/boxstation.dmm, _maps/map_files/stations/cerestation.dmm, _maps/map_files/stations/deltastation.dmm, _maps/map_files/stations/metastation.dmm, code/__DEFINES/misc_defines.dm, code/datums/mind.dm, code/game/dna/mutations/mutation_powers.dm, code/game/objects/items/devices/radio/intercom.dm, code/game/objects/items/devices/radio/radio_objects.dm, code/modules/projectiles/guns/medbeam.dm, code/modules/research/designs/medical_designs.dm, code/modules/station_goals/secondary/medical/random_bulk_medicine.dm, code/modules/station_goals/secondary/medical/variety_medicine.dm, code/modules/supply/supply_console.dm, code/modules/supply/supply_pack.dm, code/modules/supply/supply_packs/pack_shuttle.dm, code/modules/surgery/organs/augments_arms.dm
:cl: ParadiseSS13
add: Добавлен абдукторский тулсет
tweak: Медицинский луч тепреь имеет шанс вылечить все внутренние повреждения
fix: Прыжок больше не должен впечатывать вас в стену, буквально
/:cl:
=> Merge Upstream 21.05.2024

_maps/map_files220/stations/boxstation.dmm, _maps/map_files220/stations/deltastation.dmm
Добавлены недостающие disaster counter'ы на карты... Даже оффы забыли добавить некоторые на свои же карты, лол........
:cl:
add: На карты добавлены недостающие disaster counter'ы (монитор кол-ва смен прошедших без происшествий в определенных отделах)
/:cl:
=> Add: Missed disaster counters

_maps/map_files220/stations/boxstation.dmm
Добавил недостающую камеру в комнату экспедиторов, сменил им раскраску двери в техи, в крысу удалил лишнюю аиралярму в комнате хопа
:cl:
fix: Кибериада: Добавлена недостающая камера в комнате экспедиторов, покрашены двери в техи, удалена лишняя аир-алярма в комнате ХоПа.
/:cl:
=> Fix expedition room lack of camera

_maps/map_files220/stations/boxstation.dmm, _maps/map_files220/stations/deltastation.dmm, _maps/map_files220/stations/metastation.dmm
После мержа апстрима, подтянул [обнову](https://github.com/ParadiseSS13/Paradise/pull/25449) на карты, которая добавляет лобби в РнД.
:cl:
tweak: Все карты: Добавлена зона фойе РнД, дабы алярмы не так сильно выносили мозги, а инженерам было немного удобнее
/:cl:
=> Add: RnD lobby areas

modular_ss220/sm_space_drop/code/sm_drop_button.dm
Closes https://github.com/ss220club/Paradise-SS220/issues/1221
Убирает возможность у ИИ взаимодействовать с кнопкой сброса СМ
ИИ не должен иметь возможность силой мысли разбивать стёкла и нажимать кнопку ручного (я только что сам выдумал) сброса
:cl:
tweak: ИИ больше не может взаимодействовать с кнопкой сброса СМ
/:cl:
=> Tweak: No AI interaction with SM Drop Button

_maps/map_files220/generic/centcomm.dmm, _maps/map_files220/shuttles/ferry_clown.dmm, _maps/map_files220/shuttles/ferry_convoy.dmm, _maps/map_files220/shuttles/ferry_medical.dmm, _maps/map_files220/shuttles/ferry_tsf.dmm, _maps/map_files220/shuttles/ferry_ussp.dmm, _maps/map_files220/shuttles/ferry_vip.dmm, modular_ss220/shuttles/_shuttles.dme, modular_ss220/shuttles/code/ferry_shuttles.dm
- Добавлено 6 новых ферри шаттлов для щитспавна админами
1. ТСФ
2. СССП
3. Клоунский
4. Медицинский
5. Для конвоирования
6. Для VIP-персон
- В зоне кастом щитспавна убраны любые упоминания о ЦК, а также кринж флаги
Теперь у админов появилась полноценная щитспавн зона для осуществления большинства задумок с фракциями
Смотри мапдифф
:cl:
add: Для щитспавна админами добавлено 6 новых ферри шаттлов (ТСФ, СССП, клоунский, медицинский, для конвоирования и для VIP-персон)
tweak: Центком: В кастомной зоне щитспавна убраны любые упоминания НТ, а также флаги
/:cl:
=> Add: New Ferry shuttles

_maps/map_files220/RandomZLevels/caves.dmm, _maps/map_files220/generic/Lavaland.dmm, modular_ss220/maps220/code/RandomRuins/lavaland/lavaland_turfs.dm
- Доисправляет то, что проебал (и то что проебали оффы :GAGAGA:)
- Исправляет модульные лаваленд-эир турфы
:cl:
fix: Исправил активные тайлы атмоса на наших руинах Лаваленда
tweak: В гейте Caves теперь тоже учтен новый атмос
/:cl:
=> Fix lavaland_air turfs, fix missed

_maps/map_files220/stations/boxstation.dmm
- Улучшил общий визуал и поправил симметрию
- Переложил раскраску плиток
- Некоторые исправления отсутствующей машинерии
- Перемещена заброшенная парикмахерская в более подходящее место - в техи к клоуну.
Приятно глазам
**Самые актуальные изменения в MapDiff**
Смотрел в игре
:cl:
tweak: Кибериада: Улучшена визуальная составляющей дорм (переложена плитка, исправлена симметрия), добавлена отсутствующая машинерия и перемещена заброшенная парикмахерская в более подходящее место - в техи к клоуну.
/:cl:
=> Update Cyberiad dorms visual

modular_ss220/_defines220/code/emote.dm, modular_ss220/emotes/code/emote_names.dm, modular_ss220/emotes/code/emote_verbs.dm
Добавил «камень-ножницы-бумага» в эмоут панель
Можно играть в «камень-ножницы-бумага»
:cl:
add: «Камень-ножницы-бумага» теперь в эмоут панели, можете играть
/:cl:
=> Add RPS into the emote panel

_maps/map_files220/RandomZLevels/gate_lizard.dmm, _maps/map_files220/RandomZLevels/spacebattle.dmm
После обновления эксплореров у старых ID карт доступ стал ACCESS_THETA_STATION (301). Появление тетовцев в гейтах маловероятно, поэтому просто поменял доступы машинерии на 301.
Убрал забытые активные турфы в гейте космобитва.
Машинерия с доступами снова работает в гейтах.
:cl:
fix: Починил сломанные доступы в гейтах.
/:cl:
=> Fix: awaymissions id issue

code/game/area/ss13_areas/supply_areas.dm
Меняет название зоны "экспИдиция" на "экспЕдиция"
Меньше ошибок хорошо скажется на будущем поколении. Кто знает. Может на ОГЭ попадётся это слово и они вспомнят сосаку и такие: "О, внатуре!"
Нема
Верю, что не ошибся
:cl:
spellcheck: "ЭкспИдиция" теперь "ЭкспЕдиция"
/:cl:
=> [Spellcheck] Она не "экспИдиция"

code/modules/events/door_runtime.dm
Убирает плюсик из слова "шлюзов" в ивенте об уязвимости сети т.к. эти плюсики в оповещениях не работают (и я не уверен, что работают вообще)
В данный момент выглядит как очепятка. Глаза болят
Вот отсюда \\/
Верю в свои силы
:cl:
spellcheck: Убрал плюсик из слова "шлюзов" в ивенте об уязвимости сети
/:cl:
=> [Spellcheck] Убираем плюсик из оповещения об уязвимости сети

modular_ss220/verbs/code/verbs.dm
Добавляем букву "ы"
да просто так... никак не хорошо... вообще плохой ПР...
Верю в свои силы
:cl:
spellcheck: Очепятка в сообщении при возрождении исправлена
/:cl:
=> [Spellcheck] "Вы уверен" заменено на "Вы уверены" при респавне

modular_ss220/redis220/code/news.dm
Изначально, иконка имеет все кадры анимации в себе, так что лучше слать только первый. Ну либо формировать из них гифку, но это будет кринж
=> Fix: send only one frame to redis

_maps/map_files220/stations/deltastation.dmm, modular_ss220/aesthetics/_aesthetics.dme, modular_ss220/aesthetics/lights/code/flashlight.dm, modular_ss220/maps220/code/Station/station_areas.dm
- Добавляет [Waste and Distribution Monitor](https://github.com/ParadiseSS13/Paradise/pull/25955)
- Стаскиваю и модифицирую церковь с оффов. Массдрайвер бтв.
- Немного почистил вар-эдитное говно.
- Изменил цвет света у lantern на тёплый (значения взяты с вар-едитного на Кибе).
Дельта чуть лучше чем сейчас
+ Мапдифф
:cl:
add: Дельта: Добавлен модифицированный ремап церкви с официалов.
tweak: Дельта: Добавлен Waste and Distribution Monitor в комнату управления атмосферного отдела.
fix: Дельта: Произведена небольшая стандартизация на карте.
tweak: Изменен цвет света у lantern на тёплый.
/:cl:
=> Delta: Actualization - Chapel, Distribution Monitor, Cleanup

_maps/map_files220/stations/boxstation.dmm
починил работу  Waste and Distribution Monitor
удобнее следить
брух. В дифе
вроде ворк
:cl:
fix: Кибериада: Waste and Distribution Monitor работает как положено (до этого оказывается работал неправильно).
/:cl:
=> Fix: Cyberiad Waste and Distribution Monitor

code/controllers/subsystem/SSredis.dm, modular_ss220/redis220/code/tgs_deploy_bandaid.dm
Заглушил бесполезный рантайм с предупреждением и теперь перезапускаю редис только при деплоях
=> Fix: more optimal redis bandaid

modular_ss220/clothing/code/shoes.dm, modular_ss220/loadout/code/donor.dm
Fixes https://github.com/ss220club/Paradise-SS220/issues/470
- Исправляет работу оверлея неоновых ботинок
- Код отсортирован
Оверлей будет отображаться корректно
https://github.com/ss220club/Paradise-SS220/assets/20109643/6488c929-6289-4784-a02e-73ff90f88908
:cl:
fix: Неоновые ботинки теперь корректно накладывают оверлей подсветки (да-да, оно было сломано).
/:cl:
=> Fix: Neon shoes overlay

modular_ss220/jobs/code/jobs.dm
Теперь трейни джобки работают следующем образом:
* Если в конфиге стоит -1 число, то они могут занимать любое количество слотов ВНУТРИ слотов основы (9 Кадетов из 9 Офицеров)
** Если и основа имеет -1, то может быть любое количество слотов (inf. Кадеты и inf. Офицеры)
* Если в конфиге стоит 0, то нельзя получить эту роль (0 Кадетов из 9 Офицеров)
* Если в конфиге стоит любое другое N число, то это значение отвечает за максимальное количество этих слотов ВНУТРИ слотов основы (N кадетов из 9 офицеров)
Данное ограничение работает ТОЛЬКО на трейни. Всякие "банщики" не были затронуты и имеют свои слоты.
=> Fix relate jobs?

modular_ss220/jobs/code/donor/job/5_tier_jobs.dm
Дебаффает количество кэша у банкира и випа. К сожалению заменить деньги на хорошую зарплату я не смог так как не разобрался по итогу как это сделать.
Игроки, которые раундстартом могут скупить карго, особенно при войне - это пиздец. Не забывайте что у них еще имеется раундстарт кэш на аккаунте.
Отдельно про банкира. Это роль, которая
а) ни разу не пользовались при мне по назначению, единственный раз я его застал в использовании в качестве торгаша - объективно выставляя торгаша в роль помойки.
б) имеет кол-во кэша больше чем у капитана и хранилища вместе взятые (раундстартом).
По хорошему Банкир должен быть вырезан/отключён, но мне жалко вырезать его, поэтому сделано так, как сделано.
:cl:
tweak: У роли Banker и VIP Corporate Guest понижен стартовый кэш. Banker 5к -> 1к, VIP 2к -> 1к. …
=> Debuff spacecash of VIP and Banker

modular_ss220/objects/_objects.dme, modular_ss220/objects/code/airlock_painter.dm
Добавляет возможность использовать краситель шлюзов на двойных шлюзах. При выборе стилей, у которых нету спрайтов двойных шлюзов выводит сообщение об этом пользователю.
Больше кастомизации при строительстве.
Пробежался на локалочке, всё покрасил, всё красивенько. Багов не заметил.
:cl:
tweak: Двойные шлюзы теперь можно красить (но только в определённые стили).
/:cl:
=> Paintable multi-tile airlocks

_maps/map_files220/generic/Lavaland.dmm
Заменяет пустой сундук на нормальный в Некрополисе
:cl:
fix: Пустой сундук в Некрополисе больше не пустой
/:cl:
=> Fix bad Necropolis crate

modular_ss220/title_screen/code/new_player.dm, modular_ss220/title_screen/code/title_screen_controls.dm, modular_ss220/title_screen/code/title_screen_datum.dm, modular_ss220/title_screen/html/title_screen.html
Добавил 2 кнопки в лобби для админов, можно быстро менять пикчу или нотис
Удобно
:cl:
add: Админам накинули 2 кнопки прямо в лобби: сменить арт в лобби и оставить уведомление там же.
tweak: Для тех у кого ну слишком маленький экран, добавлен скроллбар для пролистывания кнопочек
fix: В лобби больше ничего не должно скроллится по приколу
/:cl:
=> Add some buttons to title screen for admins

modular_ss220/keybindings/code/mob_keybinds.dm
В общем то закрывает вот этот ишуй https://github.com/ss220club/Paradise-SS220/issues/1218#issue-2291282636
Клавиша, (по дефолту) отвечающая за рацию, теперь не активирует предмет одновременно с этим
Потыкал гранаты и разные айтемы как на видосе
:cl:
fix: Клавиша, по умолчанию отвечающая за рацию, теперь не активирует предмет в руке
/:cl:
=> [FIX] Multiaction keybinding

modular_ss220/title_screen/code/new_player.dm, modular_ss220/title_screen/code/title_screen_datum.dm
При открытии настроек игры а потом перса, не будет настроек игры
:cl:
fix: Кнопки настроек в лобби теперь работают как надо
/:cl:
=> Fix title screen preferences tab

modular_ss220/text_to_speech/code/tts_component.dm
Перемещает verb "Смена голоса" во вкладку "Подсистемы" для киборгов/ИИ. Сейчас вкладки две с одинаковыми названиями, в одной из которых лежит только этот verb.
Меньше вкладок - кайф.
:cl: Maxiemar
tweak: Вкладки Subsystems и Подсистемы в статус панели теперь объединены.
/:cl:
=> Move 'Change voice' verb to existing tab

modular_ss220/bureaucracy/code/forms.dm
Пишет в форме год из глобальной переменной вместо хардкода.
Год в форме будет актуальным даже в следующем году.
=> CC form update but valid

_maps/map_files220/stations/boxstation.dmm, _maps/map_files220/stations/deltastation.dmm
Добавляет недостающую консоль на коробку.
Двигает консоль на дельте чуть в сторону, а то че она за холодильником прячется.
Меня попросили.
mapdiff
Не было
:cl: Maxiemar
fix: Недостающая консоль запросов добавлена в химию меда на Кибериаде.
/:cl:
=> Chemistry Request Consoles

_maps/map_files220/stations/deltastation.dmm
Пофиксил зоны камер ксенобиологии, чтобы они не вылезали за стены.
Поставил раундстарт болты на теха ксенобиологии.
Добавил недостающую машинерию.
Небольшая правка пайпинга в меде (наложение).
Немного сместил нагромождение лута прямо у входа в техи.
Мапдифф.
Проверил в игре.
:cl:
fix: Дельта: В меде исправлено наложение трубы скраббера.
fix: Дельта: В ксенобиологии РнД поправлены камеры, дабы они не вылезали за стены.
tweak: Дельта: Техи к проходной ксенобиологии теперь раундстартово заболтированы (разболтировать возможно по кнопке изнутри).
tweak: Дельта: В РнД добавлена недостающая машинерия.
/:cl:
=> Fix: Delta RnD another tweaks & fixes

_maps/map_files220/stations/metastation.dmm
Меняет зону в чекпоинте отбытия, а то там стоит консоль запросов, которая руинит тест.
Ну и добавляет туда апц, а то новая зона.
Ну это логично, и тест не падает.
Рантаймов нет и спасибо.
:cl: Maxiemar
tweak: КПП в отбытии на Мете теперь является отдельной зоной.
/:cl:
=> Edit exit checkpoint area on Cerebron

_maps/map_files220/stations/deltastation.dmm
Изменяет доступ на шлюзах свободного офиса на Дельте. На оффах там общий, все равно с обеих сторон свободный коридор.
Добавляет в комнату кнопку для затемнения окон.
Возможно порой сократить путь.
mapdiff
Зашел ассистентом, затемнил окна, сижу.
:cl: Maxiemar
fix: Свободный офис возле мостика на Дельте теперь имеет общий доступ.
tweak: Свободный офис возле мостика на Дельте теперь имеет затемняющиеся окна.
/:cl:
=> Set general access for vacant office on Kerberos

modular_ss220/wire_splicing/code/wiresplicing.dm
Чинит спавн разрывов проводки, чтобы они появлялись случайно, как и задумывалось. До этого они спавнились гарантированно.
Меньше ожогов, но и меньше веселья, увы.
Не во всех местах теперь появляются.
:cl: Maxiemar
fix: Проводка на станциях теперь реже оголяется.
/:cl:
=> Fix wire splicing spawning

_maps/map_files220/generic/centcomm.dmm
Добавлен доступ к оружейной зоне лидерам ЕРТ и оружейной уровня AMBER в частности. Это позволит авто-ЕРТ самостоятельно выдвигаться на станцию с какой-никакой экипировкой в отсутствии админов.
Авто-ЕРТ не будет сосать.
Вроде.
:cl:
tweak: ЦК: Добавлен доступ к оружейной зоне лидерам ЕРТ и оружейной уровня AMBER в частности. Это позволит авто-ЕРТ самостоятельно выдвигаться на станцию с какой-никакой экипировкой в отсутствии админов.
tweak: ЦК: Бластдоры к поду ЕРТ теперь под доступом лидера ЕРТ.
/:cl:
=> Qol changes for auto ERT

_maps/map_files220/stations/boxstation.dmm
Чуть двигает камеры, чуть добавляет.
Чуть меньше слепых зон ИИ там, где они не задумывались.
<details>
<summary>Spoiler</summary>
</details>
На ИИ видно, шлюзы доступны.
:cl: Maxiemar
tweak: На Кибериаде немного изменено местоположение камер. Теперь чуть меньше слепых зон.
/:cl:
=> Rearrange some cameras on Cyberiad

_maps/map_files220/stations/boxstation.dmm, _maps/map_files220/stations/deltastation.dmm, _maps/map_files220/stations/metastation.dmm
Чинит линковку фабрикатора.
Не нужен пароль от сервера раундстартом.
На коробке сработало.
:cl: Maxiemar
fix: Фабрикатор снова автоматически подключен к серверам РНД.
/:cl:
=> Fix autolinking of mech fabricator

modular_ss220/clothing/code/under.dm
Исправляет отсутствие спрайта на расовых спрайтах по типу вульпы и так далее. Заебало видеть челов, которые абузят спрайт и бегают с надписью suit :Fortune:
Меньше багов.
Протестировал на локалке.
:cl:
fix: Исправлено отсутствие спрайта у рас у костюма Катарины.
/:cl:
=> Fix Katarina species sprite

code/modules/admin/verbs/mapping_verbs.dm
Разрешает администрации устанавливать карты, недоступные для голосования. Не знаю, зачем было это запрещать. Простого способа выполнить это иначе не нахожу.
Возможно попробовать другие карты и покритиковать.
Выставить можно, проверить загрузку на локалке не удалось.
:cl: Maxiemar
tweak: Администрации теперь проще установить карты, недоступные для голосования.
/:cl:
=> Allow admins to set non votable maps

modular_ss220/antagonists/_antagonists.dm
Тоже самое что и это https://github.com/ss220club/Paradise-SS220/pull/1522, но модульно
И Я НЕ ЗНАЮ БУДЕТ ЛИ ОНО ТАК РАБОТАТЬ, но по крайней мере локалка работает и на том спасибо.
:cl:
tweak: Теперь для игры на Воксах-Рейдерах и Братьях по крови нужно наиграть часы на экипаже.
/:cl:
=> Tweak: Adds playtime requirement for Vox Raiders and Blood Brothers (Modular Edition)

code/game/verbs/who.dm
Правит классификацию стаффа путем изменения подсчета администрации. Теперь администратором считается клиент с правом `R_BAN`, а не `R_ADMIN`, потому что разработчики получили кнопки для отладки.
Не сбивает с толку игроков.
=> Consider `R_BAN` permission as admin permission

modular_ss220/balance/code/items/projectiles.dm, modular_ss220/maps220/code/walls.dm
Чинит попадание снарядов по телам в соответствии с #586.
Чинит флаги рикошета у турфа.
Fixes #1375.
Баги плохо.
<details>
<summary>Попадание в разных интентах</summary>
https://github.com/user-attachments/assets/3575944a-2d17-43fa-bbb5-866ed98c0f48
</details>
<details>
<summary>Попадание рикошетом</summary>
https://github.com/user-attachments/assets/a5f96070-b25d-4398-b718-a9d397fb12a7
</details>
:cl: Maxiemar
fix: Логика попадания теперь должна работать как ранее: снаряд проходит сквозь лежащую куклу в хелп интенте и не проходит в остальных.
fix: Стены белого шаттла снова отражают снаряды.
/:cl:
=> Projectile Fixes

_maps/map_files220/stations/boxstation.dmm, _maps/map_files220/stations/metastation.dmm
Добавляет магистрату на коробке и мете по принтеру.
Небольшая перестановка в офисе, чтоб влезло как надо.
Не надо ходить к агентам за принтером.
mapdiff
Есть принтер, печатает.
:cl: Maxiemar
tweak: В офисы магистратов на станциях поставили принтер.
tweak: Офис магистрата на Цереброне незначительно расширен.
/:cl:
=> Add a photocopier to Magistrate's office

_maps/map_files220/generic/Lavaland.dmm, _maps/map_files220/generic/centcomm.dmm, modular_ss220/maps220/code/objects.dm
- Переносит шаттл Гулага и Шахтёров на CC-уровень, раундстартово отправляя на шахту.
- Теперь все объекты engine не передают тепло и не пропускают атмос. Сделано это чтобы избежать лишних активных турфов раундстартом.
- Визуальные и логические изменения Гулага. Добавлена красивенькая посадочная площадка, голопады, консоль вызова шаттла в СБшной зоне Гулага и прочее.
Думайте...
Проверял на локалке.
:cl:
tweak: Лаваленд: Визуальные и минорные изменения "Гулага". Добавлена консоль вызова шаттла в СБшную зону, голопады и прочее.
experiment: Шаттлы Гулага и Шахтёров перенесены на CC-уровень, откуда раундстартом стартуют на Лаваленд. Ничего не должно сломаться, наверное.
/:cl:
=> Gulag (Labor camp) improvements & Move Lavaland shuttles to CC

_maps/map_files220/stations/boxstation.dmm
Исправил отсутствующий анрестриктед ацес хелпер в бриге киберуины
Ага
Ну локальная игра в соло
:cl:
fix: Кибериада: Возвращен флажок одностороннего доступа в бриге (точнее пофикшен его слёт, наверное).
/:cl:
=> Fix unrestricted access in Cyberiad brig

_maps/map_files220/stations/boxstation.dmm, _maps/map_files220/stations/deltastation.dmm
Добавил доступы исследователей в проходы к печкам на обоих картах.
Потому что так и должно быть
:cl:
fix: Теперь исследователи могут попасть к печке на Кибериаде и Керберосе.
/:cl:
=> Fix: Доступ исследователей к печке

_maps/map_files220/RandomRuins/LavaRuins/scp_facility.dmm
Заменяет `/obj/item/gun/energy/e_gun` (буквально является generic еганом без изменений) на `/obj/item/gun/energy/gun` в руине `scp_facility.dmm`.
Еган был generic'ом, который не предназначен для игроков. Он имел OOC описание и не имел применения в игре.
На локальном сервере.. еган настоящий, как в оружейной СБ.
:cl:
fix: Еган в руине СЦП на Лаваленде теперь рабочий.
/:cl:
=> Fixes generic energy gun in the scp ruin

_maps/map_files220/generic/Admin_Zone.dmm
Залатал дыру в ~~жопе~~ гост баре, которая появилась после мерге апстрима
:cl:
fix: Дыра в гост-баре была плодом вашего воображения
/:cl:
=> Fix Ghost Bar hole

modular_ss220/hydroponics/code/plants.dm
Добавляет замену иконки на иконку исходника, как с икон стейтом
Так что наши семена должны быть с спрайтом
Вырастил огурец, семена имели спрайт
:cl:
fix: Несортированные огурцы, угливки, гречка и горохострел должны вернуть свой спрайт
/:cl:
=> Fix unsorted modular seed sprite

modular_ss220/text_to_speech/code/obj/hologram.dm
Чинит рантайм голопада.
```
[2024-11-05T18:24:31] Runtime in code/obj/hologram.dm:5: Cannot execute null. AddComponent().
proc name: activate holo (/obj/machinery/hologram/holopad/activate_holo)
usr: [NT_REDACTED] ([NT_REDACTED]) (/mob/living/silicon/ai)
usr.loc: The floor (160,23,3) (/turf/simulated/floor/bluegrid)
src: the holopad (/obj/machinery/hologram/holopad)
src.loc: the floor (92,178,3) (/turf/simulated/floor/plasteel)
call stack:
the holopad (/obj/machinery/hologram/holopad): activate_holo
the holopad (/obj/machinery/hologram/holopad): attack_ai
[NT_REDACTED] (/mob/living/silicon/ai): ClickOn
the holopad (/obj/machinery/hologram/holopad): Click
[NT_REDACTED](/client): Click
```
Ничего не изменилось.
Нет.
=> Fix holopad runtime

modular_ss220/_defines220/code/signals_obj.dm, modular_ss220/security_redalert_accesses/_security_redalert_accesses.dm, modular_ss220/security_redalert_accesses/_security_redalert_accesses.dme, modular_ss220/security_redalert_accesses/code/security_redalert_accesses.dm, modular_ss220/security_redalert_accesses/code/security_redalert_element.dm
Добавляет элемент, который будет улавливать сигнал получения доступа для предоставления новых доступов, а не добавлять доступа на карту.
По факту, доступ на карте не изменяется. Если каким-то образом пропал доступ секурити, то расширенный доступ будет отключен на карте.
Так же, теперь после получении полного доступа в красный через консоль (модификация карты), когда снижается код до синего - доступа остаются на карте
Ловушка сигналов и `.` в сигнале взяла своё
:cl:
tweak: [PRIME] Расширенный доступ на карте теперь проверяется не по поднятию кода, а при проверке доступа. Этот расширенный доступ не изменяет текущий доступ карты, а лишь дополняет при проверке доступа. Иными словами, можно получить полный доступ у ГП при красном коде, и на синем коде этот доступ не пропадет с карты.
/:cl:
=> Use element for red alert access

modular_ss220/objects/code/id_skins/_id_skins_base.dm
Заменил проверки снятия наклейки на стандартизированные и более надёжные
Чел не сможет через камеру спиздить наклейка
БС магия
:cl:
fix: Консоли камер были наделены Блюспейс магией, из-за чего через них можно было воровать наклейки с карт. Инквизиция НТ разобралась с этой проблемой. Федерации Магов НЕ победить!
/:cl:
=> Fix ID Skins interaction

.github/workflows/render_nanomaps.yml
Скипает джоб, если нет изменений, вместо фейла.
Наверное, поможет и ничего не сломаю.
```
pull request create failed: GraphQL: No commits between master and nanomap-render (createPullRequest)
```
=> Prevent Nanomaps Render failure if no changes

_maps/map_files220/stations/metastation.dmm
Добавляет vial storage box вирусологию на карте metastation.
На других картах, такая коробочка есть. В ней удобно смешивать вещества и делать вирусы. Сделать её в игре нельзя, а значит она должна быть на карте.
Проверил на локалке, всё на месте.
:cl:
add: vial storage box теперь есть в вирусологии на metastation
/:cl:
=> Added a vial storage box to metastation

_maps/map_files220/stations/boxstation.dmm, _maps/map_files220/stations/deltastation.dmm, _maps/map_files220/stations/metastation.dmm
Не заметил пропажу анализатора после переименования. Возвращаю обратно.
Нет.
:cl: Maxiemar
fix: Научный анализатор снова доступен в РНД.
/:cl:
=> Bring scientific analyzer back

modular_ss220/events/code/christmas.dm
Возвращает спрайт тренировочной нюке.
Тренировочную нюку видно.
Увидел тренировочную нюку.
Стандартная нюка все еще праздничная.
:cl: Maxiemar
fix: Тренировочную нюку снова видно.
/:cl:
=> Bring training bomb back

modular_ss220/objects/code/id_skins/_id_skins_base.dm
Фиксит конфликт сочетания клавиш.
Скин для ID карты и гостевой пропуск использовали одинаковое сочетание клавиш для открепления от ID карты.
Сделал скину ID карты снятие на Ctrl-Shift-Click (ранее было Alt-Click), изменил IC описание действия.
Фиксы мы любим.
В разном порядке ставил/снимал на ID карту гостевой пропуск и наклейку, всё работает корректно.
:cl:
fix: Теперь ID карты корректно работают с гостевыми пропусками и наклейками
/:cl:
=> Fix conflict between ID cards and a guest pass
